DEMO_LOGS = [
    {
        "id": 1,
        "matter": "Estate Planning",
        "client": "Smith & Co.",
        "date": "2025-05-19",
        "hours": 2,
        "description": "Consultation",
        "status": "Billable",
    },
    {
        "id": 2,
        "matter": "IP Filing",
        "client": "Acme Biotech",
        "date": "2025-05-18",
        "hours": 1.5,
        "description": "Draft application",
        "status": "Billed",
    },
    {
        "id": 3,
        "matter": "M&A Advice",
        "client": "Peak Ventures",
        "date": "2025-05-16",
        "hours": 3,
        "description": "Negotiation call",
        "status": "Billable",
    },
]

CALENDAR_DATA = [
    {
        "id": 1,
        "date": "2025-05-06",
        "label": "Smith Matter: Signing",
        "time": "11:00am",
        "color": "forest",
    },
    {
        "id": 2,
        "date": "2025-05-07",
        "label": "Internal Review",
        "time": "2:30pm",
        "color": "indigo",
    },
    {
        "id": 3,
        "date": "2025-05-13",
        "label": "Court Filing",
        "time": "9:00am",
        "color": "blue",
    },
    {
        "id": 4,
        "date": "2025-05-18",
        "label": "Client Call - Jessica",
        "time": "2:00pm",
        "color": "forest",
    },
    {
        "id": 5,
        "date": "2025-05-18",
        "label": "M&A: Docs Due",
        "time": "5:00pm",
        "color": "indigo",
    },
    {
        "id": 6,
        "date": "2025-05-22",
        "label": "Staff Meeting",
        "time": "1:30pm",
        "color": "zinc",
    },
]
CLIENT_DATA = [
    {
        "id": "CL-101",
        "name": "Smith & Co.",
        "email": "team@smithco.com",
        "matters": 3,
        "avatar": "",
        "status": "Active",
        "last": "3d ago",
    },
    {
        "id": "CL-098",
        "name": "Jessica Brown",
        "email": "jbrown@samplemail.com",
        "matters": 1,
        "avatar": "",
        "status": "Active",
        "last": "5d ago",
    },
    {
        "id": "CL-092",
        "name": "Acme Biotech",
        "email": "legal@acmebio.com",
        "matters": 2,
        "avatar": "",
        "status": "On Hold",
        "last": "2w ago",
    },
    {
        "id": "CL-086",
        "name": "Peak Ventures",
        "email": "peak@ventures.com",
        "matters": 4,
        "avatar": "",
        "status": "Active",
        "last": "1mo ago",
    },
]
DOCUMENT_DATA = [
    {
        "id": 1,
        "name": "Retainer-Agreement.pdf",
        "size": "234 KB",
        "version": "v2",
        "updated": "Today",
        "status": "Signed",
    },
    {
        "id": 2,
        "name": "Client-Onboarding.docx",
        "size": "82 KB",
        "version": "v1",
        "updated": "This week",
        "status": "Draft",
    },
    {
        "id": 3,
        "name": "Patent-Application.pdf",
        "size": "1.3 MB",
        "version": "v4",
        "updated": "last month",
        "status": "Submitted",
    },
]
MATTERS_DATA = [
    {
        "id": "MAT-0012",
        "name": "Estate Planning",
        "status": "Active",
        "client": "Smith & Co.",
        "updated": "Today",
    },
    {
        "id": "MAT-0011",
        "name": "Contract Review",
        "status": "Archived",
        "client": "Jones Legal",
        "updated": "2 days ago",
    },
    {
        "id": "MAT-0009",
        "name": "IP Filing",
        "status": "Active",
        "client": "Acme Biotech",
        "updated": "last week",
    },
    {
        "id": "MAT-0005",
        "name": "M&A Advice",
        "status": "On Hold",
        "client": "Peak Ventures",
        "updated": "Yesterday",
    },
]
