RESTAURANT_DATA = [
    {
        "id": "restaurant-1",
        "name": "The Royal Dine",
        "rating": 3,
        "reviews": 18,
        "bookings": 6,
        "price": "$$",
        "cuisine": "French",
        "desc": "Enjoy a delightful experience at The Royal Dine, offering a fusion of flavors in the heart of Mission District.",
    },
    {
        "id": "restaurant-2",
        "name": "Vintage Bites",
        "rating": 4,
        "reviews": 22,
        "bookings": 12,
        "price": "$$$",
        "cuisine": "Italian",
        "desc": "Enjoy a delightful experience at Vintage Bites, offering a fusion of flavors in the heart of SOMA.",
    },
    {
        "id": "restaurant-3",
        "name": "Evening Delight",
        "rating": 5,
        "reviews": 35,
        "bookings": 17,
        "price": "$$$$",
        "cuisine": "American",
        "desc": "Enjoy a delightful experience at Evening Delight, offering a fusion of flavors in the heart of North Beach.",
    },
    {
        "id": "restaurant-4",
        "name": "River View Café",
        "rating": 4,
        "reviews": 47,
        "bookings": 23,
        "price": "$$",
        "cuisine": "Japanese",
        "desc": "Enjoy a delightful experience at River View Café, offering a fusion of flavors in the heart of Downtown.",
    },
    {
        "id": "restaurant-5",
        "name": "Fancy Lights Bistro",
        "rating": 5,
        "reviews": 53,
        "bookings": 27,
        "price": "$$$",
        "cuisine": "Mexican",
        "desc": "Enjoy a delightful experience at Fancy Lights Bistro, offering a fusion of flavors in the heart of Hayes Valley.",
    },
    {
        "id": "restaurant-6",
        "name": "Urban Palate",
        "rating": 3,
        "reviews": 62,
        "bookings": 32,
        "price": "$$$$",
        "cuisine": "Indian",
        "desc": "Enjoy a delightful experience at Urban Palate, offering a fusion of flavors in the heart of Nob Hill.",
    },
    {
        "id": "restaurant-7",
        "name": "Tandoori House",
        "rating": 4,
        "reviews": 71,
        "bookings": 37,
        "price": "$$",
        "cuisine": "Thai",
        "desc": "Enjoy a delightful experience at Tandoori House, offering a fusion of flavors in the heart of Japantown.",
    },
    {
        "id": "restaurant-8",
        "name": "Zen Sushi",
        "rating": 5,
        "reviews": 28,
        "bookings": 40,
        "price": "$$$",
        "cuisine": "Café",
        "desc": "Enjoy a delightful experience at Zen Sushi, offering a fusion of flavors in the heart of Embarcadero.",
    },
    {
        "id": "restaurant-9",
        "name": "El Toro",
        "rating": 3,
        "reviews": 39,
        "bookings": 43,
        "price": "$$$$",
        "cuisine": "Mediterranean",
        "desc": "Enjoy a delightful experience at El Toro, offering a fusion of flavors in the heart of Marina.",
    },
    {
        "id": "restaurant-10",
        "name": "Bella Vita",
        "rating": 4,
        "reviews": 44,
        "bookings": 50,
        "price": "$$",
        "cuisine": "French",
        "desc": "Enjoy a delightful experience at Bella Vita, offering a fusion of flavors in the heart of Mission District.",
    },
    {
        "id": "restaurant-11",
        "name": "Coastal Catch",
        "rating": 3,
        "reviews": 55,
        "bookings": 57,
        "price": "$$$",
        "cuisine": "Italian",
        "desc": "Enjoy a delightful experience at Coastal Catch, offering a fusion of flavors in the heart of SOMA.",
    },
    {
        "id": "restaurant-12",
        "name": "Harvest Table",
        "rating": 5,
        "reviews": 66,
        "bookings": 65,
        "price": "$$$$",
        "cuisine": "American",
        "desc": "Enjoy a delightful experience at Harvest Table, offering a fusion of flavors in the heart of North Beach.",
    },
    {
        "id": "restaurant-13",
        "name": "Crimson Spoon",
        "rating": 4,
        "reviews": 72,
        "bookings": 67,
        "price": "$$",
        "cuisine": "Japanese",
        "desc": "Enjoy a delightful experience at Crimson Spoon, offering a fusion of flavors in the heart of Downtown.",
    },
    {
        "id": "restaurant-14",
        "name": "Golden Lotus",
        "rating": 5,
        "reviews": 80,
        "bookings": 69,
        "price": "$$$",
        "cuisine": "Mexican",
        "desc": "Enjoy a delightful experience at Golden Lotus, offering a fusion of flavors in the heart of Hayes Valley.",
    },
    {
        "id": "restaurant-15",
        "name": "The Hungry Fork",
        "rating": 3,
        "reviews": 91,
        "bookings": 74,
        "price": "$$$$",
        "cuisine": "Indian",
        "desc": "Enjoy a delightful experience at The Hungry Fork, offering a fusion of flavors in the heart of Nob Hill.",
    },
    {
        "id": "restaurant-16",
        "name": "Ocean's Plate",
        "rating": 4,
        "reviews": 24,
        "bookings": 79,
        "price": "$$",
        "cuisine": "Thai",
        "desc": "Enjoy a delightful experience at Ocean's Plate, offering a fusion of flavors in the heart of Japantown.",
    },
    {
        "id": "restaurant-17",
        "name": "Fire & Spice",
        "rating": 5,
        "reviews": 31,
        "bookings": 84,
        "price": "$$$",
        "cuisine": "Café",
        "desc": "Enjoy a delightful experience at Fire & Spice, offering a fusion of flavors in the heart of Embarcadero.",
    },
    {
        "id": "restaurant-18",
        "name": "Olive & Vine",
        "rating": 3,
        "reviews": 42,
        "bookings": 86,
        "price": "$$$$",
        "cuisine": "Mediterranean",
        "desc": "Enjoy a delightful experience at Olive & Vine, offering a fusion of flavors in the heart of Marina.",
    },
    {
        "id": "restaurant-19",
        "name": "La Bella Cucina",
        "rating": 4,
        "reviews": 48,
        "bookings": 89,
        "price": "$$",
        "cuisine": "French",
        "desc": "Enjoy a delightful experience at La Bella Cucina, offering a fusion of flavors in the heart of Mission District.",
    },
    {
        "id": "restaurant-20",
        "name": "Sunset Grill",
        "rating": 5,
        "reviews": 60,
        "bookings": 92,
        "price": "$$$",
        "cuisine": "Italian",
        "desc": "Enjoy a delightful experience at Sunset Grill, offering a fusion of flavors in the heart of SOMA.",
    },
    {
        "id": "restaurant-21",
        "name": "Noir Brasserie",
        "rating": 4,
        "reviews": 70,
        "bookings": 94,
        "price": "$$$$",
        "cuisine": "American",
        "desc": "Enjoy a delightful experience at Noir Brasserie, offering a fusion of flavors in the heart of North Beach.",
    },
    {
        "id": "restaurant-22",
        "name": "Blue Orchid",
        "rating": 5,
        "reviews": 15,
        "bookings": 97,
        "price": "$$",
        "cuisine": "Japanese",
        "desc": "Enjoy a delightful experience at Blue Orchid, offering a fusion of flavors in the heart of Downtown.",
    },
    {
        "id": "restaurant-23",
        "name": "Saffron Garden",
        "rating": 3,
        "reviews": 33,
        "bookings": 98,
        "price": "$$$",
        "cuisine": "Mexican",
        "desc": "Enjoy a delightful experience at Saffron Garden, offering a fusion of flavors in the heart of Hayes Valley.",
    },
    {
        "id": "restaurant-24",
        "name": "Rustic Roots",
        "rating": 4,
        "reviews": 45,
        "bookings": 100,
        "price": "$$$$",
        "cuisine": "Indian",
        "desc": "Enjoy a delightful experience at Rustic Roots, offering a fusion of flavors in the heart of Nob Hill.",
    },
    {
        "id": "restaurant-25",
        "name": "Amber Lounge",
        "rating": 5,
        "reviews": 59,
        "bookings": 13,
        "price": "$$",
        "cuisine": "Thai",
        "desc": "Enjoy a delightful experience at Amber Lounge, offering a fusion of flavors in the heart of Japantown.",
    },
    {
        "id": "restaurant-26",
        "name": "Bistro Lumière",
        "rating": 3,
        "reviews": 63,
        "bookings": 14,
        "price": "$$$",
        "cuisine": "Café",
        "desc": "Enjoy a delightful experience at Bistro Lumière, offering a fusion of flavors in the heart of Embarcadero.",
    },
    {
        "id": "restaurant-27",
        "name": "Maple Hearth",
        "rating": 4,
        "reviews": 76,
        "bookings": 16,
        "price": "$$$$",
        "cuisine": "Mediterranean",
        "desc": "Enjoy a delightful experience at Maple Hearth, offering a fusion of flavors in the heart of Marina.",
    },
    {
        "id": "restaurant-28",
        "name": "Oak & Ember",
        "rating": 5,
        "reviews": 81,
        "bookings": 20,
        "price": "$$",
        "cuisine": "French",
        "desc": "Enjoy a delightful experience at Oak & Ember, offering a fusion of flavors in the heart of Mission District.",
    },
    {
        "id": "restaurant-29",
        "name": "Peppercorn Place",
        "rating": 3,
        "reviews": 95,
        "bookings": 21,
        "price": "$$$",
        "cuisine": "Italian",
        "desc": "Enjoy a delightful experience at Peppercorn Place, offering a fusion of flavors in the heart of SOMA.",
    },
    {
        "id": "restaurant-30",
        "name": "The Local Dish",
        "rating": 4,
        "reviews": 38,
        "bookings": 25,
        "price": "$$$$",
        "cuisine": "American",
        "desc": "Enjoy a delightful experience at The Local Dish, offering a fusion of flavors in the heart of North Beach.",
    },
    {
        "id": "restaurant-31",
        "name": "Cedar Grove Café",
        "rating": 5,
        "reviews": 49,
        "bookings": 30,
        "price": "$$",
        "cuisine": "Japanese",
        "desc": "Enjoy a delightful experience at Cedar Grove Café, offering a fusion of flavors in the heart of Downtown.",
    },
    {
        "id": "restaurant-32",
        "name": "Soleil Bistro",
        "rating": 4,
        "reviews": 51,
        "bookings": 34,
        "price": "$$$",
        "cuisine": "Mexican",
        "desc": "Enjoy a delightful experience at Soleil Bistro, offering a fusion of flavors in the heart of Hayes Valley.",
    },
    {
        "id": "restaurant-33",
        "name": "Brickhouse Eats",
        "rating": 5,
        "reviews": 58,
        "bookings": 41,
        "price": "$$$$",
        "cuisine": "Indian",
        "desc": "Enjoy a delightful experience at Brickhouse Eats, offering a fusion of flavors in the heart of Nob Hill.",
    },
    {
        "id": "restaurant-34",
        "name": "Wanderlust Grill",
        "rating": 3,
        "reviews": 64,
        "bookings": 52,
        "price": "$$",
        "cuisine": "Thai",
        "desc": "Enjoy a delightful experience at Wanderlust Grill, offering a fusion of flavors in the heart of Japantown.",
    },
    {
        "id": "restaurant-35",
        "name": "The Nest",
        "rating": 4,
        "reviews": 77,
        "bookings": 56,
        "price": "$$$",
        "cuisine": "Café",
        "desc": "Enjoy a delightful experience at The Nest, offering a fusion of flavors in the heart of Embarcadero.",
    },
    {
        "id": "restaurant-36",
        "name": "Cafe Verona",
        "rating": 5,
        "reviews": 82,
        "bookings": 68,
        "price": "$$$$",
        "cuisine": "Mediterranean",
        "desc": "Enjoy a delightful experience at Cafe Verona, offering a fusion of flavors in the heart of Marina.",
    },
    {
        "id": "restaurant-37",
        "name": "Midtown Meals",
        "rating": 3,
        "reviews": 87,
        "bookings": 75,
        "price": "$$",
        "cuisine": "French",
        "desc": "Enjoy a delightful experience at Midtown Meals, offering a fusion of flavors in the heart of Mission District.",
    },
    {
        "id": "restaurant-38",
        "name": "Ginger & Thyme",
        "rating": 4,
        "reviews": 90,
        "bookings": 78,
        "price": "$$$",
        "cuisine": "Italian",
        "desc": "Enjoy a delightful experience at Ginger & Thyme, offering a fusion of flavors in the heart of SOMA.",
    },
    {
        "id": "restaurant-39",
        "name": "Lavender & Sage",
        "rating": 5,
        "reviews": 96,
        "bookings": 83,
        "price": "$$$$",
        "cuisine": "American",
        "desc": "Enjoy a delightful experience at Lavender & Sage, offering a fusion of flavors in the heart of North Beach.",
    },
    {
        "id": "restaurant-40",
        "name": "Hearthstone Inn",
        "rating": 4,
        "reviews": 99,
        "bookings": 93,
        "price": "$$",
        "cuisine": "Japanese",
        "desc": "Enjoy a delightful experience at Hearthstone Inn, offering a fusion of flavors in the heart of Downtown.",
    },
    {
        "id": "restaurant-41",
        "name": "Juniper Table",
        "rating": 3,
        "reviews": 19,
        "bookings": 7,
        "price": "$$$",
        "cuisine": "Mexican",
        "desc": "Enjoy a delightful experience at Juniper Table, offering a fusion of flavors in the heart of Hayes Valley.",
    },
    {
        "id": "restaurant-42",
        "name": "The Garden Fork",
        "rating": 4,
        "reviews": 26,
        "bookings": 8,
        "price": "$$$$",
        "cuisine": "Indian",
        "desc": "Enjoy a delightful experience at The Garden Fork, offering a fusion of flavors in the heart of Nob Hill.",
    },
    {
        "id": "restaurant-43",
        "name": "Twilight Tapas",
        "rating": 5,
        "reviews": 29,
        "bookings": 9,
        "price": "$$",
        "cuisine": "Thai",
        "desc": "Enjoy a delightful experience at Twilight Tapas, offering a fusion of flavors in the heart of Japantown.",
    },
    {
        "id": "restaurant-44",
        "name": "Meadow & Moor",
        "rating": 3,
        "reviews": 36,
        "bookings": 10,
        "price": "$$$",
        "cuisine": "Café",
        "desc": "Enjoy a delightful experience at Meadow & Moor, offering a fusion of flavors in the heart of Embarcadero.",
    },
    {
        "id": "restaurant-45",
        "name": "The Vine",
        "rating": 4,
        "reviews": 46,
        "bookings": 11,
        "price": "$$$$",
        "cuisine": "Mediterranean",
        "desc": "Enjoy a delightful experience at The Vine, offering a fusion of flavors in the heart of Marina.",
    },
    {
        "id": "restaurant-46",
        "name": "Ember Flame",
        "rating": 5,
        "reviews": 54,
        "bookings": 35,
        "price": "$$",
        "cuisine": "French",
        "desc": "Enjoy a delightful experience at Ember Flame, offering a fusion of flavors in the heart of Mission District.",
    },
    {
        "id": "restaurant-47",
        "name": "Miso Modern",
        "rating": 3,
        "reviews": 61,
        "bookings": 38,
        "price": "$$$",
        "cuisine": "Italian",
        "desc": "Enjoy a delightful experience at Miso Modern, offering a fusion of flavors in the heart of SOMA.",
    },
    {
        "id": "restaurant-48",
        "name": "The Borough",
        "rating": 4,
        "reviews": 73,
        "bookings": 60,
        "price": "$$$$",
        "cuisine": "American",
        "desc": "Enjoy a delightful experience at The Borough, offering a fusion of flavors in the heart of North Beach.",
    },
    {
        "id": "restaurant-49",
        "name": "Copper Kitchen",
        "rating": 5,
        "reviews": 85,
        "bookings": 70,
        "price": "$$",
        "cuisine": "Japanese",
        "desc": "Enjoy a delightful experience at Copper Kitchen, offering a fusion of flavors in the heart of Downtown.",
    },
    {
        "id": "restaurant-50",
        "name": "Pine & Poppy",
        "rating": 4,
        "reviews": 88,
        "bookings": 90,
        "price": "$$$",
        "cuisine": "Mexican",
        "desc": "Enjoy a delightful experience at Pine & Poppy, offering a fusion of flavors in the heart of Hayes Valley.",
    },
]
RESTAURANT_TIMES = ["12:30 PM", "01:00 PM", "01:30 PM", "02:00 PM", "02:30 PM"]
RESTAURANT_PEOPLE_COUNTS = [1, 2, 3, 4, 5, 6, 7, 8]
RESTAURANT_COUNTRIES = [
    {"code": "AR", "name": "Argentina"},
    {"code": "AU", "name": "Australia"},
    {"code": "BD", "name": "Bangladesh"},
    {"code": "BR", "name": "Brazil"},
    {"code": "CA", "name": "Canada"},
    {"code": "CN", "name": "China"},
    {"code": "EG", "name": "Egypt"},
    {"code": "FR", "name": "France"},
    {"code": "DE", "name": "Germany"},
    {"code": "IN", "name": "India"},
    {"code": "ID", "name": "Indonesia"},
    {"code": "IT", "name": "Italy"},
    {"code": "JP", "name": "Japan"},
    {"code": "MX", "name": "Mexico"},
    {"code": "MY", "name": "Malaysia"},
    {"code": "NG", "name": "Nigeria"},
    {"code": "NL", "name": "Netherlands"},
    {"code": "PK", "name": "Pakistan"},
    {"code": "PH", "name": "Philippines"},
    {"code": "PL", "name": "Poland"},
    {"code": "RU", "name": "Russia"},
    {"code": "SA", "name": "Saudi Arabia"},
    {"code": "ZA", "name": "South Africa"},
    {"code": "KR", "name": "South Korea"},
    {"code": "ES", "name": "Spain"},
    {"code": "SE", "name": "Sweden"},
    {"code": "CH", "name": "Switzerland"},
    {"code": "TH", "name": "Thailand"},
    {"code": "TR", "name": "Turkey"},
    {"code": "AE", "name": "United Arab Emirates"},
    {"code": "GB", "name": "United Kingdom"},
    {"code": "US", "name": "United States"},
    {"code": "VN", "name": "Vietnam"},
]
RESTAURANT_OCCASIONS = ["birthday", "anniversary", "business meeting", "other"]
