from datetime import datetime

from dateutil import parser

from ..operators import CONTAINS, EQUALS, GREATER_EQUAL, GREATER_THAN, IN_LIST, LESS_EQUAL, LESS_THAN, NOT_CONTAINS, NOT_EQUALS, NOT_IN_LIST

DASHBOARD_HOTELS = [
    {
        "id": 1,
        "image": "/images/hotel1.jpeg",
        "title": "The Pinewood Chalet",
        "location": "Lake Tahoe, USA",
        "rating": 4.7,
        "reviews": 124,
        "guests": 4,
        "maxGuests": 4,
        "bedrooms": 2,
        "beds": 2,
        "baths": 2,
        "datesFrom": "2025-05-03",
        "datesTo": "2025-07-13",
        "price": 189,
        "host": {"name": "Emily", "since": 3, "avatar": "https://randomuser.me/api/portraits/women/65.jpg"},
        "amenities": [
            {"icon": "💻", "title": "Dedicated workspace", "desc": "A common area with wifi that's well-suited for working."},
            {"icon": "📍", "title": "Great location", "desc": "Close to hiking trails and the lake shore."},
            {"icon": "🔍", "title": "Easy check-in", "desc": "Guests loved the seamless self-check-in process."},
        ],
    },
    {
        "id": 2,
        "image": "/images/hotel2.jpeg",
        "title": "Sunset Beach Bungalow",
        "location": "Goa, India",
        "rating": 4.5,
        "reviews": 98,
        "guests": 2,
        "maxGuests": 2,
        "bedrooms": 1,
        "beds": 1,
        "baths": 1,
        "datesFrom": "2025-05-03",
        "datesTo": "2025-07-13",
        "price": 104,
        "host": {"name": "Raj", "since": 2, "avatar": "https://randomuser.me/api/portraits/men/23.jpg"},
        "amenities": [
            {"icon": "💻", "title": "WiFi included", "desc": "Reliable high-speed internet connection."},
            {"icon": "📍", "title": "Prime beach access", "desc": "Step out directly onto the sandy beach."},
            {"icon": "🔍", "title": "Local guidebooks", "desc": "Explore nearby restaurants and attractions."},
        ],
    },
    {
        "id": 3,
        "image": "/images/hotel3.png",
        "title": "Alpine Retreat Lodge",
        "location": "Zermatt, Switzerland",
        "rating": 4.9,
        "reviews": 212,
        "guests": 6,
        "maxGuests": 6,
        "bedrooms": 3,
        "beds": 3,
        "baths": 2,
        "datesFrom": "2025-07-12",
        "datesTo": "2025-07-21",
        "price": 320,
        "host": {"name": "Luca", "since": 5, "avatar": "https://randomuser.me/api/portraits/men/54.jpg"},
        "amenities": [
            {"icon": "💻", "title": "Work-friendly space", "desc": "Large table and mountain views for productivity."},
            {"icon": "📍", "title": "Ski-in, Ski-out", "desc": "Direct access to the Matterhorn slopes."},
            {"icon": "🔍", "title": "Luxury amenities", "desc": "Fireplace, spa tub, and heated floors included."},
        ],
    },
    {
        "id": 4,
        "image": "/images/hotel4.png",
        "title": "Riverside Zen Cottage",
        "location": "Kyoto, Japan",
        "rating": 4.8,
        "reviews": 163,
        "guests": 2,
        "maxGuests": 2,
        "bedrooms": 1,
        "beds": 1,
        "baths": 1,
        "datesFrom": "2025-03-09",
        "datesTo": "2025-07-16",
        "price": 142,
        "host": {"name": "Aiko", "since": 6, "avatar": "https://randomuser.me/api/portraits/women/33.jpg"},
        "amenities": [
            {"icon": "💻", "title": "Tatami workspace", "desc": "Low table with garden view and high-speed wifi."},
            {"icon": "📍", "title": "Near Gion District", "desc": "Walking distance to temples and tea houses."},
            {"icon": "🔍", "title": "Traditional style", "desc": "Shoji doors, futon beds, and stone bath."},
        ],
    },
    {
        "id": 5,
        "image": "/images/hotel5.png",
        "title": "Bohemian Loft",
        "location": "Lisbon, Portugal",
        "rating": 4.6,
        "reviews": 81,
        "guests": 3,
        "maxGuests": 3,
        "bedrooms": 1,
        "beds": 2,
        "baths": 1,
        "datesFrom": "2025-03-13",
        "datesTo": "2025-07-16",
        "price": 115,
        "host": {"name": "Beatriz", "since": 4, "avatar": "https://randomuser.me/api/portraits/women/22.jpg"},
        "amenities": [
            {"icon": "💻", "title": "Fast WiFi", "desc": "Perfect for remote work or video calls."},
            {"icon": "📍", "title": "Central Alfama", "desc": "Right in the heart of old Lisbon."},
            {"icon": "🔍", "title": "City views", "desc": "Rooftop access with panoramic skyline."},
        ],
    },
    {
        "id": 6,
        "image": "/images/hotel6.png",
        "title": "Cozy City Apartment",
        "location": "Amsterdam, Netherlands",
        "rating": 4.3,
        "reviews": 76,
        "guests": 2,
        "maxGuests": 2,
        "bedrooms": 1,
        "beds": 1,
        "baths": 1,
        "datesFrom": "2025-03-09",
        "datesTo": "2025-07-21",
        "price": 134,
        "host": {"name": "Jasper", "since": 2, "avatar": "https://randomuser.me/api/portraits/men/19.jpg"},
        "amenities": [
            {"icon": "💻", "title": "Desk & chair", "desc": "Work-friendly setup in a quiet corner."},
            {"icon": "📍", "title": "Near canals", "desc": "2-minute walk to iconic canal paths."},
            {"icon": "🔍", "title": "Bike rental available", "desc": "Host offers bikes for local exploring."},
        ],
    },
    {
        "id": 7,
        "image": "/images/hotel7.jpg",
        "title": "Modern Desert Villa",
        "location": "Sedona, USA",
        "rating": 4.9,
        "reviews": 205,
        "guests": 5,
        "maxGuests": 5,
        "bedrooms": 2,
        "beds": 3,
        "baths": 2,
        "datesFrom": "2025-05-03",
        "datesTo": "2025-07-13",
        "price": 245,
        "host": {"name": "Melissa", "since": 7, "avatar": "https://randomuser.me/api/portraits/women/11.jpg"},
        "amenities": [
            {"icon": "💻", "title": "Outdoor workspace", "desc": "Covered patio with power and WiFi."},
            {"icon": "📍", "title": "Red rock views", "desc": "Floor-to-ceiling windows face the mountains."},
            {"icon": "🔍", "title": "Private pool", "desc": "Saltwater pool with night lighting."},
        ],
    },
    {
        "id": 8,
        "image": "/images/hotel8.jpg",
        "title": "The Garden House",
        "location": "Melbourne, Australia",
        "rating": 4.4,
        "reviews": 63,
        "guests": 3,
        "maxGuests": 3,
        "bedrooms": 1,
        "beds": 2,
        "baths": 1,
        "datesFrom": "2025-07-12",
        "datesTo": "2025-07-21",
        "price": 129,
        "host": {"name": "Tom", "since": 3, "avatar": "https://randomuser.me/api/portraits/men/47.jpg"},
        "amenities": [
            {"icon": "💻", "title": "Sunroom workspace", "desc": "Natural light and lush garden views."},
            {"icon": "📍", "title": "Botanic Gardens nearby", "desc": "Walk to iconic Royal Botanic Gardens."},
            {"icon": "🔍", "title": "Eco-friendly", "desc": "Solar-powered with recycling facilities."},
        ],
    },
    {
        "id": 9,
        "image": "/images/hotel9.jpg",
        "title": "Artisan Brick Loft",
        "location": "Brooklyn, USA",
        "rating": 4.2,
        "reviews": 47,
        "guests": 2,
        "maxGuests": 2,
        "bedrooms": 1,
        "beds": 1,
        "baths": 1,
        "datesFrom": "2025-03-13",
        "datesTo": "2025-07-13",
        "price": 159,
        "host": {"name": "Marcus", "since": 5, "avatar": "https://randomuser.me/api/portraits/men/38.jpg"},
        "amenities": [
            {"icon": "💻", "title": "Studio desk", "desc": "Creative space for writing or editing."},
            {"icon": "📍", "title": "Trendy neighborhood", "desc": "Near Williamsburg cafés and art spaces."},
            {"icon": "🔍", "title": "Exposed brick charm", "desc": "Industrial interior with cozy lighting."},
        ],
    },
    {
        "id": 10,
        "image": "/images/hotel10.jpg",
        "title": "Mountain View Cabin",
        "location": "Banff, Canada",
        "rating": 4.8,
        "reviews": 174,
        "guests": 4,
        "maxGuests": 4,
        "bedrooms": 2,
        "beds": 2,
        "baths": 1,
        "datesFrom": "2025-07-12",
        "datesTo": "2025-07-16",
        "price": 198,
        "host": {"name": "Sarah", "since": 6, "avatar": "https://randomuser.me/api/portraits/women/40.jpg"},
        "amenities": [
            {"icon": "💻", "title": "Loft workspace", "desc": "Views of the Rockies while working."},
            {"icon": "📍", "title": "Near National Park", "desc": "5-minute drive to Banff Park entrance."},
            {"icon": "🔍", "title": "Wood-burning stove", "desc": "Rustic warmth and mountain charm."},
        ],
    },
    {
        "id": 11,
        "image": "/images/hotel11.png",
        "title": "Casa del Sol",
        "location": "Barcelona, Spain",
        "rating": 4.6,
        "reviews": 132,
        "guests": 2,
        "maxGuests": 2,
        "bedrooms": 1,
        "beds": 1,
        "baths": 1,
        "datesFrom": "2025-03-13",
        "datesTo": "2025-07-21",
        "price": 154,
        "host": {"name": "Alejandro", "since": 3, "avatar": "https://randomuser.me/api/portraits/men/30.jpg"},
        "amenities": [
            {"icon": "💻", "title": "Dedicated workspace", "desc": "Perfect for remote work with high-speed WiFi."},
            {"icon": "📍", "title": "Near Sagrada Familia", "desc": "5-minute walk to Gaudí's masterpiece."},
            {"icon": "🔍", "title": "Balcony views", "desc": "Enjoy the sunset over the city."},
        ],
    },
    {
        "id": 12,
        "image": "/images/hotel12.png",
        "title": "Seaside Escape",
        "location": "Gold Coast, Australia",
        "rating": 4.7,
        "reviews": 98,
        "guests": 4,
        "maxGuests": 4,
        "bedrooms": 2,
        "beds": 3,
        "baths": 2,
        "datesFrom": "2025-07-12",
        "datesTo": "2025-07-16",
        "price": 199,
        "host": {"name": "Ruby", "since": 4, "avatar": "https://randomuser.me/api/portraits/women/29.jpg"},
        "amenities": [
            {"icon": "💻", "title": "Ocean-view workspace", "desc": "Desk by the window with sea breeze."},
            {"icon": "📍", "title": "Beach access", "desc": "Step right onto the sand."},
            {"icon": "🔍", "title": "Outdoor shower", "desc": "Rinse off after swimming or surfing."},
        ],
    },
    {
        "id": 13,
        "image": "/images/hotel13.jpg",
        "title": "The Heritage Flat",
        "location": "Edinburgh, UK",
        "rating": 4.4,
        "reviews": 76,
        "guests": 2,
        "maxGuests": 2,
        "bedrooms": 1,
        "beds": 1,
        "baths": 1,
        "datesFrom": "2025-05-03",
        "datesTo": "2025-07-13",
        "price": 123,
        "host": {"name": "Oliver", "since": 5, "avatar": "https://randomuser.me/api/portraits/men/11.jpg"},
        "amenities": [
            {"icon": "💻", "title": "Writer's nook", "desc": "Quiet corner for reading and journaling."},
            {"icon": "📍", "title": "Historic Old Town", "desc": "Cobblestone streets outside your door."},
            {"icon": "🔍", "title": "Fireplace", "desc": "Traditional stone hearth for cozy evenings."},
        ],
    },
    {
        "id": 14,
        "image": "/images/hotel14.png",
        "title": "Jungle Treehouse",
        "location": "Ubud, Bali",
        "rating": 4.9,
        "reviews": 214,
        "guests": 2,
        "maxGuests": 2,
        "bedrooms": 1,
        "beds": 1,
        "baths": 1,
        "datesFrom": "2025-03-13",
        "datesTo": "2025-07-16",
        "price": 182,
        "host": {"name": "Kadek", "since": 6, "avatar": "https://randomuser.me/api/portraits/men/42.jpg"},
        "amenities": [
            {"icon": "💻", "title": "Nature desk", "desc": "Surrounded by jungle sounds and WiFi."},
            {"icon": "📍", "title": "Rice terrace view", "desc": "Private balcony overlooking nature."},
            {"icon": "🔍", "title": "Outdoor bathtub", "desc": "Bathe under the stars."},
        ],
    },
    {
        "id": 15,
        "image": "/images/hotel15.jpg",
        "title": "Nordic Lakehouse",
        "location": "Oslo, Norway",
        "rating": 4.6,
        "reviews": 143,
        "guests": 4,
        "maxGuests": 4,
        "bedrooms": 2,
        "beds": 3,
        "baths": 2,
        "datesFrom": "2025-05-03",
        "datesTo": "2025-07-13",
        "price": 215,
        "host": {"name": "Ingrid", "since": 4, "avatar": "https://randomuser.me/api/portraits/women/18.jpg"},
        "amenities": [
            {"icon": "💻", "title": "Scenic workspace", "desc": "Window-side desk with lake views."},
            {"icon": "📍", "title": "Dock access", "desc": "Canoe and fish steps from the door."},
            {"icon": "🔍", "title": "Heated floors", "desc": "Stay warm in style during chilly nights."},
        ],
    },
    {
        "id": 16,
        "image": "/images/hotel16.png",
        "title": "Tuscany Farmhouse",
        "location": "Siena, Italy",
        "rating": 4.8,
        "reviews": 189,
        "guests": 6,
        "maxGuests": 6,
        "bedrooms": 3,
        "beds": 4,
        "baths": 2,
        "datesFrom": "2025-03-13",
        "datesTo": "2025-07-16",
        "price": 264,
        "host": {"name": "Giulia", "since": 7, "avatar": "https://randomuser.me/api/portraits/women/35.jpg"},
        "amenities": [
            {"icon": "💻", "title": "Rustic desk", "desc": "Set beside vineyard-facing windows."},
            {"icon": "📍", "title": "Olive groves nearby", "desc": "Stroll through peaceful farmland."},
            {"icon": "🔍", "title": "Outdoor kitchen", "desc": "Cook al fresco with a wood-fired oven."},
        ],
    },
    {
        "id": 17,
        "image": "/images/hotel17.png",
        "title": "The Ice Loft",
        "location": "Reykjavík, Iceland",
        "rating": 4.5,
        "reviews": 102,
        "guests": 2,
        "maxGuests": 2,
        "bedrooms": 1,
        "beds": 1,
        "baths": 1,
        "datesFrom": "2025-03-13",
        "datesTo": "2025-07-16",
        "price": 179,
        "host": {"name": "Einar", "since": 5, "avatar": "https://randomuser.me/api/portraits/men/10.jpg"},
        "amenities": [
            {"icon": "💻", "title": "Bright workspace", "desc": "Skylights and cozy reading lamps."},
            {"icon": "📍", "title": "Walk to harbor", "desc": "Just minutes from the waterfront."},
            {"icon": "🔍", "title": "Art-inspired decor", "desc": "Locally curated photography and sculpture."},
        ],
    },
    {
        "id": 18,
        "image": "/images/hotel18.png",
        "title": "Savannah Courtyard Suite",
        "location": "Savannah, USA",
        "rating": 4.3,
        "reviews": 67,
        "guests": 2,
        "maxGuests": 2,
        "bedrooms": 1,
        "beds": 1,
        "baths": 1,
        "datesFrom": "2025-03-13",
        "datesTo": "2025-07-13",
        "price": 149,
        "host": {"name": "Grace", "since": 3, "avatar": "https://randomuser.me/api/portraits/women/17.jpg"},
        "amenities": [
            {"icon": "💻", "title": "Indoor-outdoor desk", "desc": "Use it inside or out in the courtyard."},
            {"icon": "📍", "title": "Historic district", "desc": "Southern charm and Spanish moss."},
            {"icon": "🔍", "title": "Garden patio", "desc": "Brick walls and string lights."},
        ],
    },
    {
        "id": 19,
        "image": "/images/hotel19.jpg",
        "title": "Skyline Studio",
        "location": "Toronto, Canada",
        "rating": 4.2,
        "reviews": 88,
        "guests": 2,
        "maxGuests": 2,
        "bedrooms": 1,
        "beds": 1,
        "baths": 1,
        "datesFrom": "2025-03-13",
        "datesTo": "2025-07-13",
        "price": 158,
        "host": {"name": "Daniel", "since": 2, "avatar": "https://randomuser.me/api/portraits/men/40.jpg"},
        "amenities": [
            {"icon": "💻", "title": "High-rise desk view", "desc": "Watch the CN Tower as you work."},
            {"icon": "📍", "title": "Downtown core", "desc": "Steps from shopping and dining."},
            {"icon": "🔍", "title": "Private gym access", "desc": "Building fitness center included."},
        ],
    },
    {
        "id": 20,
        "image": "/images/hotel20.jpg",
        "title": "Countryside Stone Villa",
        "location": "Burgundy, France",
        "rating": 4.8,
        "reviews": 173,
        "guests": 5,
        "maxGuests": 5,
        "bedrooms": 3,
        "beds": 4,
        "baths": 2,
        "datesFrom": "2025-03-13",
        "datesTo": "2025-07-16",
        "price": 245,
        "host": {"name": "Henri", "since": 8, "avatar": "https://randomuser.me/api/portraits/men/8.jpg"},
        "amenities": [
            {"icon": "💻", "title": "Library workspace", "desc": "Bookshelves and antique writing desk."},
            {"icon": "📍", "title": "Vineyard tours", "desc": "Free tastings with local vintners."},
            {"icon": "🔍", "title": "Stone fireplace", "desc": "Warm evenings with rustic ambiance."},
        ],
    },
    {
        "id": 21,
        "image": "/images/hotel21.jpg",
        "title": "Mountain Escape Retreat",
        "location": "Banff, Canada",
        "rating": 4.8,
        "reviews": 142,
        "guests": 2,
        "maxGuests": 2,
        "bedrooms": 1,
        "beds": 1,
        "baths": 1,
        "datesFrom": "2025-05-03",
        "datesTo": "2025-07-13",
        "price": 179,
        "host": {"name": "Lucas", "since": 5, "avatar": "https://randomuser.me/api/portraits/men/32.jpg"},
        "amenities": [
            {"icon": "💻", "title": "Dedicated workspace", "desc": "A common area with wifi that's well-suited for working."},
            {"icon": "📍", "title": "Great location", "desc": "Walkable to downtown shops and hiking trails."},
            {"icon": "🔍", "title": "Great check-in experience", "desc": "Guests rated check-in 5 stars."},
        ],
    },
    {
        "id": 22,
        "image": "/images/hotel22.jpg",
        "title": "Seaside Villa with Private Pool",
        "location": "Santorini, Greece",
        "rating": 4.9,
        "reviews": 210,
        "guests": 4,
        "maxGuests": 4,
        "bedrooms": 2,
        "beds": 2,
        "baths": 2,
        "datesFrom": "2025-05-03",
        "datesTo": "2025-07-16",
        "price": 289,
        "host": {"name": "Maria", "since": 6, "avatar": "https://randomuser.me/api/portraits/women/12.jpg"},
        "amenities": [
            {"icon": "💻", "title": "Oceanview workspace", "desc": "Work with a view of the sea."},
            {"icon": "📍", "title": "Prime location", "desc": "Steps from the beach and nightlife."},
            {"icon": "🔍", "title": "Self check-in", "desc": "Easy access with smart lock."},
        ],
    },
    {
        "id": 23,
        "image": "/images/hotel23.jpg",
        "title": "Cozy Forest Lodge",
        "location": "Black Forest, Germany",
        "rating": 4.7,
        "reviews": 96,
        "guests": 3,
        "maxGuests": 3,
        "bedrooms": 2,
        "beds": 2,
        "baths": 1,
        "datesFrom": "2025-07-12",
        "datesTo": "2025-07-16",
        "price": 149,
        "host": {"name": "Anna", "since": 4, "avatar": "https://randomuser.me/api/portraits/women/50.jpg"},
        "amenities": [
            {"icon": "💻", "title": "Quiet workspace", "desc": "Great for reading or remote work."},
            {"icon": "📍", "title": "Nature access", "desc": "Right next to hiking and biking trails."},
            {"icon": "🔍", "title": "Smooth check-in", "desc": "Personalized welcome by host."},
        ],
    },
    {
        "id": 24,
        "image": "/images/hotel24.jpg",
        "title": "Stylish Loft in City Center",
        "location": "Barcelona, Spain",
        "rating": 4.6,
        "reviews": 180,
        "guests": 2,
        "maxGuests": 2,
        "bedrooms": 1,
        "beds": 1,
        "baths": 1,
        "datesFrom": "2025-07-12",
        "datesTo": "2025-07-16",
        "price": 199,
        "host": {"name": "Carlos", "since": 3, "avatar": "https://randomuser.me/api/portraits/men/41.jpg"},
        "amenities": [
            {"icon": "💻", "title": "City workspace", "desc": "Fast WiFi, great for working vacations."},
            {"icon": "📍", "title": "Central location", "desc": "Close to Gaudí buildings and tapas bars."},
            {"icon": "🔍", "title": "Easy check-in", "desc": "Flexible key pickup and support."},
        ],
    },
    {
        "id": 25,
        "image": "/images/hotel25.jpg",
        "title": "Lakeview Cottage Getaway",
        "location": "Lake Tahoe, USA",
        "rating": 4.5,
        "reviews": 110,
        "guests": 4,
        "maxGuests": 4,
        "bedrooms": 2,
        "beds": 3,
        "baths": 2,
        "datesFrom": "2025-05-05",
        "datesTo": "2025-07-16",
        "price": 209,
        "host": {"name": "Samantha", "since": 7, "avatar": "https://randomuser.me/api/portraits/women/70.jpg"},
        "amenities": [
            {"icon": "💻", "title": "Work-friendly spot", "desc": "Peaceful area with lakeside views."},
            {"icon": "📍", "title": "Lake access", "desc": "Just steps from swimming and kayaking."},
            {"icon": "🔍", "title": "Great host support", "desc": "24/7 availability for guests."},
        ],
    },
    {
        "id": 26,
        "image": "/images/hotel26.jpg",
        "title": "Modern Flat near Tower Bridge",
        "location": "London, UK",
        "rating": 4.8,
        "reviews": 225,
        "guests": 2,
        "maxGuests": 2,
        "bedrooms": 1,
        "beds": 1,
        "baths": 1,
        "datesFrom": "2025-05-03",
        "datesTo": "2025-07-16",
        "price": 189,
        "host": {"name": "George", "since": 6, "avatar": "https://randomuser.me/api/portraits/men/29.jpg"},
        "amenities": [
            {"icon": "💻", "title": "Business ready", "desc": "Perfect for remote workers visiting London."},
            {"icon": "📍", "title": "Near attractions", "desc": "Walk to Tower Bridge and the Shard."},
            {"icon": "🔍", "title": "Quick check-in", "desc": "Keyless entry with code."},
        ],
    },
    {
        "id": 27,
        "image": "/images/hotel27.jpg",
        "title": "Tropical Jungle Bungalow",
        "location": "Ubud, Bali",
        "rating": 4.9,
        "reviews": 310,
        "guests": 2,
        "maxGuests": 2,
        "bedrooms": 1,
        "beds": 1,
        "baths": 1,
        "datesFrom": "2025-07-12",
        "datesTo": "2025-07-16",
        "price": 149,
        "host": {"name": "Ketut", "since": 9, "avatar": "https://randomuser.me/api/portraits/men/55.jpg"},
        "amenities": [
            {"icon": "💻", "title": "Scenic workspace", "desc": "Jungle views and fast internet."},
            {"icon": "📍", "title": "Close to nature", "desc": "Nearby waterfalls and rice terraces."},
            {"icon": "🔍", "title": "Balinese hospitality", "desc": "Personal welcome and daily breakfast."},
        ],
    },
    {
        "id": 28,
        "image": "/images/hotel28.jpg",
        "title": "Historic Studio in Old Town",
        "location": "Prague, Czech Republic",
        "rating": 4.4,
        "reviews": 82,
        "guests": 2,
        "maxGuests": 2,
        "bedrooms": 1,
        "beds": 1,
        "baths": 1,
        "datesFrom": "2025-07-12",
        "datesTo": "2025-07-16",
        "price": 139,
        "host": {"name": "Petra", "since": 3, "avatar": "https://randomuser.me/api/portraits/women/64.jpg"},
        "amenities": [
            {"icon": "💻", "title": "Comfortable desk", "desc": "Perfect for light work or journaling."},
            {"icon": "📍", "title": "Walkable sights", "desc": "Charles Bridge just 5 mins away."},
            {"icon": "🔍", "title": "Flexible check-in", "desc": "Available even for late-night arrivals."},
        ],
    },
    {
        "id": 29,
        "image": "/images/hotel29.jpg",
        "title": "Rustic Farm Stay",
        "location": "Tuscany, Italy",
        "rating": 4.6,
        "reviews": 157,
        "guests": 3,
        "maxGuests": 3,
        "bedrooms": 1,
        "beds": 2,
        "baths": 1,
        "datesFrom": "2025-07-12",
        "datesTo": "2025-07-16",
        "price": 159,
        "host": {"name": "Giulia", "since": 5, "avatar": "https://randomuser.me/api/portraits/women/17.jpg"},
        "amenities": [
            {"icon": "💻", "title": "Scenic workspace", "desc": "Desk with vineyard views."},
            {"icon": "📍", "title": "Farm activities", "desc": "Pick grapes and join cooking class."},
            {"icon": "🔍", "title": "Warm welcome", "desc": "Family-run with homemade breakfast."},
        ],
    },
    {
        "id": 30,
        "image": "/images/hotel30.jpg",
        "title": "Luxury Apartment near Opera",
        "location": "Vienna, Austria",
        "rating": 5.0,
        "reviews": 98,
        "guests": 2,
        "maxGuests": 2,
        "bedrooms": 1,
        "beds": 1,
        "baths": 1,
        "datesFrom": "2025-05-03",
        "datesTo": "2025-07-16",
        "price": 219,
        "host": {"name": "Stefan", "since": 2, "avatar": "https://randomuser.me/api/portraits/men/22.jpg"},
        "amenities": [
            {"icon": "💻", "title": "Elegant workspace", "desc": "Ideal for business travelers."},
            {"icon": "📍", "title": "Cultural hotspot", "desc": "Steps from Opera House and museums."},
            {"icon": "🔍", "title": "Fast check-in", "desc": "Code-based access with instructions."},
        ],
    },
    {
        "id": 31,
        "image": "/images/hotel31.jpg",
        "title": "Boutique Haven near Eiffel Tower",
        "location": "Paris, France",
        "rating": 4.8,
        "reviews": 212,
        "guests": 2,
        "maxGuests": 2,
        "bedrooms": 1,
        "beds": 1,
        "baths": 1,
        "datesFrom": "2025-05-09",
        "datesTo": "2025-07-16",
        "price": 185,
        "host": {"name": "Camille", "since": 6, "avatar": "https://randomuser.me/api/portraits/women/65.jpg"},
        "amenities": [
            {"icon": "🛎️", "title": "24/7 Concierge", "desc": "Always available to assist you during your stay."},
            {"icon": "🍷", "title": "Rooftop Bar", "desc": "Enjoy Parisian nights with a drink and a view."},
            {"icon": "🗼", "title": "Eiffel Views", "desc": "Unobstructed views of the Eiffel Tower."},
        ],
    },
    {
        "id": 32,
        "image": "/images/hotel32.jpg",
        "title": "Lakeside Retreat with Kayaks",
        "location": "Lake Como, Italy",
        "rating": 4.7,
        "reviews": 153,
        "guests": 4,
        "maxGuests": 5,
        "bedrooms": 2,
        "beds": 3,
        "baths": 2,
        "datesFrom": "2025-07-12",
        "datesTo": "2025-07-16",
        "price": 210,
        "host": {"name": "Marco", "since": 3, "avatar": "https://randomuser.me/api/portraits/men/22.jpg"},
        "amenities": [
            {"icon": "🚣", "title": "Free Kayaks", "desc": "Explore Lake Como with complimentary kayaks."},
            {"icon": "🔥", "title": "Outdoor Fireplace", "desc": "Relax by the lake with a cozy fire."},
            {"icon": "🌄", "title": "Mountain Views", "desc": "Stunning views of the surrounding Alps."},
        ],
    },
    {
        "id": 33,
        "image": "/images/hotel33.jpg",
        "title": "Desert Escape with Pool",
        "location": "Sedona, USA",
        "rating": 4.5,
        "reviews": 188,
        "guests": 3,
        "maxGuests": 4,
        "bedrooms": 2,
        "beds": 2,
        "baths": 2,
        "datesFrom": "2025-03-09",
        "datesTo": "2025-07-16",
        "price": 175,
        "host": {"name": "Maya", "since": 4, "avatar": "https://randomuser.me/api/portraits/women/12.jpg"},
        "amenities": [
            {"icon": "🏜️", "title": "Desert Trails Nearby", "desc": "Enjoy hikes right outside your door."},
            {"icon": "🏊", "title": "Private Pool", "desc": "Cool off in your own backyard pool."},
            {"icon": "🧘", "title": "Meditation Deck", "desc": "Unwind with views of red rock formations."},
        ],
    },
    {
        "id": 34,
        "image": "/images/hotel34.jpg",
        "title": "Ski-in Chalet with Sauna",
        "location": "Zermatt, Switzerland",
        "rating": 4.9,
        "reviews": 302,
        "guests": 6,
        "maxGuests": 6,
        "bedrooms": 3,
        "beds": 4,
        "baths": 3,
        "datesFrom": "2025-07-12",
        "datesTo": "2025-07-16",
        "price": 360,
        "host": {"name": "Lukas", "since": 8, "avatar": "https://randomuser.me/api/portraits/men/50.jpg"},
        "amenities": [
            {"icon": "🎿", "title": "Ski-in/Ski-out", "desc": "Hit the slopes right from your door."},
            {"icon": "🧖", "title": "Private Sauna", "desc": "Relax your muscles after a long day skiing."},
            {"icon": "🏔️", "title": "Alpine Views", "desc": "Panoramic views of the Matterhorn."},
        ],
    },
    {
        "id": 35,
        "image": "/images/hotel35.jpg",
        "title": "Tropical Beach Bungalow",
        "location": "Phuket, Thailand",
        "rating": 4.6,
        "reviews": 179,
        "guests": 2,
        "maxGuests": 2,
        "bedrooms": 1,
        "beds": 1,
        "baths": 1,
        "datesFrom": "2025-07-12",
        "datesTo": "2025-07-16",
        "price": 145,
        "host": {"name": "Nok", "since": 2, "avatar": "https://randomuser.me/api/portraits/women/71.jpg"},
        "amenities": [
            {"icon": "🏖️", "title": "Beach Access", "desc": "Walk to the beach in under 2 minutes."},
            {"icon": "🌅", "title": "Sunset Deck", "desc": "Perfect for watching the sun dip below the horizon."},
            {"icon": "🧴", "title": "Spa Services", "desc": "Enjoy massages and wellness treatments on-site."},
        ],
    },
    {
        "id": 36,
        "image": "/images/hotel36.jpg",
        "title": "Rustic Farmhouse Getaway",
        "location": "Tuscany, Italy",
        "rating": 4.7,
        "reviews": 143,
        "guests": 5,
        "maxGuests": 5,
        "bedrooms": 3,
        "beds": 4,
        "baths": 2,
        "datesFrom": "2025-07-12",
        "datesTo": "2025-07-16",
        "price": 220,
        "host": {"name": "Gianna", "since": 5, "avatar": "https://randomuser.me/api/portraits/women/45.jpg"},
        "amenities": [
            {"icon": "🌾", "title": "Organic Garden", "desc": "Guests can pick fresh produce daily."},
            {"icon": "🍷", "title": "Local Wine Tasting", "desc": "Sample Tuscany's finest vintages on site."},
            {"icon": "🐓", "title": "Farm Animals", "desc": "Perfect for families with kids."},
        ],
    },
    {
        "id": 37,
        "image": "/images/hotel37.jpg",
        "title": "Modern Loft in Downtown",
        "location": "Toronto, Canada",
        "rating": 4.4,
        "reviews": 121,
        "guests": 2,
        "maxGuests": 2,
        "bedrooms": 1,
        "beds": 1,
        "baths": 1,
        "datesFrom": "2025-07-12",
        "datesTo": "2025-07-16",
        "price": 155,
        "host": {"name": "Dylan", "since": 4, "avatar": "https://randomuser.me/api/portraits/men/61.jpg"},
        "amenities": [
            {"icon": "🏙️", "title": "City Skyline View", "desc": "Enjoy views from the 18th floor balcony."},
            {"icon": "🚉", "title": "Near Subway", "desc": "Only 2 blocks from the nearest station."},
            {"icon": "💻", "title": "Fast Wi-Fi", "desc": "Reliable fiber internet for work and play."},
        ],
    },
    {
        "id": 38,
        "image": "/images/hotel38.jpg",
        "title": "Jungle Treehouse",
        "location": "Costa Rica",
        "rating": 4.9,
        "reviews": 87,
        "guests": 2,
        "maxGuests": 2,
        "bedrooms": 1,
        "beds": 1,
        "baths": 1,
        "datesFrom": "2025-05-09",
        "datesTo": "2025-07-16",
        "price": 160,
        "host": {"name": "Carlos", "since": 7, "avatar": "https://randomuser.me/api/portraits/men/18.jpg"},
        "amenities": [
            {"icon": "🌳", "title": "Treehouse Stay", "desc": "Live among the treetops in comfort."},
            {"icon": "🐒", "title": "Wildlife Sightings", "desc": "Monkeys and toucans are frequent visitors."},
            {"icon": "🔌", "title": "Eco Power", "desc": "100% solar-powered accommodation."},
        ],
    },
    {
        "id": 39,
        "image": "/images/hotel39.jpg",
        "title": "Colonial Charm in Old Town",
        "location": "Cartagena, Colombia",
        "rating": 4.6,
        "reviews": 110,
        "guests": 3,
        "maxGuests": 4,
        "bedrooms": 2,
        "beds": 2,
        "baths": 2,
        "datesFrom": "2025-07-12",
        "datesTo": "2025-07-16",
        "price": 165,
        "host": {"name": "Valeria", "since": 6, "avatar": "https://randomuser.me/api/portraits/women/26.jpg"},
        "amenities": [
            {"icon": "🏛️", "title": "Historic Architecture", "desc": "Stay in a 200-year-old restored gem."},
            {"icon": "🛍️", "title": "Local Market Access", "desc": "Steps away from handmade goods and fresh food."},
            {"icon": "📸", "title": "Instagram Worthy", "desc": "Every corner is picture-perfect."},
        ],
    },
    {
        "id": 40,
        "image": "/images/hotel40.jpg",
        "title": "Quiet Cottage by the Fjord",
        "location": "Bergen, Norway",
        "rating": 4.8,
        "reviews": 98,
        "guests": 2,
        "maxGuests": 2,
        "bedrooms": 1,
        "beds": 1,
        "baths": 1,
        "datesFrom": "2025-07-12",
        "datesTo": "2025-07-16",
        "price": 190,
        "host": {"name": "Astrid", "since": 5, "avatar": "https://randomuser.me/api/portraits/women/32.jpg"},
        "amenities": [
            {"icon": "🌊", "title": "Fjord Access", "desc": "Kayak or fish right outside your door."},
            {"icon": "❄️", "title": "Cozy Heating", "desc": "Warm up with underfloor heating and a fireplace."},
            {"icon": "📚", "title": "Reading Nook", "desc": "Watch the rain with a good book."},
        ],
    },
    {
        "id": 41,
        "image": "/images/hotel1.jpeg",
        "title": "Alpine Retreat Lodge",
        "location": "Zermatt, Switzerland",
        "rating": 4.9,
        "reviews": 62,
        "guests": 4,
        "maxGuests": 4,
        "bedrooms": 2,
        "beds": 3,
        "baths": 2,
        "datesFrom": "2025-07-12",
        "datesTo": "2025-07-16",
        "price": 220,
        "host": {"name": "Marta", "since": 5, "avatar": "https://randomuser.me/api/portraits/women/31.jpg"},
        "amenities": [
            {"icon": "🧺", "title": "Washer & Dryer", "desc": "In-unit washer and dryer available."},
            {"icon": "🏞️", "title": "Mountain view", "desc": "Breathtaking views from the balcony."},
            {"icon": "🔥", "title": "Indoor fireplace", "desc": "Cozy up next to the wood-burning fireplace."},
        ],
    },
    {
        "id": 42,
        "image": "/images/hotel2.jpeg",
        "title": "Beachfront Paradise Bungalow",
        "location": "Goa, India",
        "rating": 4.7,
        "reviews": 95,
        "guests": 2,
        "maxGuests": 2,
        "bedrooms": 1,
        "beds": 1,
        "baths": 1,
        "datesFrom": "2025-07-12",
        "datesTo": "2025-07-16",
        "price": 145,
        "host": {"name": "Aarav", "since": 3, "avatar": "https://randomuser.me/api/portraits/men/52.jpg"},
        "amenities": [
            {"icon": "🌊", "title": "Oceanfront", "desc": "Just steps away from the beach."},
            {"icon": "📶", "title": "Fast Wi-Fi", "desc": "Perfect for remote work and streaming."},
            {"icon": "🌴", "title": "Private garden", "desc": "Enjoy a peaceful garden all to yourself."},
        ],
    },
    {
        "id": 43,
        "image": "/images/hotel3.png",
        "title": "Old Town Stone Apartment",
        "location": "Dubrovnik, Croatia",
        "rating": 4.8,
        "reviews": 71,
        "guests": 2,
        "maxGuests": 2,
        "bedrooms": 1,
        "beds": 1,
        "baths": 1,
        "datesFrom": "2025-07-12",
        "datesTo": "2025-07-16",
        "price": 180,
        "host": {"name": "Nikola", "since": 6, "avatar": "https://randomuser.me/api/portraits/men/18.jpg"},
        "amenities": [
            {"icon": "🏰", "title": "Historic charm", "desc": "Located inside the ancient city walls."},
            {"icon": "🧭", "title": "Central location", "desc": "Walk to all the major sights."},
            {"icon": "🛏️", "title": "Memory foam mattress", "desc": "Sleep like royalty on a premium bed."},
        ],
    },
    {
        "id": 44,
        "image": "/images/hotel4.png",
        "title": "Modern Loft with Skyline View",
        "location": "Toronto, Canada",
        "rating": 4.6,
        "reviews": 83,
        "guests": 3,
        "maxGuests": 3,
        "bedrooms": 1,
        "beds": 2,
        "baths": 1,
        "datesFrom": "2025-07-12",
        "datesTo": "2025-07-16",
        "price": 165,
        "host": {"name": "Jasmine", "since": 2, "avatar": "https://randomuser.me/api/portraits/women/21.jpg"},
        "amenities": [
            {"icon": "🏙️", "title": "City skyline view", "desc": "Floor-to-ceiling windows with panoramic views."},
            {"icon": "🏋️", "title": "Gym access", "desc": "Free access to in-building fitness center."},
            {"icon": "🚗", "title": "Free parking", "desc": "Dedicated spot included."},
        ],
    },
    {
        "id": 45,
        "image": "/images/hotel5.png",
        "title": "Tropical Garden Villa",
        "location": "Ubud, Bali",
        "rating": 4.9,
        "reviews": 122,
        "guests": 2,
        "maxGuests": 2,
        "bedrooms": 1,
        "beds": 1,
        "baths": 1,
        "datesFrom": "2025-07-12",
        "datesTo": "2025-07-16",
        "price": 132,
        "host": {"name": "Ketut", "since": 7, "avatar": "https://randomuser.me/api/portraits/men/41.jpg"},
        "amenities": [
            {"icon": "🌺", "title": "Lush surroundings", "desc": "Surrounded by nature and tropical flowers."},
            {"icon": "🧘", "title": "Yoga deck", "desc": "Private open-air yoga and meditation area."},
            {"icon": "🏊", "title": "Infinity pool", "desc": "Overlooks rice paddies and jungle."},
        ],
    },
    {
        "id": 46,
        "image": "/images/hotel6.png",
        "title": "Charming Cottage by the Lake",
        "location": "Lake Bled, Slovenia",
        "rating": 4.7,
        "reviews": 58,
        "guests": 4,
        "maxGuests": 4,
        "bedrooms": 2,
        "beds": 3,
        "baths": 2,
        "datesFrom": "2025-07-12",
        "datesTo": "2025-07-16",
        "price": 174,
        "host": {"name": "Tina", "since": 4, "avatar": "https://randomuser.me/api/portraits/women/60.jpg"},
        "amenities": [
            {"icon": "🚣", "title": "Lake access", "desc": "Private dock and paddle boat included."},
            {"icon": "🔥", "title": "Outdoor firepit", "desc": "Great for cool evenings and marshmallows."},
            {"icon": "🍳", "title": "Fully equipped kitchen", "desc": "Cook your favorite meals with ease."},
        ],
    },
    {
        "id": 47,
        "image": "/images/hotel7.jpg",
        "title": "Luxury High-Rise Studio",
        "location": "Dubai, UAE",
        "rating": 4.8,
        "reviews": 110,
        "guests": 2,
        "maxGuests": 2,
        "bedrooms": 1,
        "beds": 1,
        "baths": 1,
        "datesFrom": "2025-07-12",
        "datesTo": "2025-07-16",
        "price": 210,
        "host": {"name": "Yousef", "since": 3, "avatar": "https://randomuser.me/api/portraits/men/36.jpg"},
        "amenities": [
            {"icon": "🌇", "title": "Burj Khalifa view", "desc": "Iconic skyline view right from your bed."},
            {"icon": "🛎️", "title": "Concierge service", "desc": "24/7 building concierge for your comfort."},
            {"icon": "🧼", "title": "Daily cleaning", "desc": "Included at no extra charge."},
        ],
    },
    {
        "id": 48,
        "image": "/images/hotel8.jpg",
        "title": "Rustic Barnhouse Getaway",
        "location": "Nashville, USA",
        "rating": 4.5,
        "reviews": 44,
        "guests": 5,
        "maxGuests": 5,
        "bedrooms": 3,
        "beds": 4,
        "baths": 2,
        "datesFrom": "2025-07-12",
        "datesTo": "2025-07-16",
        "price": 198,
        "host": {"name": "Brian", "since": 2, "avatar": "https://randomuser.me/api/portraits/men/15.jpg"},
        "amenities": [
            {"icon": "🐴", "title": "Countryside escape", "desc": "Perfect for those who love nature and quiet."},
            {"icon": "🎸", "title": "Music-themed interior", "desc": "Decorated by a local country artist."},
            {"icon": "🌌", "title": "Stargazing deck", "desc": "Clear skies for unforgettable nights."},
        ],
    },
    {
        "id": 49,
        "image": "/images/hotel9.jpg",
        "title": "Cosy Apartment near Eiffel Tower",
        "location": "Paris, France",
        "rating": 4.9,
        "reviews": 130,
        "guests": 2,
        "maxGuests": 2,
        "bedrooms": 1,
        "beds": 1,
        "baths": 1,
        "datesFrom": "2025-07-12",
        "datesTo": "2025-07-16",
        "price": 205,
        "host": {"name": "Claire", "since": 5, "avatar": "https://randomuser.me/api/portraits/women/45.jpg"},
        "amenities": [
            {"icon": "🗼", "title": "Eiffel Tower view", "desc": "Visible right from the window."},
            {"icon": "🥐", "title": "Bakery next door", "desc": "Start your day with a fresh croissant."},
            {"icon": "🖼️", "title": "Artful decor", "desc": "Inspired by Parisian artists."},
        ],
    },
    {
        "id": 50,
        "image": "/images/hotel10.jpg",
        "title": "Peaceful Desert Casita",
        "location": "Sedona, USA",
        "rating": 4.6,
        "reviews": 38,
        "guests": 2,
        "maxGuests": 2,
        "bedrooms": 1,
        "beds": 1,
        "baths": 1,
        "datesFrom": "2025-05-09",
        "datesTo": "2025-07-21",
        "price": 139,
        "host": {"name": "Sandra", "since": 6, "avatar": "https://randomuser.me/api/portraits/women/28.jpg"},
        "amenities": [
            {"icon": "🌵", "title": "Desert view", "desc": "Surrounded by red rock formations."},
            {"icon": "🧖", "title": "Private hot tub", "desc": "Relax under the stars."},
            {"icon": "☕", "title": "Coffee bar", "desc": "Includes a premium espresso machine."},
        ],
    },
]


def parse_datetime(value: str | None) -> datetime | None:
    if not value:
        return None
    try:
        if isinstance(value, datetime):
            return value
        return parser.isoparse(value)
    except (ValueError, TypeError):
        return None


def get_modify_data(hotels_data=None):
    if hotels_data is None:
        hotels_data = DASHBOARD_HOTELS

    modified_data = []
    for hotel in hotels_data:
        new_dict = {}
        for k, v in hotel.items():
            if isinstance(v, str):
                if k in ["datesFrom", "datesTo"]:
                    new_dict[k] = parse_datetime(v)
                else:
                    new_dict[k] = v
            elif isinstance(v, dict):
                for nk, nv in v.items():
                    new_dict[k + "_" + nk] = nv
            elif isinstance(v, list):
                if k == "amenities":
                    new_dict["amenities"] = [sv["title"] for sv in v if sv.get("title")]
            else:
                new_dict[k] = v

        modified_data.append(new_dict)
    return modified_data


HOTELS_DATA_MODIFIED = get_modify_data()

LOGICAL_OPERATORS = [EQUALS, NOT_EQUALS, GREATER_EQUAL, GREATER_THAN, LESS_EQUAL, LESS_THAN]
STRING_OPERATORS = [EQUALS, NOT_EQUALS, CONTAINS, NOT_CONTAINS]
ARRAY_OPERATORS = [CONTAINS, NOT_CONTAINS, IN_LIST, NOT_IN_LIST]

FIELD_OPERATORS_SEARCH_HOTEL_MAP = {
    "search_term": STRING_OPERATORS,
    "datesFrom": LOGICAL_OPERATORS,
    "datesTo": LOGICAL_OPERATORS,
    "adults": LOGICAL_OPERATORS,
    "children": LOGICAL_OPERATORS,
    "infants": LOGICAL_OPERATORS,
    "pets": LOGICAL_OPERATORS,
}

FIELD_OPERATORS_VIEW_HOTEL_MAP = {
    # 'id': LOGICAL_OPERATORS,
    "title": STRING_OPERATORS,
    "location": STRING_OPERATORS,
    "rating": LOGICAL_OPERATORS,
    "price": LOGICAL_OPERATORS,
    "reviews": LOGICAL_OPERATORS,
    "datesFrom": LOGICAL_OPERATORS,
    "datesTo": LOGICAL_OPERATORS,
    "guests": LOGICAL_OPERATORS,
    "host_name": STRING_OPERATORS,
    # "host_since": LOGICAL_OPERATORS,
    # 'host_avatar': STRING_OPERATORS,
    "amenities": ARRAY_OPERATORS,
}

FIELD_OPERATORS_GUESTS_CHANGE_MAP = {"from_guests": [EQUALS, GREATER_EQUAL, GREATER_THAN], "to_guests": [EQUALS, LESS_EQUAL, LESS_THAN]}

FIELD_OPERATORS_INCREASE_GUESTS_MAP = {
    # "from_guests": [EQUALS, GREATER_EQUAL, GREATER_THAN],
    "to_guests": [EQUALS, LESS_EQUAL, LESS_THAN],
    **FIELD_OPERATORS_VIEW_HOTEL_MAP,
}

FIELD_OPERATORS_DECREASE_GUESTS_MAP = {"from_guests": LOGICAL_OPERATORS, "to_guests": LOGICAL_OPERATORS}

FIELD_OPERATORS_RESERVE_HOTEL_MAP = {
    **FIELD_OPERATORS_VIEW_HOTEL_MAP,
    "guests_set": LOGICAL_OPERATORS,
}
FIELD_OPERATORS_EDIT_CHECKIN_OUT_MAP = {
    "checkin": LOGICAL_OPERATORS,
    "checkout": LOGICAL_OPERATORS,
    "source": STRING_OPERATORS,
}
FIELD_OPERATORS_CONFIRM_AND_PAY_MAP = {
    "checkin": LOGICAL_OPERATORS,  # datetime
    "checkout": LOGICAL_OPERATORS,  # datetime
    "guests": LOGICAL_OPERATORS,  # int
    "listingTitle": STRING_OPERATORS,  # str
    "pricePerNight": LOGICAL_OPERATORS,  # int
    "nights": LOGICAL_OPERATORS,  # int
    "priceSubtotal": LOGICAL_OPERATORS,  # int
    # "cleaningFee": LOGICAL_OPERATORS,  # int
    # "serviceFee": LOGICAL_OPERATORS,  # int
    "total": LOGICAL_OPERATORS,  # int
    # "paymentMethod": STRING_OPERATORS,  # str
    # "source": STRING_OPERATORS,  # str,
    "card_number": [EQUALS, NOT_EQUALS],
    "expiration": [EQUALS, NOT_EQUALS],
    "cvv": [EQUALS, NOT_EQUALS],
    "zipcode": [EQUALS, NOT_EQUALS],
    "country": [EQUALS, NOT_EQUALS],
}

FIELD_OPERATORS_MESSAGE_HOST_MAP = {
    **FIELD_OPERATORS_VIEW_HOTEL_MAP,
    "message": STRING_OPERATORS,
    "host_name": STRING_OPERATORS,
    # "source": STRING_OPERATORS,
}

FIELD_OPERATORS_SHARE_HOTEL_MAP = {**FIELD_OPERATORS_VIEW_HOTEL_MAP, "email": STRING_OPERATORS}

FIELD_OPERATORS_BACK_TO_ALL_HOTELS_MAP = {**FIELD_OPERATORS_VIEW_HOTEL_MAP}
