from datetime import datetime

from dateutil import parser

from ..operators import CONTAINS, EQUALS, GREATER_EQUAL, GREATER_THAN, IN_LIST, LESS_EQUAL, LESS_THAN, NOT_CONTAINS, NOT_EQUALS, NOT_IN_LIST

REGION_HOTELS = [
    {
        "image": "/images/hotel1.jpg",
        "title": "Cabin in the woods",
        "location": "Asheville, USA",
        "rating": 4.0,
        "reviews": 7,
        "guests": 2,
        "bedrooms": 1,
        "beds": 1,
        "baths": 1,
        "datesFrom": "2025-07-12",
        "datesTo": "2025-07-16",
        "price": 127,
        "host": {"name": "Natalie", "since": 4, "avatar": "https://randomuser.me/api/portraits/women/44.jpg"},
        "amenities": [
            {"icon": "💻", "title": "Dedicated workspace", "desc": "A common area with wifi that's well-suited for working."},
            {"icon": "📍", "title": "Great location", "desc": "100% of recent guests gave the location a 5-star rating."},
            {"icon": "🔍", "title": "Great check-in experience", "desc": "100% of recent guests gave the check-in process a 5-star rating."},
        ],
    },
    {
        "image": "/images/hotel2.jpg",
        "title": "Lake House Retreat",
        "location": "Kelowna, Canada",
        "rating": 4.3,
        "reviews": 12,
        "guests": 6,
        "bedrooms": 3,
        "beds": 4,
        "baths": 2,
        "datesFrom": "2025-07-18",
        "datesTo": "2025-07-24",
        "price": 571,
        "host": {"name": "Alex", "since": 2, "avatar": "https://randomuser.me/api/portraits/men/11.jpg"},
        "amenities": [
            {"icon": "🏝", "title": "Lake view", "desc": "Enjoy beautiful sunrises on the water."},
            {"icon": "🌬", "title": "Mountain views", "desc": "Views of the Rockies from the balcony."},
            {"icon": "🛌", "title": "Family friendly", "desc": "Cribs, highchair, and backyard play area."},
        ],
    },
    {
        "image": "/images/hotel3.jpg",
        "title": "Mountain Escape",
        "location": "Zermatt, Switzerland",
        "rating": 4.34,
        "reviews": 29,
        "guests": 4,
        "bedrooms": 2,
        "beds": 3,
        "baths": 2,
        "datesFrom": "2025-07-28",
        "datesTo": "2025-08-10",
        "price": 960,
        "host": {"name": "Sofia", "since": 6, "avatar": "https://randomuser.me/api/portraits/women/40.jpg"},
        "amenities": [
            {"icon": "🥳", "title": "Hot tub", "desc": "Relax after your alpine adventure."},
            {"icon": "🍽", "title": "Gourmet kitchen", "desc": "Fully equipped for family meals."},
            {"icon": "🏖", "title": "Resort access", "desc": "Free shuttle to ski slopes."},
        ],
    },
    {
        "image": "/images/hotel4.jpg",
        "title": "Parisian Getaway",
        "location": "Paris, France",
        "rating": 4.33,
        "reviews": 15,
        "guests": 2,
        "bedrooms": 1,
        "beds": 1,
        "baths": 1,
        "datesFrom": "2025-08-15",
        "datesTo": "2025-08-22",
        "price": 268,
        "host": {"name": "Juliette", "since": 8, "avatar": "https://randomuser.me/api/portraits/women/28.jpg"},
        "amenities": [{"icon": "📚", "title": "Library", "desc": "Curated collection of Parisian literature."}, {"icon": "🎠", "title": "Central location", "desc": "Steps from the Metro."}],
    },
    {
        "image": "/images/hotel5.jpg",
        "title": "Cozy Beach House",
        "location": "Byron Bay, Australia",
        "rating": 4.31,
        "reviews": 9,
        "guests": 8,
        "bedrooms": 4,
        "beds": 6,
        "baths": 2,
        "datesFrom": "2025-07-20",
        "datesTo": "2025-07-30",
        "price": 969,
        "host": {"name": "Ella", "since": 3, "avatar": "https://randomuser.me/api/portraits/women/31.jpg"},
        "amenities": [
            {"icon": "🏖", "title": "Beach access", "desc": "Walk to sand in 3 minutes."},
            {"icon": "🌊", "title": "Private pool", "desc": "Heated and fenced."},
            {"icon": "🛸", "title": "Bikes included", "desc": "Surf the coast!"},
        ],
    },
    {
        "image": "/images/hotel6.jpg",
        "title": "Countryside Retreat",
        "location": "Cotswolds, UK",
        "rating": 4.43,
        "reviews": 10,
        "guests": 4,
        "bedrooms": 2,
        "beds": 3,
        "baths": 2,
        "datesFrom": "2025-09-01",
        "datesTo": "2025-09-07",
        "price": 211,
        "host": {"name": "Oliver", "since": 5, "avatar": "https://randomuser.me/api/portraits/men/37.jpg"},
        "amenities": [{"icon": "🍃", "title": "Garden", "desc": "Outdoor seating and flower beds."}, {"icon": "⛰", "title": "Country views", "desc": "See sheep and rolling hills."}],
    },
    {
        "image": "/images/hotel7.jpg",
        "title": "Garden Oasis",
        "location": "Amsterdam, Netherlands",
        "rating": 4.32,
        "reviews": 11,
        "guests": 3,
        "bedrooms": 1,
        "beds": 1,
        "baths": 1,
        "datesFrom": "2025-07-15",
        "datesTo": "2025-07-19",
        "price": 537,
        "host": {"name": "Mia", "since": 2, "avatar": "https://randomuser.me/api/portraits/women/45.jpg"},
        "amenities": [{"icon": "🌿", "title": "Private garden", "desc": "Secluded space for relaxation."}, {"icon": "🏰", "title": "Historic building", "desc": "18th-century canal house."}],
    },
    {
        "image": "/images/hotel8.jpg",
        "title": "Modern City Apartment",
        "location": "New York, USA",
        "rating": 4.27,
        "reviews": 25,
        "guests": 2,
        "bedrooms": 1,
        "beds": 1,
        "baths": 1,
        "datesFrom": "2025-07-25",
        "datesTo": "2025-07-28",
        "price": 258,
        "host": {"name": "Harper", "since": 7, "avatar": "https://randomuser.me/api/portraits/men/47.jpg"},
        "amenities": [{"image": "💻", "title": "Fast Wi-Fi", "desc": "1Gbps optic fiber."}, {"icon": "🧰", "title": "Washer/dryer", "desc": "Laundry in unit."}],
    },
    {
        "image": "/images/hotel9.jpg",
        "title": "Seaside Villa",
        "location": "Mykonos, Greece",
        "rating": 4.72,
        "reviews": 21,
        "guests": 6,
        "bedrooms": 3,
        "beds": 4,
        "baths": 2,
        "datesFrom": "2025-08-05",
        "datesTo": "2025-08-12",
        "price": 685,
        "host": {"name": "Niko", "since": 5, "avatar": "https://randomuser.me/api/portraits/men/32.jpg"},
        "amenities": [
            {"icon": "🏖", "title": "Beachfront", "desc": "Step outside to the Aegean Sea."},
            {"icon": "🛋", "title": "Infinity pool", "desc": "Swim with an endless horizon."},
            {"icon": "🎡", "title": "Nightlife nearby", "desc": "Close to beach bars and clubs."},
        ],
    },
    {
        "image": "/images/hotel10.jpg",
        "title": "Tokyo Highrise",
        "location": "Tokyo, Japan",
        "rating": 4.58,
        "reviews": 33,
        "guests": 2,
        "bedrooms": 1,
        "beds": 1,
        "baths": 1,
        "datesFrom": "2025-09-01",
        "datesTo": "2025-09-06",
        "price": 312,
        "host": {"name": "Hana", "since": 3, "avatar": "https://randomuser.me/api/portraits/women/52.jpg"},
        "amenities": [
            {"icon": "📱", "title": "High-speed Wi-Fi", "desc": "1Gbps fiber for work or play."},
            {"icon": "📺", "title": "Smart TV", "desc": "Includes Netflix & Prime."},
            {"icon": "🖥", "title": "City view", "desc": "Panoramic skyline at night."},
        ],
    },
    {
        "image": "/images/hotel11.jpg",
        "title": "Moroccan Riad",
        "location": "Marrakech, Morocco",
        "rating": 4.81,
        "reviews": 18,
        "guests": 4,
        "bedrooms": 2,
        "beds": 2,
        "baths": 2,
        "datesFrom": "2025-10-10",
        "datesTo": "2025-10-18",
        "price": 432,
        "host": {"name": "Zahra", "since": 6, "avatar": "https://randomuser.me/api/portraits/women/36.jpg"},
        "amenities": [
            {"icon": "🌿", "title": "Private courtyard", "desc": "Relax in traditional decor."},
            {"icon": "🍯", "title": "Mint tea service", "desc": "Daily Moroccan mint tea."},
            {"icon": "🏨", "title": "Local art", "desc": "Handcrafted tile and textiles."},
        ],
    },
    {
        "image": "/images/hotel12.jpg",
        "title": "Nordic Glass Cabin",
        "location": "Lapland, Finland",
        "rating": 4.76,
        "reviews": 16,
        "guests": 2,
        "bedrooms": 1,
        "beds": 1,
        "baths": 1,
        "datesFrom": "2025-12-20",
        "datesTo": "2025-12-27",
        "price": 490,
        "host": {"name": "Erik", "since": 4, "avatar": "https://randomuser.me/api/portraits/men/19.jpg"},
        "amenities": [
            {"icon": "❄", "title": "Aurora views", "desc": "Glass roof for watching the Northern Lights."},
            {"icon": "🧴", "title": "Sauna included", "desc": "Private Finnish sauna with wood stove."},
            {"icon": "🌿", "title": "Eco-heated", "desc": "Geothermal underfloor heating system."},
        ],
    },
]

DASHBOARD_HOTELS = [
    {
        "image": "/images/hotel1.jpg",
        "title": "Cabin in the woods",
        "location": "Asheville",
        "rating": 4.0,
        "dates": "Jul 12 - Jul 16",
        "datesFrom": "2025-07-12",
        "datesTo": "2025-07-16",
        "price": "$127.00 USD",
        "maxGuests": 2,
        "id": 1,
    },
    {
        "image": "/images/hotel2.jpg",
        "title": "Desert Mirage",
        "location": "Dubai",
        "rating": 4.65,
        "dates": "Jan 10 - Jan 15",
        "datesFrom": "2026-01-10",
        "datesTo": "2026-01-15",
        "price": "$800.00 USD",
        "maxGuests": 4,
        "id": 2,
    },
    {
        "image": "/images/hotel3.jpg",
        "title": "Lake House Retreat",
        "location": "Kelowna",
        "rating": 4.3,
        "dates": "Jul 18 - Jul 24",
        "datesFrom": "2025-07-18",
        "datesTo": "2025-07-24",
        "price": "$571.00 USD",
        "maxGuests": 6,
        "id": 3,
    },
    {
        "image": "/images/hotel4.jpg",
        "title": "Mountain Escape",
        "location": "Zermatt",
        "rating": 4.34,
        "dates": "Jul 28 - Aug 10",
        "datesFrom": "2025-07-28",
        "datesTo": "2025-08-10",
        "price": "$960.00 USD",
        "maxGuests": 4,
        "id": 4,
    },
    {
        "image": "/images/hotel5.jpg",
        "title": "Parisian Getaway",
        "location": "Paris",
        "rating": 4.33,
        "dates": "Aug 15 - Aug 22",
        "datesFrom": "2025-08-15",
        "datesTo": "2025-08-22",
        "price": "$268.00 USD",
        "maxGuests": 2,
        "id": 5,
    },
    {
        "image": "/images/hotel6.jpg",
        "title": "Cozy Beach House",
        "location": "Byron Bay",
        "rating": 4.31,
        "dates": "Jul 20 - Jul 30",
        "datesFrom": "2025-07-20",
        "datesTo": "2025-07-30",
        "price": "$969.00 USD",
        "maxGuests": 8,
        "id": 6,
    },
    {
        "image": "/images/hotel7.jpg",
        "title": "Countryside Retreat",
        "location": "Cotswolds",
        "rating": 4.43,
        "dates": "Sep 1 - Sep 7",
        "datesFrom": "2025-09-01",
        "datesTo": "2025-09-07",
        "price": "$211.00 USD",
        "maxGuests": 4,
        "id": 7,
    },
    {
        "image": "/images/hotel8.jpg",
        "title": "Garden Oasis",
        "location": "Amsterdam",
        "rating": 4.32,
        "dates": "Jul 15 - Jul 19",
        "datesFrom": "2025-07-15",
        "datesTo": "2025-07-19",
        "price": "$537.00 USD",
        "maxGuests": 3,
        "id": 8,
    },
    {
        "image": "/images/hotel9.png",
        "title": "Modern City Apartment",
        "location": "New York",
        "rating": 4.27,
        "dates": "Jul 25 - Jul 28",
        "datesFrom": "2025-07-25",
        "datesTo": "2025-07-28",
        "price": "$258.00 USD",
        "maxGuests": 2,
        "id": 9,
    },
    {
        "image": "/images/hotel10.png",
        "title": "Seaside Villa",
        "location": "Mykonos",
        "rating": 4.72,
        "dates": "Aug 5 - Aug 12",
        "datesFrom": "2025-08-05",
        "datesTo": "2025-08-12",
        "price": "$685.00 USD",
        "maxGuests": 6,
        "id": 10,
    },
    {
        "image": "/images/hotel11.png",
        "title": "Tokyo Highrise",
        "location": "Tokyo",
        "rating": 4.58,
        "dates": "Sep 1 - Sep 6",
        "datesFrom": "2025-09-01",
        "datesTo": "2025-09-06",
        "price": "$312.00 USD",
        "maxGuests": 2,
        "id": 11,
    },
    {
        "image": "/images/hotel12.png",
        "title": "Moroccan Riad",
        "location": "Marrakech",
        "rating": 4.81,
        "dates": "Oct 10 - Oct 18",
        "datesFrom": "2025-10-10",
        "datesTo": "2025-10-18",
        "price": "$432.00 USD",
        "maxGuests": 4,
        "id": 12,
    },
    {
        "image": "/images/hotel13.png",
        "title": "Rainforest Retreat",
        "location": "Amazon",
        "rating": 4.55,
        "dates": "Feb 5 - Feb 12",
        "datesFrom": "2026-02-05",
        "datesTo": "2026-02-12",
        "price": "$600.00 USD",
        "maxGuests": 6,
        "id": 13,
    },
    {
        "image": "/images/hotel14.png",
        "title": "Urban Loft",
        "location": "Berlin",
        "rating": 4.4,
        "dates": "Mar 1 - Mar 7",
        "datesFrom": "2026-03-01",
        "datesTo": "2026-03-07",
        "price": "$350.00 USD",
        "maxGuests": 2,
        "id": 14,
    },
    {
        "image": "/images/hotel15.png",
        "title": "Island Paradise",
        "location": "Bali",
        "rating": 4.9,
        "dates": "Apr 10 - Apr 17",
        "datesFrom": "2026-04-10",
        "datesTo": "2026-04-17",
        "price": "$1200.00 USD",
        "maxGuests": 8,
        "id": 15,
    },
    {
        "image": "/images/hotel16.png",
        "title": "Ski Chalet",
        "location": "Aspen",
        "rating": 4.85,
        "dates": "Dec 1 - Dec 8",
        "datesFrom": "2025-12-01",
        "datesTo": "2025-12-08",
        "price": "$950.00 USD",
        "maxGuests": 5,
        "id": 16,
    },
    {
        "image": "/images/hotel17.png",
        "title": "City Penthouse",
        "location": "London",
        "rating": 4.78,
        "dates": "May 10 - May 15",
        "datesFrom": "2026-05-10",
        "datesTo": "2026-05-15",
        "price": "$1100.00 USD",
        "maxGuests": 4,
        "id": 17,
    },
    {
        "image": "/images/hotel18.png",
        "title": "Wine Country Villa",
        "location": "Napa Valley",
        "rating": 4.82,
        "dates": "Jun 1 - Jun 7",
        "datesFrom": "2026-06-01",
        "datesTo": "2026-06-07",
        "price": "$1300.00 USD",
        "maxGuests": 6,
        "id": 18,
    },
    {
        "image": "/images/hotel19.png",
        "title": "Historic Castle",
        "location": "Edinburgh",
        "rating": 4.95,
        "dates": "Jul 1 - Jul 8",
        "datesFrom": "2026-07-01",
        "datesTo": "2026-07-08",
        "price": "$2000.00 USD",
        "maxGuests": 10,
        "id": 19,
    },
    {
        "image": "/images/hotel20.png",
        "title": "Beachfront Bungalow",
        "location": "Maldives",
        "rating": 4.99,
        "dates": "Aug 10 - Aug 17",
        "datesFrom": "2026-08-10",
        "datesTo": "2026-08-17",
        "price": "$2500.00 USD",
        "maxGuests": 4,
        "id": 20,
    },
    {
        "image": "/images/hotel21.jpg",
        "title": "Jungle Treehouse",
        "location": "Costa Rica",
        "rating": 4.7,
        "dates": "Sep 5 - Sep 12",
        "datesFrom": "2026-09-05",
        "datesTo": "2026-09-12",
        "price": "$700.00 USD",
        "maxGuests": 3,
        "id": 21,
    },
    {
        "image": "/images/hotel22.jpg",
        "title": "Mountain Lodge",
        "location": "Banff",
        "rating": 4.88,
        "dates": "Oct 1 - Oct 8",
        "datesFrom": "2026-10-01",
        "datesTo": "2026-10-08",
        "price": "$900.00 USD",
        "maxGuests": 5,
        "id": 22,
    },
    {
        "image": "/images/hotel23.jpg",
        "title": "City Studio",
        "location": "San Francisco",
        "rating": 4.25,
        "dates": "Nov 10 - Nov 15",
        "datesFrom": "2026-11-10",
        "datesTo": "2026-11-15",
        "price": "$400.00 USD",
        "maxGuests": 2,
        "id": 23,
    },
    {
        "image": "/images/hotel24.jpg",
        "title": "Country Farmhouse",
        "location": "Tuscany",
        "rating": 4.8,
        "dates": "Dec 5 - Dec 12",
        "datesFrom": "2026-12-05",
        "datesTo": "2026-12-12",
        "price": "$850.00 USD",
        "maxGuests": 7,
        "id": 24,
    },
    {
        "image": "/images/hotel25.jpg",
        "title": "Lakefront Cabin",
        "location": "Minnesota",
        "rating": 4.6,
        "dates": "Jan 15 - Jan 22",
        "datesFrom": "2027-01-15",
        "datesTo": "2027-01-22",
        "price": "$500.00 USD",
        "maxGuests": 5,
        "id": 25,
    },
    {
        "image": "/images/hotel26.jpg",
        "title": "Desert Adobe",
        "location": "Santa Fe",
        "rating": 4.5,
        "dates": "Feb 10 - Feb 17",
        "datesFrom": "2027-02-10",
        "datesTo": "2027-02-17",
        "price": "$600.00 USD",
        "maxGuests": 4,
        "id": 26,
    },
    {
        "image": "/images/hotel27.jpg",
        "title": "Cliffside Villa",
        "location": "Santorini",
        "rating": 4.92,
        "dates": "Mar 5 - Mar 12",
        "datesFrom": "2027-03-05",
        "datesTo": "2027-03-12",
        "price": "$1800.00 USD",
        "maxGuests": 6,
        "id": 27,
    },
    {
        "image": "/images/hotel28.jpg",
        "title": "Forest Hideaway",
        "location": "Oregon",
        "rating": 4.45,
        "dates": "Apr 1 - Apr 8",
        "datesFrom": "2027-04-01",
        "datesTo": "2027-04-08",
        "price": "$450.00 USD",
        "maxGuests": 4,
        "id": 28,
    },
    {
        "image": "/images/hotel29.jpg",
        "title": "Luxury Condo",
        "location": "Miami",
        "rating": 4.75,
        "dates": "May 10 - May 17",
        "datesFrom": "2027-05-10",
        "datesTo": "2027-05-17",
        "price": "$1200.00 USD",
        "maxGuests": 4,
        "id": 29,
    },
    {
        "image": "/images/hotel30.jpg",
        "title": "Riverfront Cottage",
        "location": "Savannah",
        "rating": 4.55,
        "dates": "Jun 1 - Jun 8",
        "datesFrom": "2027-06-01",
        "datesTo": "2027-06-08",
        "price": "$700.00 USD",
        "maxGuests": 3,
        "id": 30,
    },
    {
        "image": "/images/hotel31.jpg",
        "title": "Historic Loft",
        "location": "Prague",
        "rating": 4.65,
        "dates": "Jul 5 - Jul 12",
        "datesFrom": "2027-07-05",
        "datesTo": "2027-07-12",
        "price": "$800.00 USD",
        "maxGuests": 2,
        "id": 31,
    },
    {
        "image": "/images/hotel32.jpg",
        "title": "Alpine Chalet",
        "location": "Innsbruck",
        "rating": 4.85,
        "dates": "Aug 10 - Aug 17",
        "datesFrom": "2027-08-10",
        "datesTo": "2027-08-17",
        "price": "$950.00 USD",
        "maxGuests": 5,
        "id": 32,
    },
    {
        "image": "/images/hotel33.jpg",
        "title": "Seaside Cottage",
        "location": "Cornwall",
        "rating": 4.7,
        "dates": "Sep 1 - Sep 8",
        "datesFrom": "2027-09-01",
        "datesTo": "2027-09-08",
        "price": "$600.00 USD",
        "maxGuests": 4,
        "id": 33,
    },
    {
        "image": "/images/hotel34.jpg",
        "title": "City Center Flat",
        "location": "Barcelona",
        "rating": 4.6,
        "dates": "Oct 10 - Oct 17",
        "datesFrom": "2027-10-10",
        "datesTo": "2027-10-17",
        "price": "$700.00 USD",
        "maxGuests": 3,
        "id": 34,
    },
    {
        "image": "/images/hotel35.jpg",
        "title": "Country Estate",
        "location": "Bordeaux",
        "rating": 4.95,
        "dates": "Nov 5 - Nov 12",
        "datesFrom": "2027-11-05",
        "datesTo": "2027-11-12",
        "price": "$1500.00 USD",
        "maxGuests": 8,
        "id": 35,
    },
    {
        "image": "/images/hotel36.jpg",
        "title": "Harbor View Suite",
        "location": "Sydney",
        "rating": 4.8,
        "dates": "Dec 1 - Dec 8",
        "datesFrom": "2027-12-01",
        "datesTo": "2027-12-08",
        "price": "$1100.00 USD",
        "maxGuests": 4,
        "id": 36,
    },
    {
        "image": "/images/hotel37.jpg",
        "title": "Mountain Cabin",
        "location": "Rockies",
        "rating": 4.7,
        "dates": "Jan 10 - Jan 17",
        "datesFrom": "2028-01-10",
        "datesTo": "2028-01-17",
        "price": "$900.00 USD",
        "maxGuests": 6,
        "id": 37,
    },
    {
        "image": "/images/hotel38.jpg",
        "title": "Desert Villa",
        "location": "Phoenix",
        "rating": 4.55,
        "dates": "Feb 5 - Feb 12",
        "datesFrom": "2028-02-05",
        "datesTo": "2028-02-12",
        "price": "$650.00 USD",
        "maxGuests": 5,
        "id": 38,
    },
    {
        "image": "/images/hotel39.jpg",
        "title": "Island Bungalow",
        "location": "Fiji",
        "rating": 4.95,
        "dates": "Mar 1 - Mar 8",
        "datesFrom": "2028-03-01",
        "datesTo": "2028-03-08",
        "price": "$2200.00 USD",
        "maxGuests": 4,
        "id": 39,
    },
    {
        "image": "/images/hotel40.jpg",
        "title": "Urban Studio",
        "location": "Tokyo",
        "rating": 4.5,
        "dates": "Apr 10 - Apr 17",
        "datesFrom": "2028-04-10",
        "datesTo": "2028-04-17",
        "price": "$500.00 USD",
        "maxGuests": 2,
        "id": 40,
    },
    # // Repeat images for 41-50
    {
        "image": "/images/hotel1.jpg",
        "title": "Lakeview Apartment",
        "location": "Zurich",
        "rating": 4.8,
        "dates": "May 5 - May 12",
        "datesFrom": "2028-05-05",
        "datesTo": "2028-05-12",
        "price": "$900.00 USD",
        "maxGuests": 3,
        "id": 41,
    },
    {
        "image": "/images/hotel2.jpg",
        "title": "Forest Lodge",
        "location": "Black Forest",
        "rating": 4.65,
        "dates": "Jun 1 - Jun 8",
        "datesFrom": "2028-06-01",
        "datesTo": "2028-06-08",
        "price": "$750.00 USD",
        "maxGuests": 5,
        "id": 42,
    },
    {
        "image": "/images/hotel3.jpg",
        "title": "Beach House",
        "location": "Gold Coast",
        "rating": 4.9,
        "dates": "Jul 10 - Jul 17",
        "datesFrom": "2028-07-10",
        "datesTo": "2028-07-17",
        "price": "$1300.00 USD",
        "maxGuests": 6,
        "id": 43,
    },
    {
        "image": "/images/hotel4.jpg",
        "title": "City Penthouse",
        "location": "Chicago",
        "rating": 4.75,
        "dates": "Aug 1 - Aug 8",
        "datesFrom": "2028-08-01",
        "datesTo": "2028-08-08",
        "price": "$1400.00 USD",
        "maxGuests": 4,
        "id": 44,
    },
    {
        "image": "/images/hotel5.jpg",
        "title": "Country Cottage",
        "location": "Devon",
        "rating": 4.6,
        "dates": "Sep 5 - Sep 12",
        "datesFrom": "2028-09-05",
        "datesTo": "2028-09-12",
        "price": "$600.00 USD",
        "maxGuests": 3,
        "id": 45,
    },
    {
        "image": "/images/hotel6.jpg",
        "title": "Harbor Apartment",
        "location": "Vancouver",
        "rating": 4.85,
        "dates": "Oct 10 - Oct 17",
        "datesFrom": "2028-10-10",
        "datesTo": "2028-10-17",
        "price": "$950.00 USD",
        "maxGuests": 4,
        "id": 46,
    },
    {
        "image": "/images/hotel7.jpg",
        "title": "Mountain Retreat",
        "location": "Chamonix",
        "rating": 4.95,
        "dates": "Nov 1 - Nov 8",
        "datesFrom": "2028-11-01",
        "datesTo": "2028-11-08",
        "price": "$1200.00 USD",
        "maxGuests": 5,
        "id": 47,
    },
    {
        "image": "/images/hotel8.jpg",
        "title": "Safari Lodge",
        "location": "Serengeti",
        "rating": 4.99,
        "dates": "Dec 1 - Dec 8",
        "datesFrom": "2028-12-01",
        "datesTo": "2028-12-08",
        "price": "$2000.00 USD",
        "maxGuests": 10,
        "id": 48,
    },
    {
        "image": "/images/hotel9.png",
        "title": "Harbor View",
        "location": "Lisbon",
        "rating": 4.7,
        "dates": "Jan 5 - Jan 12",
        "datesFrom": "2029-01-05",
        "datesTo": "2029-01-12",
        "price": "$800.00 USD",
        "maxGuests": 4,
        "id": 49,
    },
    {
        "image": "/images/hotel10.png",
        "title": "City Escape",
        "location": "Vienna",
        "rating": 4.8,
        "dates": "Feb 10 - Feb 17",
        "datesFrom": "2029-02-10",
        "datesTo": "2029-02-17",
        "price": "$900.00 USD",
        "maxGuests": 3,
        "id": 50,
    },
]

FEATURED_HOTELS = [
    {
        "image": "/images/hotel1.jpg",
        "title": "Cabin in the woods",
        "location": "Asheville, USA",
        "rating": 4.0,
        "reviews": 7,
        "guests": 2,
        "bedrooms": 1,
        "beds": 1,
        "baths": 1,
        "datesFrom": "2025-07-12",
        "datesTo": "2025-07-16",
        "price": 127,
        "host": {"name": "Natalie", "since": 4, "avatar": "https://randomuser.me/api/portraits/women/44.jpg"},
        "amenities": [
            {"icon": "💻", "title": "Dedicated workspace", "desc": "A common area with wifi that's well-suited for working."},
            {"icon": "📍", "title": "Great location", "desc": "100% of recent guests gave the location a 5-star rating."},
            {"icon": "🔍", "title": "Great check-in experience", "desc": "100% of recent guests gave the check-in process a 5-star rating."},
        ],
    },
    {
        "image": "/images/hotel2.jpg",
        "title": "Lake House Retreat",
        "location": "Kelowna, Canada",
        "rating": 4.3,
        "reviews": 12,
        "guests": 6,
        "bedrooms": 3,
        "beds": 4,
        "baths": 2,
        "datesFrom": "2025-07-18",
        "datesTo": "2025-07-24",
        "price": 571,
        "host": {"name": "Alex", "since": 2, "avatar": "https://randomuser.me/api/portraits/men/11.jpg"},
        "amenities": [
            {"icon": "🏝", "title": "Lake view", "desc": "Enjoy beautiful sunrises on the water."},
            {"icon": "🌬", "title": "Mountain views", "desc": "Views of the Rockies from the balcony."},
            {"icon": "🛌", "title": "Family friendly", "desc": "Cribs, highchair, and backyard play area."},
        ],
    },
    {
        "image": "/images/hotel3.jpg",
        "title": "Mountain Escape",
        "location": "Zermatt, Switzerland",
        "rating": 4.34,
        "reviews": 29,
        "guests": 4,
        "bedrooms": 2,
        "beds": 3,
        "baths": 2,
        "datesFrom": "2025-07-28",
        "datesTo": "2025-08-10",
        "price": 960,
        "host": {"name": "Sofia", "since": 6, "avatar": "https://randomuser.me/api/portraits/women/40.jpg"},
        "amenities": [
            {"icon": "🥳", "title": "Hot tub", "desc": "Relax after your alpine adventure."},
            {"icon": "🍽", "title": "Gourmet kitchen", "desc": "Fully equipped for family meals."},
            {"icon": "🏖", "title": "Resort access", "desc": "Free shuttle to ski slopes."},
        ],
    },
    {
        "image": "/images/hotel4.jpg",
        "title": "Parisian Getaway",
        "location": "Paris, France",
        "rating": 4.33,
        "reviews": 15,
        "guests": 2,
        "bedrooms": 1,
        "beds": 1,
        "baths": 1,
        "datesFrom": "2025-08-15",
        "datesTo": "2025-08-22",
        "price": 268,
        "host": {"name": "Juliette", "since": 8, "avatar": "https://randomuser.me/api/portraits/women/28.jpg"},
        "amenities": [{"icon": "📚", "title": "Library", "desc": "Curated collection of Parisian literature."}, {"icon": "🎠", "title": "Central location", "desc": "Steps from the Metro."}],
    },
    {
        "image": "/images/hotel5.jpg",
        "title": "Cozy Beach House",
        "location": "Byron Bay, Australia",
        "rating": 4.31,
        "reviews": 9,
        "guests": 8,
        "bedrooms": 4,
        "beds": 6,
        "baths": 2,
        "datesFrom": "2025-07-20",
        "datesTo": "2025-07-30",
        "price": 969,
        "host": {"name": "Ella", "since": 3, "avatar": "https://randomuser.me/api/portraits/women/31.jpg"},
        "amenities": [
            {"icon": "🏖", "title": "Beach access", "desc": "Walk to sand in 3 minutes."},
            {"icon": "🌊", "title": "Private pool", "desc": "Heated and fenced."},
            {"icon": "🛸", "title": "Bikes included", "desc": "Surf the coast!"},
        ],
    },
    {
        "image": "/images/hotel6.jpg",
        "title": "Countryside Retreat",
        "location": "Cotswolds, UK",
        "rating": 4.43,
        "reviews": 10,
        "guests": 4,
        "bedrooms": 2,
        "beds": 3,
        "baths": 2,
        "datesFrom": "2025-09-01",
        "datesTo": "2025-09-07",
        "price": 211,
        "host": {"name": "Oliver", "since": 5, "avatar": "https://randomuser.me/api/portraits/men/37.jpg"},
        "amenities": [{"icon": "🍃", "title": "Garden", "desc": "Outdoor seating and flower beds."}, {"icon": "⛰", "title": "Country views", "desc": "See sheep and rolling hills."}],
    },
    {
        "image": "/images/hotel7.jpg",
        "title": "Garden Oasis",
        "location": "Amsterdam, Netherlands",
        "rating": 4.32,
        "reviews": 11,
        "guests": 3,
        "bedrooms": 1,
        "beds": 1,
        "baths": 1,
        "datesFrom": "2025-07-15",
        "datesTo": "2025-07-19",
        "price": 537,
        "host": {"name": "Mia", "since": 2, "avatar": "https://randomuser.me/api/portraits/women/45.jpg"},
        "amenities": [{"icon": "🌿", "title": "Private garden", "desc": "Secluded space for relaxation."}, {"icon": "🏰", "title": "Historic building", "desc": "18th-century canal house."}],
    },
    {
        "image": "/images/hotel8.jpg",
        "title": "Modern City Apartment",
        "location": "New York, USA",
        "rating": 4.27,
        "reviews": 25,
        "guests": 2,
        "bedrooms": 1,
        "beds": 1,
        "baths": 1,
        "datesFrom": "2025-07-25",
        "datesTo": "2025-07-28",
        "price": 258,
        "host": {"name": "Harper", "since": 7, "avatar": "https://randomuser.me/api/portraits/men/47.jpg"},
        "amenities": [{"image": "💻", "title": "Fast Wi-Fi", "desc": "1Gbps optic fiber."}, {"icon": "🧰", "title": "Washer/dryer", "desc": "Laundry in unit."}],
    },
    {
        "image": "/images/hotel9.jpg",
        "title": "Seaside Villa",
        "location": "Mykonos, Greece",
        "rating": 4.72,
        "reviews": 21,
        "guests": 6,
        "bedrooms": 3,
        "beds": 4,
        "baths": 2,
        "datesFrom": "2025-08-05",
        "datesTo": "2025-08-12",
        "price": 685,
        "host": {"name": "Niko", "since": 5, "avatar": "https://randomuser.me/api/portraits/men/32.jpg"},
        "amenities": [
            {"icon": "🏖", "title": "Beachfront", "desc": "Step outside to the Aegean Sea."},
            {"icon": "🛋", "title": "Infinity pool", "desc": "Swim with an endless horizon."},
            {"icon": "🎡", "title": "Nightlife nearby", "desc": "Close to beach bars and clubs."},
        ],
    },
    {
        "image": "/images/hotel10.jpg",
        "title": "Tokyo Highrise",
        "location": "Tokyo, Japan",
        "rating": 4.58,
        "reviews": 33,
        "guests": 2,
        "bedrooms": 1,
        "beds": 1,
        "baths": 1,
        "datesFrom": "2025-09-01",
        "datesTo": "2025-09-06",
        "price": 312,
        "host": {"name": "Hana", "since": 3, "avatar": "https://randomuser.me/api/portraits/women/52.jpg"},
        "amenities": [
            {"icon": "📱", "title": "High-speed Wi-Fi", "desc": "1Gbps fiber for work or play."},
            {"icon": "📺", "title": "Smart TV", "desc": "Includes Netflix & Prime."},
            {"icon": "🖥", "title": "City view", "desc": "Panoramic skyline at night."},
        ],
    },
    {
        "image": "/images/hotel11.jpg",
        "title": "Moroccan Riad",
        "location": "Marrakech, Morocco",
        "rating": 4.81,
        "reviews": 18,
        "guests": 4,
        "bedrooms": 2,
        "beds": 2,
        "baths": 2,
        "datesFrom": "2025-10-10",
        "datesTo": "2025-10-18",
        "price": 432,
        "host": {"name": "Zahra", "since": 6, "avatar": "https://randomuser.me/api/portraits/women/36.jpg"},
        "amenities": [
            {"icon": "🌿", "title": "Private courtyard", "desc": "Relax in traditional decor."},
            {"icon": "🍯", "title": "Mint tea service", "desc": "Daily Moroccan mint tea."},
            {"icon": "🏨", "title": "Local art", "desc": "Handcrafted tile and textiles."},
        ],
    },
    {
        "image": "/images/hotel12.jpg",
        "title": "Nordic Glass Cabin",
        "location": "Lapland, Finland",
        "rating": 4.76,
        "reviews": 16,
        "guests": 2,
        "bedrooms": 1,
        "beds": 1,
        "baths": 1,
        "datesFrom": "2025-12-20",
        "datesTo": "2025-12-27",
        "price": 490,
        "host": {"name": "Erik", "since": 4, "avatar": "https://randomuser.me/api/portraits/men/19.jpg"},
        "amenities": [
            {"icon": "❄", "title": "Aurora views", "desc": "Glass roof for watching the Northern Lights."},
            {"icon": "🧴", "title": "Sauna included", "desc": "Private Finnish sauna with wood stove."},
            {"icon": "🌿", "title": "Eco-heated", "desc": "Geothermal underfloor heating system."},
        ],
    },
]


def parse_datetime(value: str | None) -> datetime | None:
    if not value:
        return None
    try:
        return parser.isoparse(value)
    except (ValueError, TypeError):
        return None


def get_modify_data(hotels_data=None):
    if hotels_data is None:
        hotels_data = FEATURED_HOTELS + DASHBOARD_HOTELS + REGION_HOTELS

    modified_data = []
    for hotel in hotels_data:
        new_dict = {}
        for k, v in hotel.items():
            if isinstance(v, str):
                if k in ["datesFrom", "datesTo"]:
                    new_dict[k] = parse_datetime(v)
                else:
                    new_dict[k] = v
            elif isinstance(v, dict):
                for nk, nv in v.items():
                    new_dict[k + "_" + nk] = nv
            elif isinstance(v, list):
                if k == "amenities":
                    new_dict["amenities"] = [sv["title"] for sv in v if sv.get("title")]
            else:
                new_dict[k] = v

        modified_data.append(new_dict)
    return modified_data


HOTELS_DATA_MODIFIED = get_modify_data()

LOGICAL_OPERATORS = [EQUALS, NOT_EQUALS, GREATER_EQUAL, GREATER_THAN, LESS_EQUAL, LESS_THAN]
STRING_OPERATORS = [EQUALS, NOT_EQUALS, CONTAINS, NOT_CONTAINS]
ARRAY_OPERATORS = [EQUALS, NOT_EQUALS, IN_LIST, NOT_IN_LIST]

FIELD_OPERATORS_SEARCH_HOTEL_MAP = {
    "search_term": STRING_OPERATORS,
    "dateFrom": LOGICAL_OPERATORS,
    "dateTo": LOGICAL_OPERATORS,
    "adults": LOGICAL_OPERATORS,
    "children": LOGICAL_OPERATORS,
    "infants": LOGICAL_OPERATORS,
    "pets": LOGICAL_OPERATORS,
}

FIELD_OPERATORS_VIEW_HOTEL_MAP = {
    # 'id': LOGICAL_OPERATORS,
    "title": STRING_OPERATORS,
    "location": STRING_OPERATORS,
    "rating": LOGICAL_OPERATORS,
    "price": LOGICAL_OPERATORS,
    "dateFrom": LOGICAL_OPERATORS,
    "dateTo": LOGICAL_OPERATORS,
    "guests": LOGICAL_OPERATORS,
    "host_name": STRING_OPERATORS,
    "host_since": LOGICAL_OPERATORS,
    # 'host_avatar': STRING_OPERATORS,
    "amenities": [IN_LIST, NOT_IN_LIST, EQUALS, NOT_EQUALS],
}

FIELD_OPERATORS_GUESTS_CHANGE_MAP = {"from_guests": [EQUALS, GREATER_EQUAL, GREATER_THAN], "to_guests": [EQUALS, LESS_EQUAL, LESS_THAN]}

FIELD_OPERATORS_INCREASE_GUESTS_MAP = {
    # "from_guests": [EQUALS, GREATER_EQUAL, GREATER_THAN],
    "to_guests": [EQUALS, LESS_EQUAL, LESS_THAN],
    "title": STRING_OPERATORS,
    "location": [EQUALS],
    # "image": STRING_OPERATORS,
    "price": [EQUALS],
    "rating": [EQUALS],
    "reviews": [EQUALS],
    "guests": [EQUALS],
    "datesFrom": [EQUALS],
    "datesTo": [EQUALS],
    "baths": [EQUALS],
    "bedrooms": [EQUALS],
    "beds": [EQUALS],
    "host_name": [EQUALS],
    "host_since": [EQUALS],
    # "host_avatar": STRING_OPERATORS,
    "amenities": [EQUALS],
}

FIELD_OPERATORS_DECREASE_GUESTS_MAP = {"from_guests": LOGICAL_OPERATORS, "to_guests": LOGICAL_OPERATORS}

FIELD_OPERATORS_RESERVE_HOTEL_MAP = {
    # "hotel_id": LOGICAL_OPERATORS,
    "guests": LOGICAL_OPERATORS,
    "checkin": [EQUALS, GREATER_THAN, LESS_THAN],
    "checkout": [EQUALS, GREATER_THAN, LESS_THAN],
}
FIELD_OPERATORS_EDIT_CHECKIN_OUT_MAP = {
    "checkin": LOGICAL_OPERATORS,
    "checkout": LOGICAL_OPERATORS,
    "source": STRING_OPERATORS,
}
FIELD_OPERATORS_CONFIRM_AND_PAY_MAP = {
    "checkin": LOGICAL_OPERATORS,  # datetime
    "checkout": LOGICAL_OPERATORS,  # datetime
    "guests": LOGICAL_OPERATORS,  # int
    "listingTitle": STRING_OPERATORS,  # str
    "pricePerNight": LOGICAL_OPERATORS,  # int
    "nights": LOGICAL_OPERATORS,  # int
    "priceSubtotal": LOGICAL_OPERATORS,  # int
    "cleaningFee": LOGICAL_OPERATORS,  # int
    "serviceFee": LOGICAL_OPERATORS,  # int
    "total": LOGICAL_OPERATORS,  # int
    "paymentMethod": STRING_OPERATORS,  # str
    "country": STRING_OPERATORS,  # str
    # "source": STRING_OPERATORS,              # str
}

FIELD_OPERATORS_MESSAGE_HOST_MAP = {
    **FIELD_OPERATORS_VIEW_HOTEL_MAP,
    "message": STRING_OPERATORS,
    "host_name": STRING_OPERATORS,
    # "source": STRING_OPERATORS,
}
