from ..operators import CONTAINS, EQUALS, GREATER_EQUAL, GREATER_THAN, IN_LIST, LESS_EQUAL, LESS_THAN, NOT_CONTAINS, NOT_EQUALS, NOT_IN_LIST

CALENDAR_NAMES = [
    "Personal",
    "Fitness",
    "Study",
    "Travel",
    "Holidays",
    "Birthdays",
    "Projects",
    "Health",
    "Finance",
    "Shopping",
    "Entertainment",
    "Social",
    "Hobbies",
    "Goals",
    "Maintenance",
    "Volunteer",
    "Side Business",
    "Learning",
    "Creative",
    "Spiritual",
    "Medical",
    "Insurance",
    "Legal",
    "Investment",
    "Real Estate",
    "Career",
    "Networking",
    "Self Care",
    "Meditation",
    "Reading",
    "Writing",
    "Photography",
    "Cooking",
    "Gardening",
    "Home Improvement",
    "Pet Care",
    "Child Care",
    "Elder Care",
    "Community Service",
]

EVENT_TITLES = [
    "Meeting",
    "Doctor appointment",
    "Lunch",
    "Conference call",
    "Workout",
    "Study session",
    "Dentist visit",
    "Job interview",
    "Team standup",
    "Code review",
    "Client presentation",
    "Yoga class",
    "Piano lesson",
    "Car maintenance",
    "Grocery shopping",
    "Book club",
    "Birthday party",
    "Date night",
    "Therapy session",
    "Tax appointment",
    "Blood test",
    "Hair appointment",
    "Oil change",
    "Pet vet visit",
    "Parent-teacher conference",
    "Board meeting",
    "Training workshop",
    "Performance review",
    "Budget planning",
    "Insurance renewal",
    "Mortgage meeting",
    "Legal consultation",
    "Eye exam",
    "Therapy appointment",
    "Chiropractor visit",
    "Physical therapy",
    "Vaccination",
    "Wedding planning",
    "Anniversary dinner",
    "Family reunion",
    "Graduation ceremony",
    "Art class",
    "Language lesson",
    "Cooking class",
    "Photography workshop",
    "Home inspection",
    "Contractor meeting",
    "Garden maintenance",
    "Pet grooming",
]

EXISTING_CALENDAR_NAMES = ["Work", "Family", "Personal", "Friends", "Wellness"]

DESCRIPTIONS = [
    "Team meeting to discuss project updates",
    "Doctor's appointment",
    "Birthday celebration for a friend",
    "Weekly fitness class",
    "Family dinner at home",
    "Business trip to New York",
    "Online webinar on productivity",
    "Study session for exams",
    "Holiday planning session",
    "Client presentation review",
    "Quarterly performance review with manager",
    "Sprint planning meeting for new features",
    "Annual health checkup with primary care physician",
    "Piano recital practice session",
    "Weekly grocery shopping at local market",
    "Investment portfolio review with financial advisor",
    "Dog training class at community center",
    "Book club discussion on monthly selection",
    "Home inspection for insurance purposes",
    "Volunteer shift at local food bank",
    "Online course completion deadline",
    "Car registration renewal at DMV",
    "Wedding anniversary dinner reservation",
    "Tax document preparation meeting",
    "Kids soccer game at local field",
    "Strategic planning session for Q4 objectives",
    "Dental cleaning and checkup appointment",
    "Weekly team building lunch meeting",
    "Product launch preparation meeting",
    "Insurance claim review appointment",
    "Real estate property viewing tour",
    "Legal contract review session",
    "Annual eye examination and prescription update",
    "Physical therapy session for knee injury",
    "Wedding venue tour and tasting",
    "Parent volunteer meeting at school",
    "Art gallery opening reception",
    "Language exchange conversation practice",
    "Home renovation contractor consultation",
    "Pet vaccination appointment at veterinary clinic",
]

REMINDER_MINUTES = [5, 10, 15, 30, 60, 120, 1440]

ATTENDEE_EMAILS = [
    "test@example.com",
    "user1@work.com",
    "friend@email.net",
    "contact@domain.org",
    "manager@company.com",
    "teammate@work.org",
    "client@business.net",
    "doctor@clinic.com",
    "trainer@gym.com",
    "teacher@school.edu",
    "advisor@finance.com",
    "family@home.net",
    "colleague@office.com",
    "partner@project.org",
    "specialist@medical.com",
    "coach@sports.net",
    "assistant@office.com",
    "director@company.com",
    "consultant@firm.com",
    "vendor@supplier.net",
    "lawyer@legal.com",
    "accountant@tax.org",
    "realtor@property.net",
    "contractor@build.com",
    "therapist@wellness.com",
    "dentist@dental.org",
    "optometrist@vision.net",
    "pharmacist@med.com",
]

RECURRENCE_OPTIONS = ["None", "Daily", "Weekly", "Monthly"]

VISIBILITY_OPTIONS = ["Public", "Private", "Default"]

LOCATIONS = [
    "Office",
    "Conference Room A",
    "Online",
    "Client's Office",
    "Home",
    "Coffee Shop",
    "Library",
    "Gym",
    "Hospital",
    "School",
    "Restaurant",
    "Park",
    "Mall",
    "Bank",
    "Government Building",
    "Community Center",
    "Hotel",
    "Airport",
    "Train Station",
    "Beach",
    "Museum",
    "Theater",
    "Stadium",
    "Church",
    "Courthouse",
    "Conference Room B",
    "Conference Room C",
    "Board Room",
    "Training Room",
    "Cafeteria",
    "Parking Lot",
    "Reception Area",
    "Workshop",
    "Laboratory",
    "Clinic",
    "Pharmacy",
    "Dentist Office",
    "Law Office",
    "Accounting Firm",
    "Real Estate Office",
    "Spa",
    "Salon",
    "Garage",
    "Garden Center",
    "Pet Store",
    "Veterinary Clinic",
]

MEETING_LINKS = [
    "https://meet.example.com/abc-123",
    "https://zoom.example.com/j/987654321",
    "https://teams.example.com/l/meetup-join/...",
    "https://webex.example.com/meet/room123",
    "https://gotomeeting.example.com/join/456789",
    "https://skype.example.com/meet-now/conference",
    "https://discord.gg/meeting-room",
    "https://hangouts.google.com/call/xyz789",
    "https://jitsi.meet/ConferenceRoom2024",
    "https://bluejeans.com/meetings/123456789",
    "https://meet.google.com/abc-defg-hij",
    "https://us02web.zoom.us/j/123456789",
    "https://teams.microsoft.com/l/meetup-join/19%3ameeting_abc",
    "https://whereby.com/meeting-room-123",
    "https://bigbluebutton.org/gl/abc-def-ghi",
]
EVENTS_DATASET = [
    {
        "id": "1",
        "date": "2025-08-15",
        "start": 9,
        "end": 10,
        "label": "Team Meeting",
        "calendar": "Work",
        "color": "#2196F3",
        "start_time": [9, 0],
        "end_time": [10, 0],
        "description": "Weekly sync with team.",
        "location": "Zoom",
        "all_day": False,
        "recurrence": "weekly",
        "recurrence_end_date": "2025-12-31",
        "attendees": ["alice@example.com", "bob@example.com"],
        "reminders": [30],
        "busy": True,
        "visibility": "default",
        "meeting_link": "https://zoom.us/j/123456789",
    },
    {
        "id": "2",
        "date": "2025-08-16",
        "start": 14,
        "end": 15,
        "label": "Doctor Appointment",
        "calendar": "Personal",
        "color": "#E53935",
        "start_time": [14, 0],
        "end_time": [15, 0],
        "description": "Annual checkup.",
        "location": "Clinic",
        "all_day": False,
        "recurrence": "none",
        "recurrence_end_date": "2025-08-16",
        "attendees": [],
        "reminders": [60],
        "busy": False,
        "visibility": "private",
        "meeting_link": "",
    },
    {
        "id": "3",
        "date": "2025-08-17",
        "start": 11,
        "end": 12,
        "label": "Project Demo",
        "calendar": "Work",
        "color": "#2196F3",
        "start_time": [11, 0],
        "end_time": [12, 0],
        "description": "Demo for client.",
        "location": "Office",
        "all_day": False,
        "recurrence": "none",
        "recurrence_end_date": "2025-08-17",
        "attendees": ["client@example.com"],
        "reminders": [15],
        "busy": True,
        "visibility": "public",
        "meeting_link": "https://meet.google.com/abc-defg-hij",
    },
    {
        "id": "4",
        "date": "2025-08-18",
        "start": 8,
        "end": 9,
        "label": "Yoga Class",
        "calendar": "Wellness",
        "color": "#43A047",
        "start_time": [8, 0],
        "end_time": [9, 0],
        "description": "Morning yoga at the park.",
        "location": "Central Park",
        "all_day": False,
        "recurrence": "daily",
        "recurrence_end_date": "2025-08-25",
        "attendees": ["jane@example.com"],
        "reminders": [10],
        "busy": False,
        "visibility": "public",
        "meeting_link": "",
    },
    {
        "id": "5",
        "date": "2025-08-19",
        "start": 19,
        "end": 21,
        "label": "Movie Night",
        "calendar": "Friends",
        "color": "#FBC02D",
        "start_time": [19, 0],
        "end_time": [21, 0],
        "description": "Watching the latest blockbuster.",
        "location": "Cinema City",
        "all_day": False,
        "recurrence": "none",
        "recurrence_end_date": None,
        "attendees": ["bob@example.com", "alice@example.com"],
        "reminders": [120],
        "busy": False,
        "visibility": "default",
        "meeting_link": "",
    },
    {
        "id": "6",
        "date": "2025-08-20",
        "start": 13,
        "end": 14,
        "label": "Lunch with Mentor",
        "calendar": "Personal",
        "color": "#8E24AA",
        "start_time": [13, 0],
        "end_time": [14, 0],
        "description": "Catch up and career advice.",
        "location": "Cafe Delight",
        "all_day": False,
        "recurrence": "none",
        "recurrence_end_date": None,
        "attendees": ["mentor@example.com"],
        "reminders": [30],
        "busy": False,
        "visibility": "private",
        "meeting_link": "",
    },
    {
        "id": "7",
        "date": "2025-08-21",
        "start": 17,
        "end": 18,
        "label": "Parent-Teacher Meeting",
        "calendar": "Family",
        "color": "#D81B60",
        "start_time": [17, 0],
        "end_time": [18, 0],
        "description": "Discuss progress at school.",
        "location": "Greenwood School",
        "all_day": False,
        "recurrence": "none",
        "recurrence_end_date": None,
        "attendees": ["teacher@example.com"],
        "reminders": [60],
        "busy": True,
        "visibility": "default",
        "meeting_link": "",
    },
    {
        "id": "8",
        "date": "2025-08-22",
        "start": 10,
        "end": 12,
        "label": "Hackathon",
        "calendar": "Work",
        "color": "#1976D2",
        "start_time": [10, 0],
        "end_time": [12, 0],
        "description": "Internal company hackathon.",
        "location": "HQ - Main Hall",
        "all_day": False,
        "recurrence": "none",
        "recurrence_end_date": None,
        "attendees": ["dev1@example.com", "dev2@example.com"],
        "reminders": [60],
        "busy": True,
        "visibility": "public",
        "meeting_link": "https://meet.google.com/hackathon-2025",
    },
    {
        "id": "9",
        "date": "2025-08-13",
        "start": 8,
        "end": 9,
        "label": "Morning Run",
        "calendar": "Wellness",
        "color": "#43A047",
        "start_time": [8, 0],
        "end_time": [9, 0],
        "description": "Quick run before work.",
        "location": "Neighborhood",
        "all_day": False,
        "recurrence": "none",
        "recurrence_end_date": None,
        "attendees": [],
        "reminders": [15],
        "busy": False,
        "visibility": "default",
        "meeting_link": "",
    },
    {
        "id": "10",
        "date": "2025-08-13",
        "start": 18,
        "end": 19,
        "label": "Dinner with Friends",
        "calendar": "Friends",
        "color": "#FBC02D",
        "start_time": [18, 0],
        "end_time": [19, 0],
        "description": "Catch up at the new restaurant.",
        "location": "Downtown Grill",
        "all_day": False,
        "recurrence": "none",
        "recurrence_end_date": None,
        "attendees": ["bob@example.com", "alice@example.com"],
        "reminders": [60],
        "busy": False,
        "visibility": "default",
        "meeting_link": "",
    },
    {
        "id": "11",
        "date": "2025-08-14",
        "start": 15,
        "end": 16,
        "label": "Design Review",
        "calendar": "Work",
        "color": "#2196F3",
        "start_time": [15, 0],
        "end_time": [16, 0],
        "description": "Review new UI designs.",
        "location": "Zoom",
        "all_day": False,
        "recurrence": "none",
        "recurrence_end_date": None,
        "attendees": ["designer@example.com"],
        "reminders": [30],
        "busy": True,
        "visibility": "default",
        "meeting_link": "https://zoom.us/j/987654321",
    },
    {
        "id": "12",
        "date": "2025-08-15",
        "start": 13,
        "end": 14,
        "label": "1:1 with Manager",
        "calendar": "Work",
        "color": "#2196F3",
        "start_time": [13, 0],
        "end_time": [14, 0],
        "description": "Monthly check-in.",
        "location": "Office",
        "all_day": False,
        "recurrence": "monthly",
        "recurrence_end_date": "2025-12-15",
        "attendees": ["manager@example.com"],
        "reminders": [30],
        "busy": True,
        "visibility": "private",
        "meeting_link": "",
    },
    {
        "id": "13",
        "date": "2025-08-17",
        "start": 20,
        "end": 22,
        "label": "Game Night",
        "calendar": "Friends",
        "color": "#FBC02D",
        "start_time": [20, 0],
        "end_time": [22, 0],
        "description": "Board games and snacks.",
        "location": "Alice's House",
        "all_day": False,
        "recurrence": "weekly",
        "recurrence_end_date": "2025-09-28",
        "attendees": ["bob@example.com", "alice@example.com", "jane@example.com"],
        "reminders": [60],
        "busy": False,
        "visibility": "default",
        "meeting_link": "",
    },
    {
        "id": "14",
        "date": "2025-08-20",
        "start": 9,
        "end": 10,
        "label": "Dentist Appointment",
        "calendar": "Personal",
        "color": "#8E24AA",
        "start_time": [9, 0],
        "end_time": [10, 0],
        "description": "Routine cleaning.",
        "location": "Smile Dental",
        "all_day": False,
        "recurrence": "none",
        "recurrence_end_date": None,
        "attendees": [],
        "reminders": [60],
        "busy": False,
        "visibility": "private",
        "meeting_link": "",
    },
    {
        "id": "15",
        "date": "2025-08-25",
        "start": 10,
        "end": 11,
        "label": "Sprint Planning",
        "calendar": "Work",
        "color": "#2196F3",
        "start_time": [10, 0],
        "end_time": [11, 0],
        "description": "Plan next sprint tasks.",
        "location": "Zoom",
        "all_day": False,
        "recurrence": "monthly",
        "recurrence_end_date": "2025-12-25",
        "attendees": ["dev1@example.com", "dev2@example.com"],
        "reminders": [30],
        "busy": True,
        "visibility": "default",
        "meeting_link": "https://zoom.us/j/1122334455",
    },
]
LOGICAL_OPERATORS = [EQUALS, NOT_EQUALS, GREATER_EQUAL, GREATER_THAN, LESS_EQUAL, LESS_THAN]
STRING_OPERATORS = [EQUALS, NOT_EQUALS, CONTAINS, NOT_CONTAINS]
ARRAY_OPERATORS = [CONTAINS, NOT_CONTAINS, IN_LIST, NOT_IN_LIST]
EQUALITY_OPERATORS = [EQUALS, NOT_EQUALS]
EQUAL_OPERATOR = [EQUALS]

FIELD_OPERATORS_CREATE_CALENDAR_MAP = {
    "name": STRING_OPERATORS,
    "description": STRING_OPERATORS,
}
FIELD_OPERATORS_CHOOSE_CALENDAR_MAP = {
    "calendar_name": STRING_OPERATORS,
    "selected": [EQUALS],
}
FIELD_OPERATORS_ADD_EVENT_MAP = {
    "title": STRING_OPERATORS,
    "calendar": STRING_OPERATORS,
    "date": LOGICAL_OPERATORS,
    "start_time": LOGICAL_OPERATORS,
    "end_time": LOGICAL_OPERATORS,
    "all_day": EQUALITY_OPERATORS,
    "recurrence": EQUALITY_OPERATORS,
    "attendees": EQUALITY_OPERATORS,
    "reminders": EQUALITY_OPERATORS,
    "busy": EQUALITY_OPERATORS,
    "visibility": EQUALITY_OPERATORS,
    "location": STRING_OPERATORS,
    "description": STRING_OPERATORS,
    "meeting_link": EQUALITY_OPERATORS,
}
FIELD_OPERATORS_CLICK_CELL_MAP = {
    # "source": EQUALITY_OPERATORS,
    "date": LOGICAL_OPERATORS,
    "hour": LOGICAL_OPERATORS,
    "view": EQUAL_OPERATOR,
}
# FIELD_OPERATORS_CANCEL_ADD_EVENT_MAP = {
#     "source": STRING_OPERATORS,
#     "date": LOGICAL_OPERATORS,
#     "title": LOGICAL_OPERATORS,
# }
# FIELD_OPERATORS_DELETE_ADD_EVENT_MAP = {
#     "source": STRING_OPERATORS,
#     "date": LOGICAL_OPERATORS,
#     "event_title": STRING_OPERATORS,
#     "calendar": STRING_OPERATORS,
# }
FIELD_OPERATORS_SEARCH_SUBMIT_MAP = {
    "query": STRING_OPERATORS,
}

FIELD_OPERATORS_EVENT_REMINDER_MAP = {
    "minutes": LOGICAL_OPERATORS,
    # "idx": LOGICAL_OPERATORS,
}

FIELD_OPERATORS_EVENT_ATTENDEE_MAP = {
    "email": STRING_OPERATORS,
}
