PRODUCTS_DATA = [
    {
        "id": "kitchen-1",
        "title": "Espresso Machine",
        "price": "$160.00",
        "description": "Professional-grade espresso machine with steam wand and programmable settings.",
        "category": "Kitchen",
        "rating": 4.5,
        "brand": "BrewMaster",
        "inStock": True,
    },
    {
        "id": "kitchen-2",
        "title": "Air Fryer",
        "price": "$89.99",
        "description": "4.2L capacity air fryer with digital touchscreen and 8 preset cooking functions.",
        "category": "Kitchen",
        "rating": 4.7,
        "brand": "ChefPlus",
        "inStock": True,
    },
    {
        "id": "kitchen-3",
        "title": "Stainless Steel Cookware Set",
        "price": "$129.95",
        "description": "10-piece stainless steel cookware set with induction-compatible bases.",
        "category": "Kitchen",
        "rating": 4.6,
        "brand": "CuisinePro",
        "inStock": True,
    },
    {
        "id": "kitchen-4",
        "title": "Smart Blender",
        "price": "$75.50",
        "description": "1200W smart blender with 8-speed settings and pre-programmed smoothie functions.",
        "category": "Kitchen",
        "rating": 4.4,
        "brand": "BlendTech",
        "inStock": True,
    },
    {
        "id": "kitchen-5",
        "title": "Electric Kettle",
        "price": "$32.99",
        "description": "1.7L rapid boil kettle with auto shut-off and boil-dry protection.",
        "category": "Kitchen",
        "rating": 4.3,
        "brand": "KitchenAid",
        "inStock": True,
    },
    {
        "id": "kitchen-6",
        "title": "Food Processor",
        "price": "$112.00",
        "description": "12-cup capacity food processor with 6 interchangeable blades and discs.",
        "category": "Kitchen",
        "rating": 4.5,
        "brand": "Cuisinart",
        "inStock": True,
    },
    {
        "id": "kitchen-7",
        "title": "Stand Mixer",
        "price": "$249.99",
        "description": "5-quart stand mixer with 10-speed settings and included attachments.",
        "category": "Kitchen",
        "rating": 4.8,
        "brand": "KitchenAid",
        "inStock": True,
    },
    {
        "id": "kitchen-8",
        "title": "Slow Cooker",
        "price": "$45.75",
        "description": "6-quart programmable slow cooker with digital timer and keep-warm function.",
        "category": "Kitchen",
        "rating": 4.4,
        "brand": "Crock-Pot",
        "inStock": True,
    },
    {
        "id": "kitchen-9",
        "title": "Rice Cooker",
        "price": "$39.99",
        "description": "5-cup rice cooker with steamer basket and automatic keep-warm function.",
        "category": "Kitchen",
        "rating": 4.2,
        "brand": "Aroma",
        "inStock": True,
    },
    {
        "id": "kitchen-10",
        "title": "Immersion Blender",
        "price": "$59.95",
        "description": "300W immersion blender with 2-speed control and stainless steel blades.",
        "category": "Kitchen",
        "rating": 4.3,
        "brand": "Braun",
        "inStock": True,
    },
    {
        "id": "tech-1",
        "title": "Wireless Earbuds",
        "price": "$129.99",
        "description": "True wireless earbuds with active noise cancellation and 24-hour battery life.",
        "category": "Electronics",
        "rating": 4.7,
        "brand": "SoundCore",
        "inStock": True,
    },
    {
        "id": "tech-2",
        "title": "Smart Watch",
        "price": "$199.00",
        "description": "Fitness tracker with heart rate monitor, GPS, and 7-day battery life.",
        "category": "Electronics",
        "rating": 4.6,
        "brand": "FitTech",
        "inStock": True,
    },
    {
        "id": "tech-3",
        "title": "4K Smart TV",
        "price": "$499.99",
        "description": "55-inch 4K UHD smart TV with HDR and built-in streaming apps.",
        "category": "Electronics",
        "rating": 4.8,
        "brand": "Sony",
        "inStock": True,
    },
    {
        "id": "tech-4",
        "title": "Gaming Laptop",
        "price": "$1,299.00",
        "description": "15.6-inch gaming laptop with RTX 3060 graphics and 144Hz display.",
        "category": "Electronics",
        "rating": 4.9,
        "brand": "ROG",
        "inStock": True,
    },
    {
        "id": "tech-5",
        "title": "Wireless Router",
        "price": "$89.95",
        "description": "Wi-Fi 6 router with dual-band and mesh network compatibility.",
        "category": "Electronics",
        "rating": 4.5,
        "brand": "NetLink",
        "inStock": True,
    },
    {
        "id": "tech-6",
        "title": "Bluetooth Speaker",
        "price": "$79.99",
        "description": "Waterproof portable speaker with 20-hour playtime and deep bass.",
        "category": "Electronics",
        "rating": 4.6,
        "brand": "JBL",
        "inStock": True,
    },
    {
        "id": "tech-7",
        "title": "Tablet",
        "price": "$329.00",
        "description": "10.2-inch tablet with 64GB storage and stylus support.",
        "category": "Electronics",
        "rating": 4.4,
        "brand": "Apple",
        "inStock": True,
    },
    {
        "id": "tech-8",
        "title": "Noise Cancelling Headphones",
        "price": "$179.95",
        "description": "Over-ear headphones with 30-hour battery life and built-in mic.",
        "category": "Electronics",
        "rating": 4.7,
        "brand": "Bose",
        "inStock": True,
    },
    {
        "id": "tech-9",
        "title": "External SSD",
        "price": "$129.00",
        "description": "1TB portable SSD with USB-C and 1050MB/s read speeds.",
        "category": "Electronics",
        "rating": 4.8,
        "brand": "Samsung",
        "inStock": True,
    },
    {
        "id": "tech-10",
        "title": "Smart Thermostat",
        "price": "$149.99",
        "description": "Learning thermostat that adapts to your schedule and saves energy.",
        "category": "Electronics",
        "rating": 4.6,
        "brand": "Nest",
        "inStock": True,
    },
    {
        "id": "home-1",
        "title": "Memory Foam Mattress",
        "price": "$399.00",
        "description": "10-inch gel memory foam mattress with cooling technology.",
        "category": "Home",
        "rating": 4.7,
        "brand": "SleepWell",
        "inStock": True,
    },
    {
        "id": "home-2",
        "title": "Sectional Sofa",
        "price": "$899.99",
        "description": "L-shaped sectional sofa with reversible chaise and stain-resistant fabric.",
        "category": "Home",
        "rating": 4.5,
        "brand": "FurniComfort",
        "inStock": True,
    },
    {
        "id": "home-3",
        "title": "Coffee Table",
        "price": "$149.95",
        "description": "Modern coffee table with tempered glass top and metal frame.",
        "category": "Home",
        "rating": 4.3,
        "brand": "ModLiving",
        "inStock": True,
    },
    {
        "id": "home-4",
        "title": "Dining Table Set",
        "price": "$599.00",
        "description": "5-piece dining set with extendable table and 4 upholstered chairs.",
        "category": "Home",
        "rating": 4.6,
        "brand": "HomeStyle",
        "inStock": True,
    },
    {
        "id": "home-5",
        "title": "Bookshelf",
        "price": "$79.99",
        "description": "5-tier wooden bookshelf with adjustable shelves.",
        "category": "Home",
        "rating": 4.2,
        "brand": "FurniComfort",
        "inStock": True,
    },
    {
        "id": "home-6",
        "title": "Area Rug",
        "price": "$129.95",
        "description": "5'x7' plush area rug with non-slip backing.",
        "category": "Home",
        "rating": 4.4,
        "brand": "RugVista",
        "inStock": True,
    },
    {
        "id": "home-7",
        "title": "Blackout Curtains",
        "price": "$39.99",
        "description": "Thermal insulated blackout curtains with noise reduction.",
        "category": "Home",
        "rating": 4.5,
        "brand": "HomeStyle",
        "inStock": True,
    },
    {
        "id": "home-8",
        "title": "Desk Lamp",
        "price": "$29.95",
        "description": "LED desk lamp with adjustable brightness and color temperature.",
        "category": "Home",
        "rating": 4.3,
        "brand": "BrightTech",
        "inStock": True,
    },
    {
        "id": "home-9",
        "title": "Wall Mirror",
        "price": "$59.00",
        "description": "Round wall mirror with rustic wooden frame.",
        "category": "Home",
        "rating": 4.4,
        "brand": "ModLiving",
        "inStock": True,
    },
    {
        "id": "home-10",
        "title": "Throw Pillow Set",
        "price": "$24.99",
        "description": "Set of 2 decorative throw pillows with removable covers.",
        "category": "Home",
        "rating": 4.2,
        "brand": "CozyHome",
        "inStock": True,
    },
    # Health & Fitness (10 items)
    {
        "id": "fitness-1",
        "title": "Yoga Mat",
        "price": "$29.95",
        "description": "6mm thick non-slip yoga mat with carrying strap.",
        "category": "Fitness",
        "rating": 4.6,
        "brand": "Gaiam",
        "inStock": True,
    },
    {
        "id": "fitness-2",
        "title": "Dumbbell Set",
        "price": "$89.99",
        "description": "Adjustable dumbbell set with 5-25lb range.",
        "category": "Fitness",
        "rating": 4.7,
        "brand": "Bowflex",
        "inStock": True,
    },
    {
        "id": "fitness-3",
        "title": "Resistance Bands",
        "price": "$19.99",
        "description": "5-piece set of latex resistance bands with handles.",
        "category": "Fitness",
        "rating": 4.5,
        "brand": "TheraBand",
        "inStock": True,
    },
    {
        "id": "fitness-4",
        "title": "Foam Roller",
        "price": "$24.95",
        "description": "High-density foam roller for muscle recovery.",
        "category": "Fitness",
        "rating": 4.4,
        "brand": "TriggerPoint",
        "inStock": True,
    },
    {
        "id": "fitness-5",
        "title": "Jump Rope",
        "price": "$12.99",
        "description": "Adjustable speed jump rope with ball bearings.",
        "category": "Fitness",
        "rating": 4.3,
        "brand": "CrossRope",
        "inStock": True,
    },
    {
        "id": "fitness-6",
        "title": "Smart Scale",
        "price": "$49.95",
        "description": "Bluetooth body composition scale with 13 metrics.",
        "category": "Fitness",
        "rating": 4.5,
        "brand": "Withings",
        "inStock": True,
    },
    {
        "id": "fitness-7",
        "title": "Running Shoes",
        "price": "$89.99",
        "description": "Lightweight running shoes with responsive cushioning.",
        "category": "Fitness",
        "rating": 4.7,
        "brand": "Nike",
        "inStock": True,
    },
    {
        "id": "fitness-8",
        "title": "Water Bottle",
        "price": "$19.95",
        "description": "32oz insulated stainless steel water bottle.",
        "category": "Fitness",
        "rating": 4.6,
        "brand": "HydroFlask",
        "inStock": True,
    },
    {
        "id": "fitness-9",
        "title": "Massage Gun",
        "price": "$129.00",
        "description": "Deep tissue percussion massage gun with 5 attachments.",
        "category": "Fitness",
        "rating": 4.8,
        "brand": "Theragun",
        "inStock": True,
    },
    {
        "id": "fitness-10",
        "title": "Yoga Block",
        "price": "$14.99",
        "description": "High-density EVA foam yoga block for support and alignment.",
        "category": "Fitness",
        "rating": 4.4,
        "brand": "Gaiam",
        "inStock": True,
    },
    # Outdoor & Garden (10 items)
    {
        "id": "outdoor-1",
        "title": "Patio Furniture Set",
        "price": "$399.99",
        "description": "4-piece rattan patio set with weather-resistant cushions.",
        "category": "Outdoor",
        "rating": 4.6,
        "brand": "OutdoorLiving",
        "inStock": True,
    },
    {
        "id": "outdoor-2",
        "title": "Grill",
        "price": "$249.95",
        "description": "3-burner propane gas grill with side shelf and thermometer.",
        "category": "Outdoor",
        "rating": 4.7,
        "brand": "Weber",
        "inStock": True,
    },
    {
        "id": "outdoor-3",
        "title": "Hammock",
        "price": "$59.99",
        "description": "Double hammock with space-saving steel stand.",
        "category": "Outdoor",
        "rating": 4.5,
        "brand": "Eno",
        "inStock": True,
    },
    {
        "id": "outdoor-4",
        "title": "Garden Tool Set",
        "price": "$39.95",
        "description": "6-piece stainless steel gardening tool set with tote bag.",
        "category": "Outdoor",
        "rating": 4.4,
        "brand": "Fiskars",
        "inStock": True,
    },
    {
        "id": "outdoor-5",
        "title": "Outdoor String Lights",
        "price": "$29.99",
        "description": "48ft waterproof LED string lights with 25 bulbs.",
        "category": "Outdoor",
        "rating": 4.6,
        "brand": "Brightech",
        "inStock": True,
    },
    {
        "id": "outdoor-6",
        "title": "Fire Pit",
        "price": "$149.00",
        "description": "30-inch steel fire pit with spark screen and poker.",
        "category": "Outdoor",
        "rating": 4.7,
        "brand": "OutdoorLiving",
        "inStock": True,
    },
    {
        "id": "outdoor-7",
        "title": "Planter Box",
        "price": "$49.95",
        "description": "Self-watering raised garden bed with drainage system.",
        "category": "Outdoor",
        "rating": 4.3,
        "brand": "GreenThumb",
        "inStock": True,
    },
    {
        "id": "outdoor-8",
        "title": "Camping Tent",
        "price": "$129.99",
        "description": "4-person dome tent with rainfly and ventilation.",
        "category": "Outdoor",
        "rating": 4.5,
        "brand": "Coleman",
        "inStock": True,
    },
    {
        "id": "outdoor-9",
        "title": "Cooler",
        "price": "$79.95",
        "description": "50-quart rotomolded cooler with 7-day ice retention.",
        "category": "Outdoor",
        "rating": 4.8,
        "brand": "Yeti",
        "inStock": True,
    },
    {
        "id": "outdoor-10",
        "title": "Bird Feeder",
        "price": "$24.99",
        "description": "Squirrel-proof bird feeder with 2.5lb capacity.",
        "category": "Outdoor",
        "rating": 4.4,
        "brand": "Perky-Pet",
        "inStock": True,
    },
]
