services:
  app:
    build: .
    ports:
      - "${PORT:-8080}:8080"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  db:
    image: postgres:13-alpine
    env_file:
      - .env
    ports:
      - "5433:5433"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/initdb.d:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-webs_user} -d ${POSTGRES_DB:-autoppia_db} -p 5433"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network
    command: >
      postgres -p 5433
               -c max_connections=200
               -c shared_buffers=512MB
               -c work_mem=32MB
               -c effective_cache_size=1536MB
               -c maintenance_work_mem=128MB
               -c random_page_cost=1.1
               -c checkpoint_completion_target=0.9

volumes:
  postgres_data:

networks:
  app-network:
    external: true
