from ..operators import CONTAINS, EQUALS, GREATER_EQUAL, GREATER_THAN, IN_LIST, LESS_EQUAL, LESS_THAN, NOT_CONTAINS, NOT_EQUALS, NOT_IN_LIST

LOCATIONS = [
    "1 Hotel San Francisco - 8 Mission St, San Francisco, CA 94105, USA",
    "100 Van Ness - 100 Van Ness Ave, San Francisco, CA 94102, USA",
    "1000 Chestnut Street Apartments - 1000 Chestnut St, San Francisco, CA 94109, USA",
    "1001 Castro Street - 1001 Castro St, San Francisco, CA 94114, USA",
]

STRING_OPERATORS = [EQUALS, NOT_EQUALS, CONTAINS, NOT_CONTAINS]
LOGICAL_OPERATORS = [EQUALS, NOT_EQUALS, GREATER_THAN, LESS_THAN, GREATER_EQUAL, LESS_EQUAL]
LIST_OPERATORS = [CONTAINS, NOT_CONTAINS, IN_LIST, NOT_IN_LIST]

FIELD_OPERATORS_MAP_ENTER_LOCATION = {"value": STRING_OPERATORS}
FIELD_OPERATORS_MAP_ENTER_DESTINATION = {
    **FIELD_OPERATORS_MAP_ENTER_LOCATION,
}
FIELD_OPERATORS_MAP_SEE_PRICES = {
    "location": STRING_OPERATORS,
    "destination": STRING_OPERATORS,
}
FIELD_OPERATORS_MAP_SELECT_DATE = {
    "date": LOGICAL_OPERATORS,
}
FIELD_OPERATORS_MAP_SELECT_TIME = {
    "time": LOGICAL_OPERATORS,
}
FIELD_OPERATORS_MAP_NEXT_PICKUP = {
    "date": LOGICAL_OPERATORS,
    "time": LOGICAL_OPERATORS,
}
