from ..operators import CONTAINS, EQUALS, GREATER_EQUAL, GREATER_THAN, IN_LIST, LESS_EQUAL, LESS_THAN, NOT_CONTAINS, NOT_EQUALS, NOT_IN_LIST

LOGICAL_OPERATORS = [EQUALS, NOT_EQUALS, GREATER_EQUAL, GREATER_THAN, LESS_EQUAL, LESS_THAN]
STRING_OPERATORS = [EQUALS, NOT_EQUALS, CONTAINS, NOT_CONTAINS]
ARRAY_OPERATORS = [CONTAINS, NOT_CONTAINS, IN_LIST, NOT_IN_LIST]
EQUALITY_OPERATORS = [EQUALS, NOT_EQUALS]

FIELD_OPERATORS_SEARCH_RESTAURANT_MAP = {
    "query": STRING_OPERATORS,
}
FIELD_OPERATORS_RESTAURANT_FILTER_MAP = {
    "cuisine": STRING_OPERATORS,
    "rating": LOGICAL_OPERATORS,
}

FIELD_OPERATORS_VIEW_RESTAURANT_MAP = {
    "name": STRING_OPERATORS,
    "cuisine": STRING_OPERATORS,
    "rating": LOGICAL_OPERATORS,
    "description": STRING_OPERATORS,
}

FIELD_OPERATORS_DELETE_REVIEW_MAP = {
    **FIELD_OPERATORS_VIEW_RESTAURANT_MAP,
    "review_rating": STRING_OPERATORS,
    "author": STRING_OPERATORS,
    "date": STRING_OPERATORS,
    "comment": STRING_OPERATORS,
}

FIELD_OPERATORS_ADD_TO_CART_MODAL_OPEN_MAP = {
    "item": STRING_OPERATORS,
    "price": LOGICAL_OPERATORS,
    "restaurant": STRING_OPERATORS,
}

FIELD_OPERATORS_INCREMENT_QUANTITY_MAP = {
    **FIELD_OPERATORS_ADD_TO_CART_MODAL_OPEN_MAP,
    "quantity": LOGICAL_OPERATORS,
}

FIELD_OPERATORS_DECREMENT_QUANTITY_MAP = {
    **FIELD_OPERATORS_ADD_TO_CART_MODAL_OPEN_MAP,
    "quantity": LOGICAL_OPERATORS,
}

FIELD_OPERATORS_ADD_TO_CART_MAP = {
    **FIELD_OPERATORS_INCREMENT_QUANTITY_MAP,
    # "options": ARRAY_OPERATORS,
    "preferences": ARRAY_OPERATORS,
    "size": STRING_OPERATORS,
}

FIELD_OPERATORS_DROPOFF_OPTION_MAP = {
    **FIELD_OPERATORS_ADD_TO_CART_MAP,
    "delivery_preference": EQUALITY_OPERATORS,
}
FIELD_OPERATORS_ADDRESS_ADDED_MAP = {
    **FIELD_OPERATORS_ADD_TO_CART_MAP,
    "address": EQUALITY_OPERATORS,
}

FIELD_OPERATORS_PLACE_ORDER_MAP = {
    **FIELD_OPERATORS_DROPOFF_OPTION_MAP,
    "username": STRING_OPERATORS,
    "phone": EQUALITY_OPERATORS,
    "address": STRING_OPERATORS,
    "mode": STRING_OPERATORS,
}

FIELD_OPERATORS_QUICK_REORDER_MAP = {
    "item": STRING_OPERATORS,
    "restaurant": STRING_OPERATORS,
}
