from ...operators import CONTAINS, EQUALS, GREATER_EQUAL, GREATER_THAN, IN_LIST, LESS_EQUAL, LESS_THAN, NOT_CONTAINS, NOT_EQUALS, NOT_IN_LIST

# Common Operators with Fields
FIELD_OPERATORS_MAP_CONTACT = {
    "name": [EQUALS, NOT_EQUALS, CONTAINS, NOT_CONTAINS],
    "email": [EQUALS, NOT_EQUALS, CONTAINS, NOT_CONTAINS],
    "subject": [EQUALS, NOT_EQUALS, CONTAINS, NOT_CONTAINS],
    "message": [EQUALS, NOT_EQUALS, CONTAINS, NOT_CONTAINS],
}
FIELD_OPERATORS_MAP_EDIT_USER = {
    "first_name": [EQUALS, CONTAINS, NOT_CONTAINS],
    "last_name": [EQUALS, CONTAINS, NOT_CONTAINS],
    "bio": [EQUALS, CONTAINS, NOT_CONTAINS],
    "location": [EQUALS, CONTAINS, NOT_CONTAINS, NOT_EQUALS],
    "website": [NOT_EQUALS, CONTAINS, NOT_CONTAINS],
    "genres": [IN_LIST, NOT_IN_LIST, CONTAINS, NOT_CONTAINS],
}

FIELD_OPERATORS_MAP_ADD_COMMENT = {
    "book_name": [EQUALS, NOT_EQUALS, CONTAINS, NOT_CONTAINS],
    "commenter_name": [EQUALS, NOT_EQUALS, CONTAINS, NOT_CONTAINS],
    "content": [EQUALS, NOT_EQUALS, CONTAINS, NOT_CONTAINS],
}

FIELD_OPERATORS_MAP_VIEW_AUTHOR = {
    "author_name": [EQUALS, NOT_EQUALS, CONTAINS, NOT_CONTAINS],
}


FIELD_OPERATORS_MAP_BOOK = {
    "name": [EQUALS, NOT_EQUALS, CONTAINS, NOT_CONTAINS],
    "year": [EQUALS, NOT_EQUALS, GREATER_THAN, LESS_THAN, GREATER_EQUAL, LESS_EQUAL],
    "rating": [EQUALS, NOT_EQUALS, GREATER_THAN, LESS_THAN, GREATER_EQUAL, LESS_EQUAL],
    "page_count": [EQUALS, NOT_EQUALS, GREATER_THAN, LESS_THAN, GREATER_EQUAL, LESS_EQUAL],
    "genre": [CONTAINS, NOT_CONTAINS, IN_LIST, NOT_IN_LIST],
    "author": [EQUALS, NOT_EQUALS, CONTAINS, NOT_CONTAINS],
    "desc": [EQUALS, NOT_EQUALS, CONTAINS, NOT_CONTAINS],
}

VISIBLE_FIELDS_BOOK_DETAIL = ["name", "author", "year", "rating", "page_count", "genres", "desc"]
VISIBLE_FIELDS_SEARCH_BOOK = ["name", "author", "year", "rating", "page_count", "genres", "desc"]
VISIBLE_FIELDS_FILTER_BOOK = ["genres", "year"]
