from ...operators import CONTAINS, EQUALS, GREATER_EQUAL, GREATER_THAN, IN_LIST, LESS_EQUAL, LESS_THAN, NOT_CONTAINS, NOT_EQUALS, NOT_IN_LIST

STRING_OPERATORS = [EQUALS, NOT_EQUALS, CONTAINS, NOT_CONTAINS]
LOGICAL_OPERATORS = [EQUALS, NOT_EQUALS, GREATER_THAN, LESS_THAN, GREATER_EQUAL, LESS_EQUAL]
LIST_OPERATORS = [CONTAINS, NOT_CONTAINS, IN_LIST, NOT_IN_LIST]
BOOL_OPERATORS = [EQUALS, NOT_EQUALS]

FIELD_OPERATORS_MAP_ENTER_LOCATION = {"location": STRING_OPERATORS}
FIELD_OPERATORS_MAP_ENTER_DESTINATION = {
    "destination": [EQUALS, NOT_EQUALS],
    # "destination": STRING_OPERATORS
}
FIELD_OPERATORS_MAP_SEE_PRICES = {
    "location": STRING_OPERATORS,
    "destination": STRING_OPERATORS,
}
FIELD_OPERATORS_MAP_SELECT_DATE = {
    "date": LOGICAL_OPERATORS,
}
FIELD_OPERATORS_MAP_SELECT_TIME = {
    "time": LOGICAL_OPERATORS,
}
FIELD_OPERATORS_MAP_NEXT_PICKUP = {
    "date": LOGICAL_OPERATORS,
    "time": LOGICAL_OPERATORS,
}
FIELD_OPERATORS_MAP_SEARCH_RIDE = {
    "destination": STRING_OPERATORS,
    "location": STRING_OPERATORS,
    "scheduled": LOGICAL_OPERATORS,
}
FIELD_OPERATORS_MAP_SELECT_CAR = {
    "destination": STRING_OPERATORS,
    "location": STRING_OPERATORS,
    "ride_name": STRING_OPERATORS,
    "scheduled": LOGICAL_OPERATORS,
}
FIELD_OPERATORS_MAP_RESERVE_RIDE = {
    **FIELD_OPERATORS_MAP_SELECT_CAR,
}
FIELD_OPERATORS_MAP_SUBMIT_TRIP_REVIEW = {
    "trip_id": STRING_OPERATORS,
    "rating": LOGICAL_OPERATORS,
}
FIELD_OPERATORS_MAP_VIEW_AVAILABLE_TRIPS = {"total_trips": LOGICAL_OPERATORS}
FIELD_OPERATORS_MAP_BOOK_TRIP = {
    **FIELD_OPERATORS_MAP_RESERVE_RIDE,
    "trip_id": STRING_OPERATORS,
    "source": STRING_OPERATORS,
}
FIELD_OPERATORS_MAP_FILTER_TRIPS = {
    "filter_type": STRING_OPERATORS,
    "filter_value": STRING_OPERATORS,
}
