BOOKS_DATA = [
    {
        "name": "Lidia's Italian-American Kitchen",
        "desc": 'Focusing on the Italian-American kitchen--the cooking she encountered when she first came to America as a young adolescent--Lidia pays homage to this "cuisine of adaptation born of necessity." But she transforms it subtly with her light, discriminating touch, using the authentic ingredients, not accessible to the early immigrants, which are all so readily available today. The aromatic flavors of fine Italian olive oil, imported Parmigiano-Reggiano and Gorgonzola dolce latte, fresh basil, oregano, and rosemary, sun-sweetened San Marzano tomatoes, prosciutto, and pancetta permeate the dishes she makes in her Italian-American kitchen today. And they will transform for you this time-honored cuisine, as you cook with Lidia, learning from her the many secret, sensuous touches that make her food superlative.',
        "year": 2001,
        "director": "Lidia Matticchio Bastianich",
        "cast": "Tim Robbins, Morgan Freeman, Bob Gunton",
        "duration": 464,
        "trailer_url": "https://www.bookstores.com/books/lidias-italian-american-kitchen/9780375411502",
        "rating": 4.8,
        "price": 12.90,
        "img_file": "9780375411502.jpg",  # <-- archivo local
        "genres": ["Cooking"],
    },
    {
        "name": "Programming Massively Parallel Processors",
        "desc": "Programming Massively Parallel Processors: A Hands-on Approach shows both students and professionals alike the basic concepts of parallel programming and GPU architecture. Concise, intuitive, and practical, it is based on years of road-testing in the authors' own parallel computing courses",
        "year": 2022,
        "director": "Wen-Mei W. Hwu, David B. Kirk, Izzat El Hajj",
        "cast": "Marlon Brando, Al Pacino, James Caan",
        "duration": 580,
        "trailer_url": "https://www.bookstores.com/books/programming-massively-parallel-processors/9780323912310",
        "rating": 4.7,
        "price": 79.84,
        "img_file": "9780323912310.jpg",
        "genres": ["Education"],
    },
    {
        "name": "Elementary Statistics",
        "desc": "Simplifies statistics through practice and real-world applications Elementary Statistics: Picturing the World makes statistics approachable with stepped-out instruction, extensive real-life examples and exercises, and a design that fits content for each page to make the material more digestible. The text's combination of theory, pedagogy, and design helps students understand concepts and use statistics to describe and think about the world. ",
        "year": 2018,
        "director": "Ron Larson, Betsy Farber",
        "cast": "Christian Bale, Heath Ledger, Aaron Eckhart",
        "duration": 704,
        "trailer_url": "https://www.bookstores.com/books/elementary-statistics-ron-larson/9780134683416",
        "rating": 4.7,
        "price": 98.47,
        "img_file": "9780134683416.jpg",
        "genres": ["Science", "Education"],
    },
    {
        "name": "Dark Nights: Metal: Dark Knights Rising",
        "desc": "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
        "year": 2019,
        "director": "Grant Morrison, Scott Snyder, Peter J. Tomasi, Francis Manapul (Illustrator)",
        "cast": "John Travolta, Uma Thurman, Samuel L. Jackson",
        "duration": 216,
        "trailer_url": "https://www.bookstores.com/books/dark-nights-metal-dark-knights-rising/9781401289072",
        "rating": 4.6,
        "price": 14.55,
        "img_file": "9781401289072.jpg",
        "genres": ["Story"],
    },
    {
        "name": "Case Files Family Medicine 5th Edition",
        "desc": "Publisher's Note: Products purchased from Third Party sellers are not guaranteed by the publisher for quality, authenticity, or access to any online entitlements included with the product.",
        "year": 2020,
        "director": "Eugene C. Toy, Donald Briscoe, Bruce S. Britton, Joel John Heidelbaugh",
        "cast": "Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen Page",
        "duration": 752,
        "trailer_url": "https://www.bookstores.com/books/case-files-family-medicine-5th-edition-eugene-c-toy/9781260468595",
        "rating": 4.5,
        "price": 44.00,
        "img_file": "9781260468595.jpg",
        "genres": ["Culture"],
    },
    {
        "name": "A Breath of Snow and Ashes",
        "desc": "The large scope of the novel allows Gabaldon to do what she does best, paint in exquisite detail the lives of her characters.",
        "year": 2005,
        "director": "Diana Gabaldon",
        "cast": "Elijah Wood, Ian McKellen, Orlando Bloom",
        "duration": 992,
        "trailer_url": "https://www.bookstores.com/books/a-breath-of-snow-and-ashes-diana-gabaldon/9780385324168",
        "rating": 4.6,
        "price": 7.47,
        "img_file": "9780385324168.jpg",
        "genres": ["Magazine"],
    },
    {
        "name": "Ettinger's Textbook of Veterinary Internal Medicine",
        "desc": "Now Ettinger's trusted, all-in-one veterinary resource is even better! Trusted by small animal veterinarians for more than 50 years, Ettinger's Textbook of Veterinary Internal Medicine adds new content on the field's leading issues and trends to its unmatched, \"gold standard\" coverage of the diagnosis and treatment of medical problems of dogs and cats. Coverage begins with the basics of veterinary medicine, followed by sections on differential diagnosis for chief complaints and for clinicopathologic abnormalities, and continues with techniques, minimally invasive interventional therapies, critical care, toxicology, diseases by body system, and comorbidities.",
        "year": 2024,
        "director": "Stephen J. Ettinger (Editor), Edward C. Feldman (Editor), Etienne Cote (Editor)",
        "cast": "Tom Hanks, Robin Wright, Gary Sinise",
        "duration": 2448,
        "trailer_url": "https://www.bookstores.com/books/ettingers-textbook-of-veterinary-internal-medicine/9780323779319",
        "rating": 4.6,
        "price": 207.02,
        "img_file": "9780323779319.jpg",
        "genres": ["Romance"],
    },
    {
        "name": "Art of Computer Programming, the, Volumes 1-4B, Boxed Set",
        "desc": 'Countless readers have spoken about the profound personal influence of Knuth\'s work. Scientists have marveled at the beauty and elegance of his analysis, while ordinary programmers have successfully applied his "cookbook" solutions to their day-to-day problems. All have admired Knuth for the breadth, clarity, accuracy, and good humor found in his books.',
        "year": 2022,
        "director": "Donald Knuth",
        "cast": "Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss",
        "duration": 736,
        "trailer_url": "https://www.bookstores.com/books/art-of-computer-programming-the-volumes-1-4b-boxed-set/9780137935109",
        "rating": 4.5,
        "price": 239.92,
        "img_file": "9780137935109.jpg",
        "genres": ["Education", "Science"],
    },
    {
        "name": "Fourth Wing",
        "desc": "A #1 New York Times bestseller * Optioned for TV by Amazon Studios * Amazon Best Books of the Year, #4 * Apple Best Books of the Year 2023 * Barnes & Noble Best Fantasy Book of 2023 * NPR \"Books We Love\" 2023 * Audible Best Books of 2023 * Hudson Book of the Year * Google Play Best Books of 2023 * Indigo Best Books of 2023 * Waterstones Book of the Year finalist * Goodreads Choice Award, semi-finalist * Newsweek Staffers' Favorite Books of 2023 * Paste Magazine's Best Books of 2023.",
        "year": 2023,
        "director": "Rebecca Yarros",
        "cast": "Robert De Niro, Ray Liotta, Joe Pesci",
        "duration": 528,
        "trailer_url": "https://www.bookstores.com/books/fourth-wing-rebecca-yarros/9781649374042",
        "rating": 4.6,
        "price": 23.47,
        "img_file": "9781649374042.jpg",
        "genres": ["Education", "Science"],
    },
    {
        "name": "The Housemaid Is Watching",
        "desc": "A twisting, pulse-pounding thriller from Freida McFadden, the New York Times bestselling author of The Housemaid and The Coworker.",
        "year": 2024,
        "director": "Freida McFadden",
        "cast": "Matthew McConaughey, Anne Hathaway, Jessica Chastain",
        "duration": 400,
        "price": 15.35,
        "trailer_url": "https://www.bookstores.com/books/the-housemaid-is-watching-freida-mcfadden/9781464221132",
        "rating": 4.5,
        "img_file": "9781464221132.jpg",
        "genres": ["Education", "Science"],
    },
]
from ..shared_data import CONTAINS, EQUALS, NOT_CONTAINS, NOT_EQUALS

FIELD_OPERATORS_MAP_ADD_COMMENT = {
    "book_name": [EQUALS, NOT_EQUALS, CONTAINS, NOT_CONTAINS],
    "commenter_name": [EQUALS, NOT_EQUALS, CONTAINS, NOT_CONTAINS],
    "content": [EQUALS, NOT_EQUALS, CONTAINS, NOT_CONTAINS],
}
