from ..operators import CONTAINS, EQUALS, GREATER_EQUAL, GREATER_THAN, LESS_EQUAL, LESS_THAN, NOT_CONTAINS, NOT_EQUALS

PRODUCTS_DATA = [
    {
        "id": "kitchen-1",
        "title": "Espresso Machine",
        "price": "$160.00",
        "description": "Professional-grade espresso machine with steam wand and programmable settings.",
        "category": "Kitchen",
        "rating": 4.5,
        "brand": "BrewMaster",
    },
    {
        "id": "kitchen-2",
        "title": "Air Fryer",
        "price": "$89.99",
        "description": "4.2L capacity air fryer with digital touchscreen and 8 preset cooking functions.",
        "category": "Kitchen",
        "rating": 4.7,
        "brand": "ChefPlus",
    },
    {
        "id": "kitchen-3",
        "title": "Stainless Steel Cookware Set",
        "price": "$129.95",
        "description": "10-piece stainless steel cookware set with induction-compatible bases.",
        "category": "Kitchen",
        "rating": 4.6,
        "brand": "CuisinePro",
    },
    {
        "id": "kitchen-4",
        "title": "Kettles",
        "price": "$75.50",
        "description": "1200W electric kettles with fast boiling, temperature control, and auto shut-off for safety.",
        "category": "Kitchen",
        "rating": 4.4,
        "brand": "BlendTech",
    },
    {
        "id": "kitchen-5",
        "title": "Electric Kettle",
        "price": "$32.99",
        "description": "1.7L rapid boil kettle with auto shut-off and boil-dry protection.",
        "category": "Kitchen",
        "rating": 4.3,
        "brand": "KitchenAid",
    },
    {
        "id": "kitchen-6",
        "title": "Food Processor",
        "price": "$112.00",
        "description": "12-cup capacity food processor with 6 interchangeable blades and discs.",
        "category": "Kitchen",
        "rating": 4.5,
        "brand": "Cuisinart",
    },
    {
        "id": "kitchen-7",
        "title": "Stand Mixer",
        "price": "$249.99",
        "description": "5-quart stand mixer with 10-speed settings and included attachments.",
        "category": "Kitchen",
        "rating": 4.8,
        "brand": "KitchenAid",
    },
    {
        "id": "kitchen-8",
        "title": "Slow Cooker",
        "price": "$45.75",
        "description": "6-quart programmable slow cooker with digital timer and keep-warm function.",
        "category": "Kitchen",
        "rating": 4.4,
        "brand": "Crock-Pot",
    },
    {
        "id": "kitchen-9",
        "title": "Rice Cooker",
        "price": "$39.99",
        "description": "5-cup rice cooker with steamer basket and automatic keep-warm function.",
        "category": "Kitchen",
        "rating": 4.2,
        "brand": "Aroma",
    },
    {
        "id": "kitchen-10",
        "title": "Immersion Blender",
        "price": "$59.95",
        "description": "300W immersion blender with 2-speed control and stainless steel blades.",
        "category": "Kitchen",
        "rating": 4.3,
        "brand": "Braun",
    },
    {
        "id": "tech-1",
        "title": "Wireless Earbuds",
        "price": "$129.99",
        "description": "True wireless earbuds with active noise cancellation and 24-hour battery life.",
        "category": "Electronics",
        "rating": 4.7,
        "brand": "SoundCore",
    },
    {
        "id": "tech-2",
        "title": "Smart Watch",
        "price": "$199.00",
        "description": "Fitness tracker with heart rate monitor, GPS, and 7-day battery life.",
        "category": "Electronics",
        "rating": 4.6,
        "brand": "FitTech",
    },
    {
        "id": "tech-3",
        "title": "4K Smart TV",
        "price": "$499.99",
        "description": "55-inch 4K UHD smart TV with HDR and built-in streaming apps.",
        "category": "Electronics",
        "rating": 4.8,
        "brand": "Sony",
    },
    {
        "id": "tech-4",
        "title": "Gaming Laptop",
        "price": "$1,299.00",
        "description": "15.6-inch gaming laptop with RTX 3060 graphics and 144Hz display.",
        "category": "Electronics",
        "rating": 4.9,
        "brand": "ROG",
    },
    {
        "id": "tech-5",
        "title": "Wireless Router",
        "price": "$89.95",
        "description": "Wi-Fi 6 router with dual-band and mesh network compatibility.",
        "category": "Electronics",
        "rating": 4.5,
        "brand": "NetLink",
    },
    {
        "id": "tech-6",
        "title": "Bluetooth Speaker",
        "price": "$79.99",
        "description": "Waterproof portable speaker with 20-hour playtime and deep bass.",
        "category": "Electronics",
        "rating": 4.6,
        "brand": "JBL",
    },
    {
        "id": "tech-7",
        "title": "Tablet",
        "price": "$329.00",
        "description": "10.2-inch tablet with 64GB storage and stylus support.",
        "category": "Electronics",
        "rating": 4.4,
        "brand": "Apple",
    },
    {
        "id": "tech-8",
        "title": "Noise Cancelling Headphones",
        "price": "$179.95",
        "description": "Over-ear headphones with 30-hour battery life and built-in mic.",
        "category": "Electronics",
        "rating": 4.7,
        "brand": "Bose",
    },
    {
        "id": "tech-9",
        "title": "External SSD",
        "price": "$129.00",
        "description": "1TB portable SSD with USB-C and 1050MB/s read speeds.",
        "category": "Electronics",
        "rating": 4.8,
        "brand": "Samsung",
    },
    {
        "id": "tech-10",
        "title": "Smart Thermostat",
        "price": "$149.99",
        "description": "Learning thermostat that adapts to your schedule and saves energy.",
        "category": "Electronics",
        "rating": 4.6,
        "brand": "Nest",
    },
    {
        "id": "home-1",
        "title": "Memory Foam Mattress",
        "price": "$399.00",
        "description": "10-inch gel memory foam mattress with cooling technology.",
        "category": "Home",
        "rating": 4.7,
        "brand": "SleepWell",
    },
    {
        "id": "home-2",
        "title": "Sectional Sofa",
        "price": "$899.99",
        "description": "L-shaped sectional sofa with reversible chaise and stain-resistant fabric.",
        "category": "Home",
        "rating": 4.5,
        "brand": "FurniComfort",
    },
    {
        "id": "home-3",
        "title": "Coffee Table",
        "price": "$149.95",
        "description": "Modern coffee table with tempered glass top and metal frame.",
        "category": "Home",
        "rating": 4.3,
        "brand": "ModLiving",
    },
    {
        "id": "home-4",
        "title": "Dining Table Set",
        "price": "$599.00",
        "description": "5-piece dining set with extendable table and 4 upholstered chairs.",
        "category": "Home",
        "rating": 4.6,
        "brand": "HomeStyle",
    },
    {
        "id": "home-5",
        "title": "Bookshelf",
        "price": "$79.99",
        "description": "5-tier wooden bookshelf with adjustable shelves.",
        "category": "Home",
        "rating": 4.2,
        "brand": "FurniComfort",
    },
    {
        "id": "home-6",
        "title": "Area Rug",
        "price": "$129.95",
        "description": "5'x7' plush area rug with non-slip backing.",
        "category": "Home",
        "rating": 4.4,
        "brand": "RugVista",
    },
    {
        "id": "home-7",
        "title": "Blackout Curtains",
        "price": "$39.99",
        "description": "Thermal insulated blackout curtains with noise reduction.",
        "category": "Home",
        "rating": 4.5,
        "brand": "HomeStyle",
    },
    {
        "id": "home-8",
        "title": "Desk Lamp",
        "price": "$29.95",
        "description": "LED desk lamp with adjustable brightness and color temperature.",
        "category": "Home",
        "rating": 4.3,
        "brand": "BrightTech",
    },
    {
        "id": "home-9",
        "title": "Wall Mirror",
        "price": "$59.00",
        "description": "Round wall mirror with rustic wooden frame.",
        "category": "Home",
        "rating": 4.4,
        "brand": "ModLiving",
    },
    {
        "id": "home-10",
        "title": "Throw Pillow Set",
        "price": "$24.99",
        "description": "Set of 2 decorative throw pillows with removable covers.",
        "category": "Home",
        "rating": 4.2,
        "brand": "CozyHome",
    },
    {
        "id": "fitness-3",
        "title": "Resistance Bands",
        "price": "$19.99",
        "description": "5-piece set of latex resistance bands with handles.",
        "category": "Fitness",
        "rating": 4.5,
        "brand": "TheraBand",
    },
    {
        "id": "fitness-4",
        "title": "Foam Roller",
        "price": "$24.95",
        "description": "High-density foam roller for muscle recovery.",
        "category": "Fitness",
        "rating": 4.4,
        "brand": "TriggerPoint",
    },
    {
        "id": "fitness-5",
        "title": "Jump Rope",
        "price": "$12.99",
        "description": "Adjustable speed jump rope with ball bearings.",
        "category": "Fitness",
        "rating": 4.3,
        "brand": "CrossRope",
    },
    {
        "id": "fitness-6",
        "title": "Smart Scale",
        "price": "$49.95",
        "description": "Bluetooth body composition scale with 13 metrics.",
        "category": "Fitness",
        "rating": 4.5,
        "brand": "Withings",
    },
    {
        "id": "fitness-7",
        "title": "Running Shoes",
        "price": "$89.99",
        "description": "Lightweight running shoes with responsive cushioning.",
        "category": "Fitness",
        "rating": 4.7,
        "brand": "Nike",
    },
    {
        "id": "fitness-8",
        "title": "Water Bottle",
        "price": "$19.95",
        "description": "32oz insulated stainless steel water bottle.",
        "category": "Fitness",
        "rating": 4.6,
        "brand": "HydroFlask",
    },
    {
        "id": "fitness-9",
        "title": "Massage Gun",
        "price": "$129.00",
        "description": "Deep tissue percussion massage gun with 5 attachments.",
        "category": "Fitness",
        "rating": 4.8,
        "brand": "Theragun",
    },
    {
        "id": "fitness-10",
        "title": "Yoga Block",
        "price": "$14.99",
        "description": "High-density EVA foam yoga block for support and alignment.",
        "category": "Fitness",
        "rating": 4.4,
        "brand": "Gaiam",
    },
    {
        "id": "tech-11",
        "title": "Drone with 4K Camera",
        "price": "$349.00",
        "description": "Foldable drone with GPS stabilization, 4K camera, and 25-minute flight time. Includes carrying case and extra batteries.",
        "category": "Technology",
        "rating": 4.6,
        "brand": "SkyEye",
    },
    {
        "id": "tech-18",
        "title": "Portable Bluetooth Speaker",
        "price": "$59.99",
        "description": "Compact waterproof speaker with 360° sound, deep bass, and 15-hour battery life. Perfect for outdoor use.",
        "category": "Technology",
        "rating": 4.4,
        "brand": "PulseBoom",
    },
    {
        "id": "tech-12",
        "title": "Wireless Charging Pad",
        "price": "$29.95",
        "description": "Fast wireless charger with 10W output, anti-slip base, and sleek aluminum finish. Compatible with all Qi devices.",
        "category": "Technology",
        "rating": 4.2,
        "brand": "ChargeMate",
    },
    {
        "id": "tech-13",
        "title": "VR Headset",
        "price": "$429.00",
        "description": "Standalone VR headset with inside-out tracking, immersive display, and access to a wide library of games and apps.",
        "category": "Technology",
        "rating": 4.7,
        "brand": "VisionX",
    },
    {
        "id": "tech-14",
        "title": "Laptop Stand",
        "price": "$42.00",
        "description": "Adjustable aluminum stand improves posture and cooling. Compatible with laptops from 11'' to 17''.",
        "category": "Technology",
        "rating": 4.5,
        "brand": "ErgoDesk",
    },
    {
        "id": "tech-15",
        "title": "Dual Monitor Arm",
        "price": "$79.99",
        "description": "Gas-spring dual arm mount supports up to 32'' displays. Full tilt, swivel, and rotation for ergonomic viewing.",
        "category": "Technology",
        "rating": 4.6,
        "brand": "Mountify",
    },
]


FIELD_OPERATORS_MAP_PRODUCTS = {
    "title": [EQUALS, NOT_EQUALS, CONTAINS, NOT_CONTAINS],
    "brand": [EQUALS, NOT_EQUALS, CONTAINS, NOT_CONTAINS],
    "category": [EQUALS, NOT_EQUALS, CONTAINS, NOT_CONTAINS],
    "rating": [EQUALS, NOT_EQUALS, GREATER_THAN, LESS_THAN, GREATER_EQUAL, LESS_EQUAL],
    "price": [EQUALS, NOT_EQUALS, GREATER_THAN, LESS_THAN, GREATER_EQUAL, LESS_EQUAL],
}
