from copy import deepcopy
from datetime import datetime

EMAILS_DATA = [
    {
        "id": "email1",
        "from": {
            "name": "Alice Smith",
            "email": "alice.smith@company.com",
            "avatar": "https://example.com/avatars/alice.jpg",
        },
        "to": [{"name": "Me", "email": "me@gmail.com"}],
        "subject": "Project Kickoff Meeting",
        "body": "Dear Me,\n\nLooking forward to our project kickoff meeting next week. Please review the attached agenda.\n\nBest,\nAlice",
        "snippet": "Looking forward to our project kickoff meeting next week...",
        "timestamp": datetime(2025, 7, 8, 10, 0, 0),
        "isRead": True,
        "isStarred": False,
        "isSnoozed": False,
        "isDraft": False,
        "isImportant": True,
        "labels": [{"id": "work", "name": "Work", "color": "#4285f4", "type": "user"}],
        "category": "primary",
        "threadId": "thread1",
        "attachments": [
            {
                "id": "attach1",
                "name": "agenda.pdf",
                "size": 1048576,
                "type": "application/pdf",
                "url": "https://example.com/agenda.pdf",
            }
        ],
    },
    {
        "id": "email2",
        "from": {
            "name": "Bob Johnson",
            "email": "bob.johnson@tech.org",
            "avatar": "https://example.com/avatars/bob.jpg",
        },
        "to": [{"name": "Me", "email": "me@gmail.com"}],
        "subject": "Lunch Plans",
        "body": "Hey,\n\nWant to grab lunch this Friday? Let me know what works for you!\n\nCheers,\nBob",
        "snippet": "Want to grab lunch this Friday?...",
        "timestamp": datetime(2025, 7, 7, 12, 30, 0),
        "isRead": False,
        "isStarred": True,
        "isSnoozed": False,
        "isDraft": False,
        "isImportant": False,
        "labels": [{"id": "personal", "name": "Personal", "color": "#0f9d58", "type": "user"}],
        "category": "social",
        "threadId": "thread2",
        "attachments": [],
    },
    {
        "id": "email3",
        "from": {"name": "Carol White", "email": "carol.white@outlook.com"},
        "to": [{"name": "Me", "email": "me@gmail.com"}],
        "subject": "Newsletter Subscription",
        "body": "Dear Me,\n\nThank you for subscribing to our newsletter! Here are the latest updates.\n\nBest,\nCarol",
        "snippet": "Thank you for subscribing to our newsletter!...",
        "timestamp": datetime(2025, 7, 6, 9, 15, 0),
        "isRead": True,
        "isStarred": False,
        "isSnoozed": False,
        "isDraft": False,
        "isImportant": False,
        "labels": [],
        "category": "promotions",
        "threadId": "thread3",
        "attachments": [],
    },
    {
        "id": "email4",
        "from": {"name": "David Brown", "email": "david.brown@company.com"},
        "to": [{"name": "Me", "email": "me@gmail.com"}],
        "subject": "Q2 Report Feedback",
        "body": "Hi,\n\nPlease review the Q2 report and share your feedback by EOD.\n\nThanks,\nDavid",
        "snippet": "Please review the Q2 report and share your feedback...",
        "timestamp": datetime(2025, 7, 5, 14, 20, 0),
        "isRead": False,
        "isStarred": False,
        "isSnoozed": True,
        "isDraft": False,
        "isImportant": True,
        "labels": [{"id": "work", "name": "Work", "color": "#4285f4", "type": "user"}],
        "category": "primary",
        "threadId": "thread4",
        "attachments": [],
    },
    {
        "id": "email5",
        "from": {"name": "Emma Davis", "email": "emma.davis@yahoo.com"},
        "to": [{"name": "Me", "email": "me@gmail.com"}],
        "subject": "Community Forum Update",
        "body": "Hello,\n\nThere's a new reply to your post in the community forum.\n\nRegards,\nEmma",
        "snippet": "There's a new reply to your post in the community forum...",
        "timestamp": datetime(2025, 7, 4, 11, 45, 0),
        "isRead": True,
        "isStarred": False,
        "isSnoozed": False,
        "isDraft": False,
        "isImportant": False,
        "labels": [],
        "category": "forums",
        "threadId": "thread5",
        "attachments": [],
    },
    {
        "id": "email6",
        "from": {"name": "Frank Wilson", "email": "frank.wilson@startup.io"},
        "to": [{"name": "Me", "email": "me@gmail.com"}],
        "subject": "Support Ticket #1234",
        "body": "Dear Me,\n\nYour support ticket has been resolved. Please let us know if you need further assistance.\n\nBest,\nFrank",
        "snippet": "Your support ticket has been resolved...",
        "timestamp": datetime(2025, 7, 3, 16, 0, 0),
        "isRead": True,
        "isStarred": False,
        "isSnoozed": False,
        "isDraft": False,
        "isImportant": False,
        "labels": [],
        "category": "support",
        "threadId": "thread6",
        "attachments": [],
    },
    {
        "id": "email7",
        "from": {"name": "Grace Lee", "email": "grace.lee@company.com"},
        "to": [{"name": "Me", "email": "me@gmail.com"}],
        "subject": "Team Outing Plan",
        "body": "Hi,\n\nWe're planning a team outing next month. Please share your availability.\n\nThanks,\nGrace",
        "snippet": "We're planning a team outing next month...",
        "timestamp": datetime(2025, 7, 2, 13, 10, 0),
        "isRead": False,
        "isStarred": True,
        "isSnoozed": False,
        "isDraft": False,
        "isImportant": False,
        "labels": [{"id": "work", "name": "Work", "color": "#4285f4", "type": "user"}],
        "category": "primary",
        "threadId": "thread7",
        "attachments": [],
    },
    {
        "id": "email8",
        "from": {"name": "Henry Moore", "email": "henry.moore@tech.org"},
        "to": [{"name": "Me", "email": "me@gmail.com"}],
        "subject": "Exclusive Offer: 20% Off",
        "body": "Dear Customer,\n\nEnjoy 20% off your next purchase with code SAVE20.\n\nBest,\nHenry",
        "snippet": "Enjoy 20% off your next purchase with code SAVE20...",
        "timestamp": datetime(2025, 7, 1, 8, 50, 0),
        "isRead": True,
        "isStarred": False,
        "isSnoozed": False,
        "isDraft": False,
        "isImportant": False,
        "labels": [],
        "category": "promotions",
        "threadId": "thread8",
        "attachments": [],
    },
    {
        "id": "email21",
        "from": {
            "name": "Grace Thompson",
            "email": "grace.thompson@org.com",
            "avatar": "https://example.com/avatars/grace.jpg",
        },
        "to": [{"name": "Me", "email": "me@gmail.com"}],
        "subject": "Project Status Update",
        "body": "Dear Me,\n\nThe project is on track. Please review the attached status report.\n\nBest,\nGrace",
        "snippet": "The project is on track...",
        "timestamp": datetime(2025, 7, 8, 9, 0, 0),
        "isRead": False,
        "isStarred": False,
        "isSnoozed": False,
        "isDraft": False,
        "isImportant": True,
        "labels": [{"id": "work", "name": "Work", "color": "#4285f4", "type": "user"}],
        "category": "primary",
        "threadId": "thread21",
        "attachments": [
            {
                "id": "attach21",
                "name": "status_report.pdf",
                "size": 1048576,
                "type": "application/pdf",
                "url": "https://example.com/status_report.pdf",
            },
        ],
    },
    {
        "id": "email22",
        "from": {
            "name": "Isaac Hayes",
            "email": "isaac.hayes@org.com",
            "avatar": "https://example.com/avatars/isaac.jpg",
        },
        "to": [{"name": "Me", "email": "me@gmail.com"}],
        "subject": "Special Discount: 15% Off",
        "body": "Dear Customer,\n\nUse code DISCOUNT15 for 15% off your next order!\n\nCheers,\nIsaac",
        "snippet": "Use code DISCOUNT15 for 15% off...",
        "timestamp": datetime(2025, 7, 8, 10, 15, 0),
        "isRead": True,
        "isStarred": False,
        "isSnoozed": False,
        "isDraft": False,
        "isImportant": False,
        "labels": [],
        "category": "promotions",
        "threadId": "thread22",
        "attachments": [],
    },
    {
        "id": "email23",
        "from": {
            "name": "Julia Bennett",
            "email": "julia.bennett@org.com",
            "avatar": "https://example.com/avatars/julia.jpg",
        },
        "to": [{"name": "Me", "email": "me@gmail.com"}],
        "subject": "Team Sync Tomorrow",
        "body": "Hi Me,\n\nJoin us for the team sync tomorrow at 11 AM.\n\nBest,\nJulia",
        "snippet": "Join us for the team sync tomorrow...",
        "timestamp": datetime(2025, 7, 8, 11, 30, 0),
        "isRead": True,
        "isStarred": True,
        "isSnoozed": False,
        "isDraft": False,
        "isImportant": True,
        "labels": [{"id": "team", "name": "Team", "color": "#ff5722", "type": "user"}],
        "category": "primary",
        "threadId": "thread23",
        "attachments": [],
    },
    {
        "id": "email24",
        "from": {
            "name": "Nathan Cole",
            "email": "nathan.cole@org.com",
            "avatar": "https://example.com/avatars/nathan.jpg",
        },
        "to": [{"name": "Me", "email": "me@gmail.com"}],
        "subject": "Lunch Invite",
        "body": "Hey Me,\n\nFree for lunch this Thursday? Let me know!\n\nCheers,\nNathan",
        "snippet": "Free for lunch this Thursday...",
        "timestamp": datetime(2025, 7, 8, 12, 45, 0),
        "isRead": True,
        "isStarred": False,
        "isSnoozed": False,
        "isDraft": False,
        "isImportant": False,
        "labels": [{"id": "personal", "name": "Personal", "color": "#9c27b0", "type": "user"}],
        "category": "social",
        "threadId": "thread24",
        "attachments": [],
    },
    {
        "id": "email25",
        "from": {
            "name": "Violet Foster",
            "email": "violet.foster@org.com",
            "avatar": "https://example.com/avatars/violet.jpg",
        },
        "to": [{"name": "Me", "email": "me@gmail.com"}],
        "subject": "Client Proposal Review",
        "body": "Dear Me,\n\nPlease review the attached client proposal by EOD.\n\nBest,\nViolet",
        "snippet": "Please review the attached client proposal...",
        "timestamp": datetime(2025, 7, 8, 14, 0, 0),
        "isRead": False,
        "isStarred": False,
        "isSnoozed": False,
        "isDraft": False,
        "isImportant": True,
        "labels": [{"id": "client", "name": "Client", "color": "#4caf50", "type": "user"}],
        "category": "primary",
        "threadId": "thread25",
        "attachments": [
            {
                "id": "attach22",
                "name": "proposal_v2.docx",
                "size": 524288,
                "type": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
                "url": "https://example.com/proposal_v2.docx",
            }
        ],
    },
    {
        "id": "email26",
        "from": {
            "name": "Elliot Ward",
            "email": "elliot.ward@org.com",
            "avatar": "https://example.com/avatars/elliot.jpg",
        },
        "to": [{"name": "Me", "email": "me@gmail.com"}],
        "subject": "Software Update Notice",
        "body": "Hi Me,\n\nA software update is scheduled for this weekend. Details attached.\n\nThanks,\nElliot",
        "snippet": "A software update is scheduled for this weekend...",
        "timestamp": datetime(2025, 7, 8, 15, 15, 0),
        "isRead": False,
        "isStarred": True,
        "isSnoozed": False,
        "isDraft": False,
        "isImportant": True,
        "labels": [{"id": "tech", "name": "Tech", "color": "#2196f3", "type": "user"}],
        "category": "primary",
        "threadId": "thread26",
        "attachments": [
            {
                "id": "attach23",
                "name": "update_notes.pdf",
                "size": 786432,
                "type": "application/pdf",
                "url": "https://example.com/update_notes.pdf",
            }
        ],
    },
    {
        "id": "email27",
        "from": {
            "name": "Lila Morgan",
            "email": "lila.morgan@org.com",
            "avatar": "https://example.com/avatars/lila.jpg",
        },
        "to": [{"name": "Me", "email": "me@gmail.com"}],
        "subject": "Team Outing RSVP",
        "body": "Hey Me,\n\nPlease RSVP for the team outing next Friday.\n\nCheers,\nLila",
        "snippet": "Please RSVP for the team outing next Friday...",
        "timestamp": datetime(2025, 7, 8, 16, 30, 0),
        "isRead": True,
        "isStarred": False,
        "isSnoozed": False,
        "isDraft": False,
        "isImportant": False,
        "labels": [{"id": "team", "name": "Team", "color": "#ff5722", "type": "user"}],
        "category": "social",
        "threadId": "thread27",
        "attachments": [],
    },
    {
        "id": "email28",
        "from": {
            "name": "Caleb Reed",
            "email": "caleb.reed@org.com",
            "avatar": "https://example.com/avatars/caleb.jpg",
        },
        "to": [{"name": "Me", "email": "me@gmail.com"}],
        "subject": "Invoice for Review",
        "body": "Dear Me,\n\nPlease review and approve the attached invoice.\n\nBest,\nCaleb",
        "snippet": "Please review and approve the attached invoice...",
        "timestamp": datetime(2025, 7, 8, 17, 45, 0),
        "isRead": False,
        "isStarred": False,
        "isSnoozed": False,
        "isDraft": False,
        "isImportant": True,
        "labels": [{"id": "finance", "name": "Finance", "color": "#ffeb3b", "type": "user"}],
        "category": "primary",
        "threadId": "thread28",
        "attachments": [
            {
                "id": "attach24",
                "name": "invoice_456.pdf",
                "size": 1048576,
                "type": "application/pdf",
                "url": "https://example.com/invoice_456.pdf",
            }
        ],
    },
    {
        "id": "email29",
        "from": {
            "name": "Nora Fisher",
            "email": "nora.fisher@org.com",
            "avatar": "https://example.com/avatars/nora.jpg",
        },
        "to": [{"name": "Me", "email": "me@gmail.com"}],
        "subject": "Newsletter Subscription",
        "body": "Dear Customer,\n\nThank you for subscribing to our newsletter! First issue attached.\n\nBest,\nNora",
        "snippet": "Thank you for subscribing to our newsletter...",
        "timestamp": datetime(2025, 7, 8, 19, 0, 0),
        "isRead": True,
        "isStarred": False,
        "isSnoozed": False,
        "isDraft": False,
        "isImportant": False,
        "labels": [],
        "category": "promotions",
        "threadId": "thread29",
        "attachments": [
            {
                "id": "attach25",
                "name": "newsletter_july.pdf",
                "size": 1572864,
                "type": "application/pdf",
                "url": "https://example.com/newsletter_july.pdf",
            }
        ],
    },
    {
        "id": "email30",
        "from": {
            "name": "Owen Myers",
            "email": "owen.myers@org.com",
            "avatar": "https://example.com/avatars/owen.jpg",
        },
        "to": [{"name": "Me", "email": "me@gmail.com"}],
        "subject": "Sprint Review Invite",
        "body": "Hi Me,\n\nJoin us for the sprint review on Wednesday at 2 PM.\n\nBest,\nOwen",
        "snippet": "Join us for the sprint review on Wednesday...",
        "timestamp": datetime(2025, 7, 8, 20, 15, 0),
        "isRead": False,
        "isStarred": False,
        "isSnoozed": False,
        "isDraft": False,
        "isImportant": True,
        "labels": [{"id": "dev", "name": "Development", "color": "#3f51b5", "type": "user"}],
        "category": "primary",
        "threadId": "thread30",
        "attachments": [],
    },
    {
        "id": "email31",
        "from": {
            "name": "Ruby Lane",
            "email": "ruby.lane@org.com",
            "avatar": "https://example.com/avatars/ruby.jpg",
        },
        "to": [{"name": "Me", "email": "me@gmail.com"}],
        "subject": "Training Workshop",
        "body": "Dear Me,\n\nYou're invited to a training workshop next Tuesday. Details attached.\n\nBest,\nRuby",
        "snippet": "You're invited to a training workshop next Tuesday...",
        "timestamp": datetime(2025, 7, 8, 21, 30, 0),
        "isRead": True,
        "isStarred": False,
        "isSnoozed": False,
        "isDraft": False,
        "isImportant": False,
        "labels": [{"id": "training", "name": "Training", "color": "#795548", "type": "user"}],
        "category": "updates",
        "threadId": "thread31",
        "attachments": [
            {
                "id": "attach26",
                "name": "workshop_details.pdf",
                "size": 1048576,
                "type": "application/pdf",
                "url": "https://example.com/workshop_details.pdf",
            }
        ],
    },
    {
        "id": "email32",
        "from": {
            "name": "Miles Grant",
            "email": "miles.grant@org.com",
            "avatar": "https://example.com/avatars/miles.jpg",
        },
        "to": [{"name": "Me", "email": "me@gmail.com"}],
        "subject": "Happy Hour This Week",
        "body": "Hey Me,\n\nJoin us for happy hour this Friday at 5 PM!\n\nCheers,\nMiles",
        "snippet": "Join us for happy hour this Friday...",
        "timestamp": datetime(2025, 7, 8, 22, 45, 0),
        "isRead": True,
        "isStarred": False,
        "isSnoozed": False,
        "isDraft": False,
        "isImportant": False,
        "labels": [{"id": "social", "name": "Social", "color": "#673ab7", "type": "user"}],
        "category": "social",
        "threadId": "thread32",
        "attachments": [],
    },
    {
        "id": "email33",
        "from": {
            "name": "Stella Brooks",
            "email": "stella.brooks@org.com",
            "avatar": "https://example.com/avatars/stella.jpg",
        },
        "to": [{"name": "Me", "email": "me@gmail.com"}],
        "subject": "Budget Proposal",
        "body": "Dear Me,\n\nPlease review the Q3 budget proposal attached.\n\nBest,\nStella",
        "snippet": "Please review the Q3 budget proposal...",
        "timestamp": datetime(2025, 7, 9, 7, 0, 0),
        "isRead": False,
        "isStarred": False,
        "isSnoozed": False,
        "isDraft": False,
        "isImportant": True,
        "labels": [{"id": "finance", "name": "Finance", "color": "#ffeb3b", "type": "user"}],
        "category": "primary",
        "threadId": "thread33",
        "attachments": [
            {
                "id": "attach27",
                "name": "budget_q3.xlsx",
                "size": 524288,
                "type": "application/vnd.ms-excel",
                "url": "https://example.com/budget_q3.xlsx",
            }
        ],
    },
    {
        "id": "email34",
        "from": {
            "name": "Finn Harper",
            "email": "finn.harper@org.com",
            "avatar": "https://example.com/avatars/finn.jpg",
        },
        "to": [{"name": "Me", "email": "me@gmail.com"}],
        "subject": "Code Review Request",
        "body": "Hi Me,\n\nCan you review my pull request by tomorrow? Link attached.\n\nThanks,\nFinn",
        "snippet": "Can you review my pull request by tomorrow...",
        "timestamp": datetime(2025, 7, 9, 8, 15, 0),
        "isRead": True,
        "isStarred": True,
        "isSnoozed": False,
        "isDraft": False,
        "isImportant": True,
        "labels": [{"id": "dev", "name": "Development", "color": "#3f51b5", "type": "user"}],
        "category": "primary",
        "threadId": "thread34",
        "attachments": [
            {
                "id": "attach28",
                "name": "pr_link.txt",
                "size": 2048,
                "type": "text/plain",
                "url": "https://example.com/pr_link.txt",
            }
        ],
    },
    {
        "id": "email35",
        "from": {
            "name": "Ivy Chen",
            "email": "ivy.chen@org.com",
            "avatar": "https://example.com/avatars/ivy.jpg",
        },
        "to": [{"name": "Me", "email": "me@gmail.com"}],
        "subject": "Feedback Survey",
        "body": "Dear Me,\n\nPlease complete the feedback survey for our recent event.\n\nBest,\nIvy",
        "snippet": "Please complete the feedback survey...",
        "timestamp": datetime(2025, 7, 9, 9, 30, 0),
        "isRead": True,
        "isStarred": False,
        "isSnoozed": False,
        "isDraft": False,
        "isImportant": False,
        "labels": [{"id": "survey", "name": "Survey", "color": "#cddc39", "type": "user"}],
        "category": "updates",
        "threadId": "thread35",
        "attachments": [],
    },
    {
        "id": "email36",
        "from": {
            "name": "Jasper Lee",
            "email": "jasper.lee@org.com",
            "avatar": "https://example.com/avatars/jasper.jpg",
        },
        "to": [{"name": "Me", "email": "me@gmail.com"}],
        "subject": "Product Launch Plan",
        "body": "Hi Me,\n\nReview the attached product launch plan for next quarter.\n\nBest,\nJasper",
        "snippet": "Review the attached product launch plan...",
        "timestamp": datetime(2025, 7, 9, 10, 45, 0),
        "isRead": False,
        "isStarred": False,
        "isSnoozed": False,
        "isDraft": False,
        "isImportant": True,
        "labels": [{"id": "product", "name": "Product", "color": "#009688", "type": "user"}],
        "category": "primary",
        "threadId": "thread36",
        "attachments": [
            {
                "id": "attach29",
                "name": "launch_plan.pdf",
                "size": 2097152,
                "type": "application/pdf",
                "url": "https://example.com/launch_plan.pdf",
            }
        ],
    },
    {
        "id": "email37",
        "from": {
            "name": "Willow Gray",
            "email": "willow.gray@org.com",
            "avatar": "https://example.com/avatars/willow.jpg",
        },
        "to": [{"name": "Me", "email": "me@gmail.com"}],
        "subject": "Team Brainstorm Session",
        "body": "Hey Me,\n\nJoin us for a brainstorm session on Monday at 3 PM.\n\nCheers,\nWillow",
        "snippet": "Join us for a brainstorm session on Monday...",
        "timestamp": datetime(2025, 7, 9, 12, 0, 0),
        "isRead": True,
        "isStarred": False,
        "isSnoozed": False,
        "isDraft": False,
        "isImportant": False,
        "labels": [{"id": "team", "name": "Team", "color": "#ff5722", "type": "user"}],
        "category": "social",
        "threadId": "thread37",
        "attachments": [],
    },
    {
        "id": "email38",
        "from": {
            "name": "Theo Kim",
            "email": "theo.kim@org.com",
            "avatar": "https://example.com/avatars/theo.jpg",
        },
        "to": [{"name": "Me", "email": "me@gmail.com"}],
        "subject": "Contract Renewal",
        "body": "Dear Me,\n\nPlease review the attached contract renewal terms.\n\nBest,\nTheo",
        "snippet": "Please review the attached contract renewal terms...",
        "timestamp": datetime(2025, 7, 9, 13, 15, 0),
        "isRead": False,
        "isStarred": False,
        "isSnoozed": False,
        "isDraft": False,
        "isImportant": True,
        "labels": [{"id": "legal", "name": "Legal", "color": "#607d8b", "type": "user"}],
        "category": "primary",
        "threadId": "thread38",
        "attachments": [
            {
                "id": "attach30",
                "name": "contract_renewal.pdf",
                "size": 1048576,
                "type": "application/pdf",
                "url": "https://example.com/contract_renewal.pdf",
            }
        ],
    },
    {
        "id": "email39",
        "from": {
            "name": "Esme Carter",
            "email": "esme.carter@org.com",
            "avatar": "https://example.com/avatars/esme.jpg",
        },
        "to": [{"name": "Me", "email": "me@gmail.com"}],
        "subject": "Exclusive Sale: 25% Off",
        "body": "Dear Customer,\n\nGet 25% off with code SALE25 this week only!\n\nBest,\nEsme",
        "snippet": "Get 25% off with code SALE25 this week only...",
        "timestamp": datetime(2025, 7, 9, 14, 30, 0),
        "isRead": True,
        "isStarred": False,
        "isSnoozed": False,
        "isDraft": False,
        "isImportant": False,
        "labels": [],
        "category": "promotions",
        "threadId": "thread39",
        "attachments": [],
    },
    {
        "id": "email40",
        "from": {
            "name": "Silas Nguyen",
            "email": "silas.nguyen@org.com",
            "avatar": "https://example.com/avatars/silas.jpg",
        },
        "to": [{"name": "Me", "email": "me@gmail.com"}],
        "subject": "Feature Request Feedback",
        "body": "Hi Me,\n\nPlease provide feedback on the new feature request attached.\n\nThanks,\nSilas",
        "snippet": "Please provide feedback on the new feature request...",
        "timestamp": datetime(2025, 7, 9, 15, 45, 0),
        "isRead": False,
        "isStarred": True,
        "isSnoozed": False,
        "isDraft": False,
        "isImportant": True,
        "labels": [{"id": "product", "name": "Product", "color": "#009688", "type": "user"}],
        "category": "primary",
        "threadId": "thread40",
        "attachments": [
            {
                "id": "attach31",
                "name": "feature_request.docx",
                "size": 524288,
                "type": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
                "url": "https://example.com/feature_request.docx",
            }
        ],
    },
    {
        "id": "email41",
        "from": {
            "name": "Freya Patel",
            "email": "freya.patel@org.com",
            "avatar": "https://example.com/avatars/freya.jpg",
        },
        "to": [{"name": "Me", "email": "me@gmail.com"}],
        "subject": "Team Meeting Notes",
        "body": "Dear Me,\n\nAttached are the notes from today's team meeting.\n\nBest,\nFreya",
        "snippet": "Attached are the notes from today's team meeting...",
        "timestamp": datetime(2025, 7, 9, 17, 0, 0),
        "isRead": True,
        "isStarred": False,
        "isSnoozed": False,
        "isDraft": False,
        "isImportant": True,
        "labels": [{"id": "team", "name": "Team", "color": "#ff5722", "type": "user"}],
        "category": "primary",
        "threadId": "thread41",
        "attachments": [
            {
                "id": "attach32",
                "name": "meeting_notes.pdf",
                "size": 1048576,
                "type": "application/pdf",
                "url": "https://example.com/meeting_notes.pdf",
            }
        ],
    },
    {
        "id": "email42",
        "from": {
            "name": "Ezra Collins",
            "email": "ezra.collins@org.com",
            "avatar": "https://example.com/avatars/ezra.jpg",
        },
        "to": [{"name": "Me", "email": "me@gmail.com"}],
        "subject": "Vacation Policy Update",
        "body": "Dear Me,\n\nThe updated vacation policy is now available. See attached.\n\nBest,\nEzra",
        "snippet": "The updated vacation policy is now available...",
        "timestamp": datetime(2025, 7, 9, 18, 15, 0),
        "isRead": True,
        "isStarred": False,
        "isSnoozed": False,
        "isDraft": False,
        "isImportant": False,
        "labels": [{"id": "hr", "name": "HR", "color": "#e91e63", "type": "user"}],
        "category": "updates",
        "threadId": "thread42",
        "attachments": [
            {
                "id": "attach33",
                "name": "vacation_policy.pdf",
                "size": 786432,
                "type": "application/pdf",
                "url": "https://example.com/vacation_policy.pdf",
            }
        ],
    },
    {
        "id": "email43",
        "from": {
            "name": "Luna Hayes",
            "email": "luna.hayes@org.com",
            "avatar": "https://example.com/avatars/luna.jpg",
        },
        "to": [{"name": "Me", "email": "me@gmail.com"}],
        "subject": "Coffee Catch-Up",
        "body": "Hey Me,\n\nLet's grab coffee next week. When are you free?\n\nCheers,\nLuna",
        "snippet": "Let's grab coffee next week...",
        "timestamp": datetime(2025, 7, 9, 19, 30, 0),
        "isRead": True,
        "isStarred": False,
        "isSnoozed": False,
        "isDraft": False,
        "isImportant": False,
        "labels": [{"id": "personal", "name": "Personal", "color": "#9c27b0", "type": "user"}],
        "category": "social",
        "threadId": "thread43",
        "attachments": [],
    },
    {
        "id": "email44",
        "from": {
            "name": "Milo Carter",
            "email": "milo.carter@org.com",
            "avatar": "https://example.com/avatars/milo.jpg",
        },
        "to": [{"name": "Me", "email": "me@gmail.com"}],
        "subject": "Q4 Marketing Plan",
        "body": "Dear Me,\n\nPlease review the Q4 marketing plan attached.\n\nBest,\nMilo",
        "snippet": "Please review the Q4 marketing plan...",
        "timestamp": datetime(2025, 7, 9, 20, 45, 0),
        "isRead": False,
        "isStarred": False,
        "isSnoozed": False,
        "isDraft": False,
        "isImportant": True,
        "labels": [{"id": "marketing", "name": "Marketing", "color": "#ff9800", "type": "user"}],
        "category": "primary",
        "threadId": "thread44",
        "attachments": [
            {
                "id": "attach34",
                "name": "marketing_plan_q4.pptx",
                "size": 3145728,
                "type": "application/vnd.ms-powerpoint",
                "url": "https://example.com/marketing_plan_q4.pptx",
            }
        ],
    },
    {
        "id": "email45",
        "from": {
            "name": "Ada Price",
            "email": "ada.price@org.com",
            "avatar": "https://example.com/avatars/ada.jpg",
        },
        "to": [{"name": "Me", "email": "me@gmail.com"}],
        "subject": "Weekly Newsletter",
        "body": "Dear Customer,\n\nCheck out this week's newsletter for updates!\n\nBest,\nAda",
        "snippet": "Check out this week's newsletter for updates...",
        "timestamp": datetime(2025, 7, 9, 22, 0, 0),
        "isRead": True,
        "isStarred": False,
        "isSnoozed": False,
        "isDraft": False,
        "isImportant": False,
        "labels": [],
        "category": "promotions",
        "threadId": "thread45",
        "attachments": [
            {
                "id": "attach35",
                "name": "newsletter_weekly.pdf",
                "size": 1572864,
                "type": "application/pdf",
                "url": "https://example.com/newsletter_weekly.pdf",
            }
        ],
    },
    {
        "id": "email46",
        "from": {
            "name": "Levi Brooks",
            "email": "levi.brooks@org.com",
            "avatar": "https://example.com/avatars/levi.jpg",
        },
        "to": [{"name": "Me", "email": "me@gmail.com"}],
        "subject": "System Upgrade Notice",
        "body": "Dear Me,\n\nA system upgrade is scheduled for this weekend. Details attached.\n\nBest,\nLevi",
        "snippet": "A system upgrade is scheduled for this weekend...",
        "timestamp": datetime(2025, 7, 9, 23, 15, 0),
        "isRead": False,
        "isStarred": False,
        "isSnoozed": False,
        "isDraft": False,
        "isImportant": True,
        "labels": [{"id": "tech", "name": "Tech", "color": "#2196f3", "type": "user"}],
        "category": "primary",
        "threadId": "thread46",
        "attachments": [
            {
                "id": "attach36",
                "name": "upgrade_notice.pdf",
                "size": 786432,
                "type": "application/pdf",
                "url": "https://example.com/upgrade_notice.pdf",
            }
        ],
    },
    {
        "id": "email47",
        "from": {
            "name": "Eliza Ford",
            "email": "eliza.ford@org.com",
            "avatar": "https://example.com/avatars/eliza.jpg",
        },
        "to": [{"name": "Me", "email": "me@gmail.com"}],
        "subject": "Team Feedback Request",
        "body": "Hi Me,\n\nPlease provide feedback on the team's recent work.\n\nThanks,\nEliza",
        "snippet": "Please provide feedback on the team's recent work...",
        "timestamp": datetime(2025, 7, 9, 6, 30, 0),
        "isRead": True,
        "isStarred": False,
        "isSnoozed": False,
        "isDraft": False,
        "isImportant": False,
        "labels": [{"id": "team", "name": "Team", "color": "#ff5722", "type": "user"}],
        "category": "updates",
        "threadId": "thread47",
        "attachments": [],
    },
    {
        "id": "email48",
        "from": {
            "name": "Jude Perry",
            "email": "jude.perry@org.com",
            "avatar": "https://example.com/avatars/jude.jpg",
        },
        "to": [{"name": "Me", "email": "me@gmail.com"}],
        "subject": "Client Meeting Follow-Up",
        "body": "Dear Me,\n\nFollowing up on our client meeting. Notes attached.\n\nBest,\nJude",
        "snippet": "Following up on our client meeting...",
        "timestamp": datetime(2025, 7, 9, 5, 45, 0),
        "isRead": False,
        "isStarred": True,
        "isSnoozed": False,
        "isDraft": False,
        "isImportant": True,
        "labels": [{"id": "client", "name": "Client", "color": "#4caf50", "type": "user"}],
        "category": "primary",
        "threadId": "thread48",
        "attachments": [
            {
                "id": "attach37",
                "name": "client_notes.pdf",
                "size": 1048576,
                "type": "application/pdf",
                "url": "https://example.com/client_notes.pdf",
            }
        ],
    },
    {
        "id": "email49",
        "from": {
            "name": "Rose Evans",
            "email": "rose.evans@org.com",
            "avatar": "https://example.com/avatars/rose.jpg",
        },
        "to": [{"name": "Me", "email": "me@gmail.com"}],
        "subject": "Coffee Break Invite",
        "body": "Hey Me,\n\nLet's have a quick coffee break tomorrow afternoon.\n\nCheers,\nRose",
        "snippet": "Let's have a quick coffee break tomorrow...",
        "timestamp": datetime(2025, 7, 9, 4, 0, 0),
        "isRead": True,
        "isStarred": False,
        "isSnoozed": False,
        "isDraft": False,
        "isImportant": False,
        "labels": [{"id": "personal", "name": "Personal", "color": "#9c27b0", "type": "user"}],
        "category": "social",
        "threadId": "thread49",
        "attachments": [],
    },
    {
        "id": "email50",
        "from": {
            "name": "Asher Gordon",
            "email": "asher.gordon@org.com",
            "avatar": "https://example.com/avatars/asher.jpg",
        },
        "to": [{"name": "Me", "email": "me@gmail.com"}],
        "subject": "Project Timeline Review",
        "body": "Dear Me,\n\nPlease review the updated project timeline attached.\n\nBest,\nAsher",
        "snippet": "Please review the updated project timeline...",
        "timestamp": datetime(2025, 7, 9, 3, 15, 0),
        "isRead": False,
        "isStarred": False,
        "isSnoozed": False,
        "isDraft": False,
        "isImportant": True,
        "labels": [{"id": "project", "name": "Project", "color": "#607d8b", "type": "user"}],
        "category": "primary",
        "threadId": "thread50",
        "attachments": [
            {
                "id": "attach38",
                "name": "timeline_v3.pdf",
                "size": 1572864,
                "type": "application/pdf",
                "url": "https://example.com/timeline_v3.pdf",
            }
        ],
    },
    {
        "id": "email51",
        "from": {
            "name": "Sienna Walsh",
            "email": "sienna.walsh@org.com",
            "avatar": "https://example.com/avatars/sienna.jpg",
        },
        "to": [{"name": "Me", "email": "me@gmail.com"}],
        "subject": "Weekly Team Update",
        "body": "Dear Me,\n\nHere's the weekly team update. Please review the attached slides.\n\nBest,\nSienna",
        "snippet": "Here's the weekly team update...",
        "timestamp": datetime(2025, 7, 9, 9, 0, 0),
        "isRead": False,
        "isStarred": False,
        "isSnoozed": False,
        "isDraft": False,
        "isImportant": True,
        "labels": [{"id": "team", "name": "Team", "color": "#ff5722", "type": "user"}],
        "category": "primary",
        "threadId": "thread51",
        "attachments": [
            {
                "id": "attach39",
                "name": "team_update.pptx",
                "size": 2097152,
                "type": "application/vnd.ms-powerpoint",
                "url": "https://example.com/team_update.pptx",
            }
        ],
    },
    {
        "id": "email52",
        "from": {
            "name": "Declan Fox",
            "email": "declan.fox@org.com",
            "avatar": "https://example.com/avatars/declan.jpg",
        },
        "to": [{"name": "Me", "email": "me@gmail.com"}],
        "subject": "Flash Sale: 30% Off",
        "body": "Dear Customer,\n\nEnjoy 30% off with code FLASH30 today only!\n\nBest,\nDeclan",
        "snippet": "Enjoy 30% off with code FLASH30 today only...",
        "timestamp": datetime(2025, 7, 9, 10, 30, 0),
        "isRead": True,
        "isStarred": False,
        "isSnoozed": False,
        "isDraft": False,
        "isImportant": False,
        "labels": [],
        "category": "promotions",
        "threadId": "thread52",
        "attachments": [],
    },
    {
        "id": "email53",
        "from": {
            "name": "Piper Dunn",
            "email": "piper.dunn@org.com",
            "avatar": "https://example.com/avatars/piper.jpg",
        },
        "to": [{"name": "Me", "email": "me@gmail.com"}],
        "subject": "Sprint Planning Session",
        "body": "Hi Me,\n\nPlease join the sprint planning session tomorrow at 10 AM.\n\nBest,\nPiper",
        "snippet": "Please join the sprint planning session tomorrow...",
        "timestamp": datetime(2025, 7, 9, 10, 0, 0),  # Corrected timestamp for consistency
        "isRead": True,
        "isStarred": True,
        "isSnoozed": False,
        "isDraft": False,
        "isImportant": False,
        "labels": [],  # Assuming no labels for this entry based on the provided snippet
        "category": "primary",  # Assuming primary category
        "threadId": "thread53",  # New thread ID
        "attachments": [],  # No attachments mentioned
    },
    {
        "id": "email54",
        "from": {
            "name": "Roman Bell",
            "email": "roman.bell@org.com",
            "avatar": "https://example.com/avatars/roman.jpg",
        },
        "to": [{"name": "Me", "email": "me@gmail.com"}],
        "subject": "Lunch This Week?",
        "body": "Hey Me,\n\nAre you free for lunch this Friday? Let me know!\n\nCheers,\nRoman",
        "snippet": "Are you free for lunch this Friday...",
        "timestamp": datetime(2025, 7, 9, 13, 0, 0),
        "isRead": True,
        "isStarred": False,
        "isSnoozed": False,
        "isDraft": False,
        "isImportant": False,
        "labels": [{"id": "personal", "name": "Personal", "color": "#9c27b0", "type": "user"}],
        "category": "social",
        "threadId": "thread54",
        "attachments": [],
    },
    {
        "id": "email55",
        "from": {
            "name": "Tessa Quinn",
            "email": "tessa.quinn@org.com",
            "avatar": "https://example.com/avatars/tessa.jpg",
        },
        "to": [{"name": "Me", "email": "me@gmail.com"}],
        "subject": "Client Feedback Review",
        "body": "Dear Me,\n\nPlease review the client feedback attached.\n\nBest,\nTessa",
        "snippet": "Please review the client feedback...",
        "timestamp": datetime(2025, 7, 9, 14, 15, 0),
        "isRead": False,
        "isStarred": False,
        "isSnoozed": False,
        "isDraft": False,
        "isImportant": True,
        "labels": [{"id": "client", "name": "Client", "color": "#4caf50", "type": "user"}],
        "category": "primary",
        "threadId": "thread55",
        "attachments": [
            {
                "id": "attach40",
                "name": "feedback_report.docx",
                "size": 524288,
                "type": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
                "url": "https://example.com/feedback_report.docx",
            }
        ],
    },
    {
        "id": "email56",
        "from": {
            "name": "Gideon Hart",
            "email": "gideon.hart@org.com",
            "avatar": "https://example.com/avatars/gideon.jpg",
        },
        "to": [{"name": "Me", "email": "me@gmail.com"}],
        "subject": "Security Patch Update",
        "body": "Hi Me,\n\nA new security patch is available. Details attached.\n\nThanks,\nGideon",
        "snippet": "A new security patch is available...",
        "timestamp": datetime(2025, 7, 9, 15, 30, 0),
        "isRead": False,
        "isStarred": True,
        "isSnoozed": False,
        "isDraft": False,
        "isImportant": True,
        "labels": [{"id": "tech", "name": "Tech", "color": "#2196f3", "type": "user"}],
        "category": "primary",
        "threadId": "thread56",
        "attachments": [
            {
                "id": "attach41",
                "name": "patch_details.pdf",
                "size": 786432,
                "type": "application/pdf",
                "url": "https://example.com/patch_details.pdf",
            }
        ],
    },
    {
        "id": "email57",
        "from": {
            "name": "Lyric Stone",
            "email": "lyric.stone@org.com",
            "avatar": "https://example.com/avatars/lyric.jpg",
        },
        "to": [{"name": "Me", "email": "me@gmail.com"}],
        "subject": "Team Happy Hour",
        "body": "Hey Me,\n\nJoin us for a team happy hour next Thursday at 6 PM.\n\nCheers,\nLyric",
        "snippet": "Join us for a team happy hour next Thursday...",
        "timestamp": datetime(2025, 7, 9, 16, 45, 0),
        "isRead": True,
        "isStarred": False,
        "isSnoozed": False,
        "isDraft": False,
        "isImportant": False,
        "labels": [{"id": "social", "name": "Social", "color": "#673ab7", "type": "user"}],
        "category": "social",
        "threadId": "thread57",
        "attachments": [],
    },
    {
        "id": "email58",
        "from": {
            "name": "Nico Wells",
            "email": "nico.wells@org.com",
            "avatar": "https://example.com/avatars/nico.jpg",
        },
        "to": [{"name": "Me", "email": "me@gmail.com"}],
        "subject": "Budget Approval Request",
        "body": "Dear Me,\n\nPlease approve the attached Q4 budget by Friday.\n\nBest,\nNico",
        "snippet": "Please approve the attached Q4 budget...",
        "timestamp": datetime(2025, 7, 9, 18, 0, 0),
        "isRead": False,
        "isStarred": False,
        "isSnoozed": False,
        "isDraft": False,
        "isImportant": True,
        "labels": [{"id": "finance", "name": "Finance", "color": "#ffeb3b", "type": "user"}],
        "category": "primary",
        "threadId": "thread58",
        "attachments": [
            {
                "id": "attach42",
                "name": "budget_q4.xlsx",
                "size": 524288,
                "type": "application/vnd.ms-excel",
                "url": "https://example.com/budget_q4.xlsx",
            }
        ],
    },
    {
        "id": "email59",
        "from": {
            "name": "Eden Marsh",
            "email": "eden.marsh@org.com",
            "avatar": "https://example.com/avatars/eden.jpg",
        },
        "to": [{"name": "Me", "email": "me@gmail.com"}],
        "subject": "New Product Launch",
        "body": "Dear Customer,\n\nOur new product is launching soon! Check out the attached preview.\n\nBest,\nEden",
        "snippet": "Our new product is launching soon...",
        "timestamp": datetime(2025, 7, 9, 19, 15, 0),
        "isRead": True,
        "isStarred": False,
        "isSnoozed": False,
        "isDraft": False,
        "isImportant": False,
        "labels": [],
        "category": "promotions",
        "threadId": "thread59",
        "attachments": [
            {
                "id": "attach43",
                "name": "product_preview.pdf",
                "size": 1572864,
                "type": "application/pdf",
                "url": "https://example.com/product_preview.pdf",
            }
        ],
    },
    {
        "id": "email9",
        "from": {
            "name": "Me",
            "email": "me@gmail.com",
            "avatar": "https://example.com/avatars/me.jpg",
        },
        "to": [{"name": "Alice Smith", "email": "alice.smith@company.com"}],
        "subject": "Re: Project Kickoff Meeting",
        "body": "Hi Alice,\n\nThanks for the agenda. I'll review and get back to you.\n\nBest,\nMe",
        "snippet": "Thanks for the agenda. I'll review and get back to you...",
        "timestamp": datetime(2025, 7, 8, 11, 0, 0),
        "isRead": True,
        "isStarred": False,
        "isSnoozed": False,
        "isDraft": False,
        "isImportant": False,
        "labels": [{"id": "sent", "name": "Sent", "color": "#34a853", "type": "system"}],
        "category": "primary",
        "threadId": "thread1",
        "attachments": [],
    },
    {
        "id": "email10",
        "from": {
            "name": "Me",
            "email": "me@gmail.com",
            "avatar": "https://example.com/avatars/me.jpg",
        },
        "to": [{"name": "Bob Johnson", "email": "bob.johnson@tech.org"}],
        "subject": "Re: Lunch Plans",
        "body": "Hey Bob,\n\nFriday works for me! Let's meet at noon.\n\nCheers,\nMe",
        "snippet": "Friday works for me! Let's meet at noon...",
        "timestamp": datetime(2025, 7, 7, 13, 0, 0),
        "isRead": True,
        "isStarred": False,
        "isSnoozed": False,
        "isDraft": False,
        "isImportant": False,
        "labels": [
            {"id": "sent", "name": "Sent", "color": "#34a853", "type": "system"},
            {"id": "personal", "name": "Personal", "color": "#0f9d58", "type": "user"},
        ],
        "category": "social",
        "threadId": "thread2",
        "attachments": [],
    },
    {
        "id": "email11",
        "from": {
            "name": "Me",
            "email": "me@gmail.com",
            "avatar": "https://example.com/avatars/me.jpg",
        },
        "to": [{"name": "David Brown", "email": "david.brown@company.com"}],
        "subject": "Re: Q2 Report Feedback",
        "body": "Hi David,\n\nI've added comments to the Q2 report. Let me know if you need more details.\n\nThanks,\nMe",
        "snippet": "I've added comments to the Q2 report...",
        "timestamp": datetime(2025, 7, 5, 15, 0, 0),
        "isRead": True,
        "isStarred": False,
        "isSnoozed": False,
        "isDraft": False,
        "isImportant": True,
        "labels": [
            {"id": "sent", "name": "Sent", "color": "#34a853", "type": "system"},
            {"id": "work", "name": "Work", "color": "#4285f4", "type": "user"},
        ],
        "category": "primary",
        "threadId": "thread4",
        "attachments": [],
    },
    {
        "id": "email12",
        "from": {
            "name": "Me",
            "email": "me@gmail.com",
            "avatar": "https://example.com/avatars/me.jpg",
        },
        "to": [{"name": "Grace Lee", "email": "grace.lee@company.com"}],
        "subject": "Re: Team Outing Plan",
        "body": "Hi Grace,\n\nI'm available on the 15th. Let me know the details!\n\nThanks,\nMe",
        "snippet": "I'm available on the 15th...",
        "timestamp": datetime(2025, 7, 2, 14, 0, 0),
        "isRead": True,
        "isStarred": True,
        "isSnoozed": False,
        "isDraft": False,
        "isImportant": False,
        "labels": [
            {"id": "sent", "name": "Sent", "color": "#34a853", "type": "system"},
            {"id": "work", "name": "Work", "color": "#4285f4", "type": "user"},
        ],
        "category": "primary",
        "threadId": "thread7",
        "attachments": [],
    },
    {
        "id": "email13",
        "from": {
            "name": "Me",
            "email": "me@gmail.com",
            "avatar": "https://example.com/avatars/me.jpg",
        },
        "to": [{"name": "Henry Moore", "email": "henry.moore@tech.org"}],
        "subject": "Re: Exclusive Offer",
        "body": "Hi Henry,\n\nThanks for the offer! I'll use the code this weekend.\n\nBest,\nMe",
        "snippet": "Thanks for the offer! I'll use the code this weekend...",
        "timestamp": datetime(2025, 7, 1, 9, 0, 0),
        "isRead": True,
        "isStarred": False,
        "isSnoozed": False,
        "isDraft": False,
        "isImportant": False,
        "labels": [{"id": "sent", "name": "Sent", "color": "#34a853", "type": "system"}],
        "category": "promotions",
        "threadId": "thread8",
        "attachments": [],
    },
    {
        "id": "email14",
        "from": {
            "name": "Me",
            "email": "me@gmail.com",
            "avatar": "https://example.com/avatars/me.jpg",
        },
        "to": [{"name": "Alice Smith", "email": "alice.smith@company.com"}],
        "subject": "Draft: Project Update",
        "body": "Hi Alice,\n\nHere's the latest project update...\n\nBest,\nMe",
        "snippet": "Here's the latest project update...",
        "timestamp": datetime(2025, 7, 7, 10, 0, 0),
        "isRead": True,
        "isStarred": False,
        "isSnoozed": False,
        "isDraft": True,
        "isImportant": False,
        "labels": [{"id": "drafts", "name": "Drafts", "color": "#9aa0a6", "type": "system"}],
        "category": "primary",
        "threadId": "thread14",
        "attachments": [],
    },
    {
        "id": "email15",
        "from": {
            "name": "Me",
            "email": "me@gmail.com",
            "avatar": "https://example.com/avatars/me.jpg",
        },
        "to": [{"name": "Bob Johnson", "email": "bob.johnson@tech.org"}],
        "subject": "(no subject)",
        "body": "Hey Bob,\n\nJust checking in...\n\nCheers,\nMe",
        "snippet": "Just checking in...",
        "timestamp": datetime(2025, 7, 6, 12, 0, 0),
        "isRead": True,
        "isStarred": False,
        "isSnoozed": False,
        "isDraft": True,
        "isImportant": False,
        "labels": [
            {"id": "drafts", "name": "Drafts", "color": "#9aa0a6", "type": "system"},
            {"id": "personal", "name": "Personal", "color": "#0f9d58", "type": "user"},
        ],
        "category": "social",
        "threadId": "thread15",
        "attachments": [],
    },
    {
        "id": "email16",
        "from": {
            "name": "Me",
            "email": "me@gmail.com",
            "avatar": "https://example.com/avatars/me.jpg",
        },
        "to": [{"name": "Carol White", "email": "carol.white@outlook.com"}],
        "subject": "Draft: Feedback",
        "body": "Hi Carol,\n\nI have some feedback on the newsletter...\n\nBest,\nMe",
        "snippet": "I have some feedback on the newsletter...",
        "timestamp": datetime(2025, 7, 5, 9, 0, 0),
        "isRead": True,
        "isStarred": False,
        "isSnoozed": False,
        "isDraft": True,
        "isImportant": False,
        "labels": [{"id": "drafts", "name": "Drafts", "color": "#9aa0a6", "type": "system"}],
        "category": "promotions",
        "threadId": "thread16",
        "attachments": [],
    },
    {
        "id": "email17",
        "from": {"name": "Unknown Sender", "email": "spam@unknown.com"},
        "to": [{"name": "Me", "email": "me@gmail.com"}],
        "subject": "Win a Free Vacation!",
        "body": "Congratulations! You've won a free vacation. Click here to claim.\n\nBest,\nUnknown Sender",
        "snippet": "Congratulations! You've won a free vacation...",
        "timestamp": datetime(2025, 7, 4, 8, 0, 0),
        "isRead": False,
        "isStarred": False,
        "isSnoozed": False,
        "isDraft": False,
        "isImportant": False,
        "labels": [{"id": "spam", "name": "Spam", "color": "#ea4335", "type": "system"}],
        "category": "promotions",
        "threadId": "thread17",
        "attachments": [],
    },
    {
        "id": "email18",
        "from": {"name": "Promo Bot", "email": "promo.bot@scam.com"},
        "to": [{"name": "Me", "email": "me@gmail.com"}],
        "subject": "Amazing Deal Awaits!",
        "body": "Don't miss this amazing deal! Click now to save big.\n\nBest,\nPromo Bot",
        "snippet": "Don't miss this amazing deal...",
        "timestamp": datetime(2025, 7, 3, 7, 0, 0),
        "isRead": False,
        "isStarred": False,
        "isSnoozed": False,
        "isDraft": False,
        "isImportant": False,
        "labels": [{"id": "spam", "name": "Spam", "color": "#ea4335", "type": "system"}],
        "category": "promotions",
        "threadId": "thread18",
        "attachments": [],
    },
    {
        "id": "email19",
        "from": {"name": "Old Contact", "email": "old.contact@yahoo.com"},
        "to": [{"name": "Me", "email": "me@gmail.com"}],
        "subject": "Old Email",
        "body": "This is an old email moved to trash.\n\nBest,\nOld Contact",
        "snippet": "This is an old email moved to trash...",
        "timestamp": datetime(2025, 6, 30, 10, 0, 0),
        "isRead": True,
        "isStarred": False,
        "isSnoozed": False,
        "isDraft": False,
        "isImportant": False,
        "labels": [{"id": "trash", "name": "Trash", "color": "#5f6368", "type": "system"}],
        "category": "primary",
        "threadId": "thread19",
        "attachments": [],
    },
    {
        "id": "email20",
        "from": {
            "name": "Me",
            "email": "me@gmail.com",
            "avatar": "https://example.com/avatars/me.jpg",
        },
        "to": [{"name": "Deleted User", "email": "deleted.user@company.com"}],
        "subject": "Re: Old Project",
        "body": "Hi,\n\nThis email was moved to trash.\n\nBest,\nMe",
        "snippet": "This email was moved to trash...",
        "timestamp": datetime(2025, 6, 29, 15, 0, 0),
        "isRead": True,
        "isStarred": False,
        "isSnoozed": False,
        "isDraft": False,
        "isImportant": False,
        "labels": [
            {"id": "trash", "name": "Trash", "color": "#5f6368", "type": "system"},
            {"id": "sent", "name": "Sent", "color": "#34a853", "type": "system"},
        ],
        "category": "primary",
        "threadId": "thread20",
        "attachments": [],
    },
]

EMAILS_DATA_MODIFIED = []
for email in deepcopy(EMAILS_DATA):
    if email.get("from"):
        new_dict = {}
        for k, v in email["from"].items():
            new_dict["from_" + k] = v
        email.pop("from")
        email.update(new_dict)
    if email.get("to"):
        email["to"] = email["to"][0]["email"]
    EMAILS_DATA_MODIFIED.append(email)

from ..operators import CONTAINS, EQUALS, NOT_CONTAINS, NOT_EQUALS

FIELD_OPERATORS_VIEW_EMAIL_MAP = {
    "from_email": [EQUALS, NOT_EQUALS, CONTAINS, NOT_CONTAINS],
    "subject": [EQUALS, NOT_EQUALS, CONTAINS, NOT_CONTAINS],
}

FLAGGED_VARIABLES_OPERATORS = [EQUALS, NOT_EQUALS]

FIELD_OPERATORS_STARRED_MAP = {
    **FIELD_OPERATORS_VIEW_EMAIL_MAP,
    "isStarred": FLAGGED_VARIABLES_OPERATORS,
}

FIELD_OPERATORS_IMPORTANT_MAP = {
    **FIELD_OPERATORS_VIEW_EMAIL_MAP,
    "isImportant": FLAGGED_VARIABLES_OPERATORS,
}

FIELD_OPERATORS_IS_READ_MAP = {
    **FIELD_OPERATORS_VIEW_EMAIL_MAP,
    "isRead": FLAGGED_VARIABLES_OPERATORS,
}

FIELD_OPERATORS_IS_SPAM_MAP = {
    **FIELD_OPERATORS_VIEW_EMAIL_MAP,
    "isSpam": FLAGGED_VARIABLES_OPERATORS,
}


def get_all_email_words():
    words = set()
    for email in EMAILS_DATA_MODIFIED:
        if email.get("subject"):
            words.update(email["subject"].split())
        if email.get("from_email"):
            words.add(email["from_email"])
        if email.get("body"):
            words.update(email["body"].split())
    return list(words)


ALL_EMAIL_WORDS = get_all_email_words()

FIELD_OPERATORS_SEARCH_MAP = {"query": [EQUALS, NOT_EQUALS, CONTAINS, NOT_CONTAINS]}

# FIELD_OPERATORS_COMPOSE_EMAIL_MAP = {
#     'to': [EQUALS, NOT_EQUALS, CONTAINS, NOT_CONTAINS],
#     'subject': [EQUALS, NOT_EQUALS, CONTAINS, NOT_CONTAINS],
#     'body': [EQUALS, NOT_EQUALS, CONTAINS, NOT_CONTAINS]
# }
FIELD_OPERATORS_SEND_EMAIL_MAP = {
    "to": [EQUALS, NOT_EQUALS, CONTAINS, NOT_CONTAINS],
    "subject": [EQUALS, NOT_EQUALS, CONTAINS, NOT_CONTAINS],
    # 'body': [EQUALS, NOT_EQUALS, CONTAINS, NOT_CONTAINS]
}

FIELD_OPERATORS_SAVE_AS_DRAFT_MAP = {"to": [EQUALS, NOT_EQUALS, CONTAINS, NOT_CONTAINS], "subject": [EQUALS, NOT_EQUALS, CONTAINS, NOT_CONTAINS], "body": [EQUALS, NOT_EQUALS, CONTAINS, NOT_CONTAINS]}

FIELD_OPERATORS_CREATE_LABEL_MAP = {"label_name": [EQUALS, NOT_EQUALS, CONTAINS, NOT_CONTAINS], "label_color": [EQUALS, NOT_EQUALS, CONTAINS, NOT_CONTAINS]}
FIELD_OPERATORS_ADD_LABEL_MAP = {
    "action": [EQUALS],
    "email_ids": [EQUALS, NOT_EQUALS, CONTAINS, NOT_CONTAINS],
    "label_name": [EQUALS, NOT_EQUALS],
    "subject": [EQUALS, NOT_EQUALS, CONTAINS, NOT_CONTAINS],
}
