from autoppia_iwa.src.execution.dynamic.palette import MutationPalette
import json

PALETTE_DATA = json.loads(r"""
{
  "project_id": "autowork",
  "version": "v1",
  "generated_by": "build_dynamic_palette",
  "templates": [
    {
      "id": "home-d1-0-wrap",
      "phase": "d1",
      "selector": "header",
      "operation": "wrap_with",
      "html": "<section class=\"iwa-dynamic-panel iwa-dynamic-panel--primary\" data-seed=\"{{seed}}\" data-path=\"/\">\n  <header>\n    <h2>Variant {{seed}} preview</h2>\n    <p class=\"iwa-dynamic-panel__subtitle\">Stress test block for <code>/</code></p>\n  </header>\n  <article class=\"iwa-dynamic-panel__body\">\n    <p>Seed {{seed}} injects synthetic content to expose brittle selectors and assertions.</p>\n    <ul class=\"iwa-dynamic-panel__list\">\n      <li data-role=\"summary\">DOM target: <strong>/</strong></li>\n      <li data-role=\"selector\">Selector impact: <code>#00</code></li>\n      <li data-role=\"note\">Always ensure your automation tolerates this block.</li>\n    </ul>\n  </article>\n  <footer>\n    <button class=\"iwa-dynamic-panel__cta\">Acknowledge variant {{seed}}</button>\n  </footer>\n</section>",
      "attribute": null,
      "value": null,
      "text": null,
      "new_name": null,
      "url_pattern": "/",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "home-d1-0-insert-after",
      "phase": "d1",
      "selector": "header",
      "operation": "insert_after",
      "html": "<aside class='iwa-palette-banner' data-seed='{{seed}}'>Seed {{seed}} activated for <code>/</code></aside>",
      "attribute": null,
      "value": null,
      "text": null,
      "new_name": null,
      "url_pattern": "/",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "home-d1-0-replace",
      "phase": "d1",
      "selector": "header",
      "operation": "replace_inner_html",
      "html": "<section class=\"iwa-dynamic-panel iwa-dynamic-panel--primary\" data-seed=\"{{seed}}\" data-path=\"/\">\n  <header>\n    <h2>Variant {{seed}} preview</h2>\n    <p class=\"iwa-dynamic-panel__subtitle\">Stress test block for <code>/</code></p>\n  </header>\n  <article class=\"iwa-dynamic-panel__body\">\n    <p>Seed {{seed}} injects synthetic content to expose brittle selectors and assertions.</p>\n    <ul class=\"iwa-dynamic-panel__list\">\n      <li data-role=\"summary\">DOM target: <strong>/</strong></li>\n      <li data-role=\"selector\">Selector impact: <code>#00</code></li>\n      <li data-role=\"note\">Always ensure your automation tolerates this block.</li>\n    </ul>\n  </article>\n  <footer>\n    <button class=\"iwa-dynamic-panel__cta\">Acknowledge variant {{seed}}</button>\n  </footer>\n</section>",
      "attribute": null,
      "value": null,
      "text": null,
      "new_name": null,
      "url_pattern": "/",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "home-d1-1-wrap",
      "phase": "d1",
      "selector": "nav",
      "operation": "wrap_with",
      "html": "<section class=\"iwa-dynamic-panel iwa-dynamic-panel--secondary\" data-seed=\"{{seed}}\" data-path=\"/\">\n  <header>\n    <h2>Variant {{seed}} preview</h2>\n    <p class=\"iwa-dynamic-panel__subtitle\">Stress test block for <code>/</code></p>\n  </header>\n  <article class=\"iwa-dynamic-panel__body\">\n    <p>Seed {{seed}} injects synthetic content to expose brittle selectors and assertions.</p>\n    <ul class=\"iwa-dynamic-panel__list\">\n      <li data-role=\"summary\">DOM target: <strong>/</strong></li>\n      <li data-role=\"selector\">Selector impact: <code>#01</code></li>\n      <li data-role=\"note\">Always ensure your automation tolerates this block.</li>\n    </ul>\n  </article>\n  <footer>\n    <button class=\"iwa-dynamic-panel__cta\">Acknowledge variant {{seed}}</button>\n  </footer>\n</section>",
      "attribute": null,
      "value": null,
      "text": null,
      "new_name": null,
      "url_pattern": "/",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "home-d1-1-insert-after",
      "phase": "d1",
      "selector": "nav",
      "operation": "insert_after",
      "html": "<aside class='iwa-palette-banner' data-seed='{{seed}}'>Seed {{seed}} activated for <code>/</code></aside>",
      "attribute": null,
      "value": null,
      "text": null,
      "new_name": null,
      "url_pattern": "/",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "home-d1-1-replace",
      "phase": "d1",
      "selector": "nav",
      "operation": "replace_inner_html",
      "html": "<section class=\"iwa-dynamic-panel iwa-dynamic-panel--secondary\" data-seed=\"{{seed}}\" data-path=\"/\">\n  <header>\n    <h2>Variant {{seed}} preview</h2>\n    <p class=\"iwa-dynamic-panel__subtitle\">Stress test block for <code>/</code></p>\n  </header>\n  <article class=\"iwa-dynamic-panel__body\">\n    <p>Seed {{seed}} injects synthetic content to expose brittle selectors and assertions.</p>\n    <ul class=\"iwa-dynamic-panel__list\">\n      <li data-role=\"summary\">DOM target: <strong>/</strong></li>\n      <li data-role=\"selector\">Selector impact: <code>#01</code></li>\n      <li data-role=\"note\">Always ensure your automation tolerates this block.</li>\n    </ul>\n  </article>\n  <footer>\n    <button class=\"iwa-dynamic-panel__cta\">Acknowledge variant {{seed}}</button>\n  </footer>\n</section>",
      "attribute": null,
      "value": null,
      "text": null,
      "new_name": null,
      "url_pattern": "/",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "home-d1-2-wrap",
      "phase": "d1",
      "selector": "main",
      "operation": "wrap_with",
      "html": "<section class=\"iwa-dynamic-panel iwa-dynamic-panel--accent\" data-seed=\"{{seed}}\" data-path=\"/\">\n  <header>\n    <h2>Variant {{seed}} preview</h2>\n    <p class=\"iwa-dynamic-panel__subtitle\">Stress test block for <code>/</code></p>\n  </header>\n  <article class=\"iwa-dynamic-panel__body\">\n    <p>Seed {{seed}} injects synthetic content to expose brittle selectors and assertions.</p>\n    <ul class=\"iwa-dynamic-panel__list\">\n      <li data-role=\"summary\">DOM target: <strong>/</strong></li>\n      <li data-role=\"selector\">Selector impact: <code>#02</code></li>\n      <li data-role=\"note\">Always ensure your automation tolerates this block.</li>\n    </ul>\n  </article>\n  <footer>\n    <button class=\"iwa-dynamic-panel__cta\">Acknowledge variant {{seed}}</button>\n  </footer>\n</section>",
      "attribute": null,
      "value": null,
      "text": null,
      "new_name": null,
      "url_pattern": "/",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "home-d1-2-insert-after",
      "phase": "d1",
      "selector": "main",
      "operation": "insert_after",
      "html": "<aside class='iwa-palette-banner' data-seed='{{seed}}'>Seed {{seed}} activated for <code>/</code></aside>",
      "attribute": null,
      "value": null,
      "text": null,
      "new_name": null,
      "url_pattern": "/",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "home-d1-2-replace",
      "phase": "d1",
      "selector": "main",
      "operation": "replace_inner_html",
      "html": "<section class=\"iwa-dynamic-panel iwa-dynamic-panel--accent\" data-seed=\"{{seed}}\" data-path=\"/\">\n  <header>\n    <h2>Variant {{seed}} preview</h2>\n    <p class=\"iwa-dynamic-panel__subtitle\">Stress test block for <code>/</code></p>\n  </header>\n  <article class=\"iwa-dynamic-panel__body\">\n    <p>Seed {{seed}} injects synthetic content to expose brittle selectors and assertions.</p>\n    <ul class=\"iwa-dynamic-panel__list\">\n      <li data-role=\"summary\">DOM target: <strong>/</strong></li>\n      <li data-role=\"selector\">Selector impact: <code>#02</code></li>\n      <li data-role=\"note\">Always ensure your automation tolerates this block.</li>\n    </ul>\n  </article>\n  <footer>\n    <button class=\"iwa-dynamic-panel__cta\">Acknowledge variant {{seed}}</button>\n  </footer>\n</section>",
      "attribute": null,
      "value": null,
      "text": null,
      "new_name": null,
      "url_pattern": "/",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "home-d1-3-wrap",
      "phase": "d1",
      "selector": "section",
      "operation": "wrap_with",
      "html": "<section class=\"iwa-dynamic-panel iwa-dynamic-panel--muted\" data-seed=\"{{seed}}\" data-path=\"/\">\n  <header>\n    <h2>Variant {{seed}} preview</h2>\n    <p class=\"iwa-dynamic-panel__subtitle\">Stress test block for <code>/</code></p>\n  </header>\n  <article class=\"iwa-dynamic-panel__body\">\n    <p>Seed {{seed}} injects synthetic content to expose brittle selectors and assertions.</p>\n    <ul class=\"iwa-dynamic-panel__list\">\n      <li data-role=\"summary\">DOM target: <strong>/</strong></li>\n      <li data-role=\"selector\">Selector impact: <code>#03</code></li>\n      <li data-role=\"note\">Always ensure your automation tolerates this block.</li>\n    </ul>\n  </article>\n  <footer>\n    <button class=\"iwa-dynamic-panel__cta\">Acknowledge variant {{seed}}</button>\n  </footer>\n</section>",
      "attribute": null,
      "value": null,
      "text": null,
      "new_name": null,
      "url_pattern": "/",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "home-d1-3-insert-after",
      "phase": "d1",
      "selector": "section",
      "operation": "insert_after",
      "html": "<aside class='iwa-palette-banner' data-seed='{{seed}}'>Seed {{seed}} activated for <code>/</code></aside>",
      "attribute": null,
      "value": null,
      "text": null,
      "new_name": null,
      "url_pattern": "/",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "home-d1-3-replace",
      "phase": "d1",
      "selector": "section",
      "operation": "replace_inner_html",
      "html": "<section class=\"iwa-dynamic-panel iwa-dynamic-panel--muted\" data-seed=\"{{seed}}\" data-path=\"/\">\n  <header>\n    <h2>Variant {{seed}} preview</h2>\n    <p class=\"iwa-dynamic-panel__subtitle\">Stress test block for <code>/</code></p>\n  </header>\n  <article class=\"iwa-dynamic-panel__body\">\n    <p>Seed {{seed}} injects synthetic content to expose brittle selectors and assertions.</p>\n    <ul class=\"iwa-dynamic-panel__list\">\n      <li data-role=\"summary\">DOM target: <strong>/</strong></li>\n      <li data-role=\"selector\">Selector impact: <code>#03</code></li>\n      <li data-role=\"note\">Always ensure your automation tolerates this block.</li>\n    </ul>\n  </article>\n  <footer>\n    <button class=\"iwa-dynamic-panel__cta\">Acknowledge variant {{seed}}</button>\n  </footer>\n</section>",
      "attribute": null,
      "value": null,
      "text": null,
      "new_name": null,
      "url_pattern": "/",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "home-d1-4-wrap",
      "phase": "d1",
      "selector": "aside",
      "operation": "wrap_with",
      "html": "<section class=\"iwa-dynamic-panel iwa-dynamic-panel--primary\" data-seed=\"{{seed}}\" data-path=\"/\">\n  <header>\n    <h2>Variant {{seed}} preview</h2>\n    <p class=\"iwa-dynamic-panel__subtitle\">Stress test block for <code>/</code></p>\n  </header>\n  <article class=\"iwa-dynamic-panel__body\">\n    <p>Seed {{seed}} injects synthetic content to expose brittle selectors and assertions.</p>\n    <ul class=\"iwa-dynamic-panel__list\">\n      <li data-role=\"summary\">DOM target: <strong>/</strong></li>\n      <li data-role=\"selector\">Selector impact: <code>#04</code></li>\n      <li data-role=\"note\">Always ensure your automation tolerates this block.</li>\n    </ul>\n  </article>\n  <footer>\n    <button class=\"iwa-dynamic-panel__cta\">Acknowledge variant {{seed}}</button>\n  </footer>\n</section>",
      "attribute": null,
      "value": null,
      "text": null,
      "new_name": null,
      "url_pattern": "/",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "home-d1-4-insert-after",
      "phase": "d1",
      "selector": "aside",
      "operation": "insert_after",
      "html": "<aside class='iwa-palette-banner' data-seed='{{seed}}'>Seed {{seed}} activated for <code>/</code></aside>",
      "attribute": null,
      "value": null,
      "text": null,
      "new_name": null,
      "url_pattern": "/",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "home-d1-4-replace",
      "phase": "d1",
      "selector": "aside",
      "operation": "replace_inner_html",
      "html": "<section class=\"iwa-dynamic-panel iwa-dynamic-panel--primary\" data-seed=\"{{seed}}\" data-path=\"/\">\n  <header>\n    <h2>Variant {{seed}} preview</h2>\n    <p class=\"iwa-dynamic-panel__subtitle\">Stress test block for <code>/</code></p>\n  </header>\n  <article class=\"iwa-dynamic-panel__body\">\n    <p>Seed {{seed}} injects synthetic content to expose brittle selectors and assertions.</p>\n    <ul class=\"iwa-dynamic-panel__list\">\n      <li data-role=\"summary\">DOM target: <strong>/</strong></li>\n      <li data-role=\"selector\">Selector impact: <code>#04</code></li>\n      <li data-role=\"note\">Always ensure your automation tolerates this block.</li>\n    </ul>\n  </article>\n  <footer>\n    <button class=\"iwa-dynamic-panel__cta\">Acknowledge variant {{seed}}</button>\n  </footer>\n</section>",
      "attribute": null,
      "value": null,
      "text": null,
      "new_name": null,
      "url_pattern": "/",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "home-d1-5-wrap",
      "phase": "d1",
      "selector": ".flex",
      "operation": "wrap_with",
      "html": "<section class=\"iwa-dynamic-panel iwa-dynamic-panel--secondary\" data-seed=\"{{seed}}\" data-path=\"/\">\n  <header>\n    <h2>Variant {{seed}} preview</h2>\n    <p class=\"iwa-dynamic-panel__subtitle\">Stress test block for <code>/</code></p>\n  </header>\n  <article class=\"iwa-dynamic-panel__body\">\n    <p>Seed {{seed}} injects synthetic content to expose brittle selectors and assertions.</p>\n    <ul class=\"iwa-dynamic-panel__list\">\n      <li data-role=\"summary\">DOM target: <strong>/</strong></li>\n      <li data-role=\"selector\">Selector impact: <code>#05</code></li>\n      <li data-role=\"note\">Always ensure your automation tolerates this block.</li>\n    </ul>\n  </article>\n  <footer>\n    <button class=\"iwa-dynamic-panel__cta\">Acknowledge variant {{seed}}</button>\n  </footer>\n</section>",
      "attribute": null,
      "value": null,
      "text": null,
      "new_name": null,
      "url_pattern": "/",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "home-d1-5-insert-after",
      "phase": "d1",
      "selector": ".flex",
      "operation": "insert_after",
      "html": "<aside class='iwa-palette-banner' data-seed='{{seed}}'>Seed {{seed}} activated for <code>/</code></aside>",
      "attribute": null,
      "value": null,
      "text": null,
      "new_name": null,
      "url_pattern": "/",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "home-d1-5-replace",
      "phase": "d1",
      "selector": ".flex",
      "operation": "replace_inner_html",
      "html": "<section class=\"iwa-dynamic-panel iwa-dynamic-panel--secondary\" data-seed=\"{{seed}}\" data-path=\"/\">\n  <header>\n    <h2>Variant {{seed}} preview</h2>\n    <p class=\"iwa-dynamic-panel__subtitle\">Stress test block for <code>/</code></p>\n  </header>\n  <article class=\"iwa-dynamic-panel__body\">\n    <p>Seed {{seed}} injects synthetic content to expose brittle selectors and assertions.</p>\n    <ul class=\"iwa-dynamic-panel__list\">\n      <li data-role=\"summary\">DOM target: <strong>/</strong></li>\n      <li data-role=\"selector\">Selector impact: <code>#05</code></li>\n      <li data-role=\"note\">Always ensure your automation tolerates this block.</li>\n    </ul>\n  </article>\n  <footer>\n    <button class=\"iwa-dynamic-panel__cta\">Acknowledge variant {{seed}}</button>\n  </footer>\n</section>",
      "attribute": null,
      "value": null,
      "text": null,
      "new_name": null,
      "url_pattern": "/",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "home-d1-6-wrap",
      "phase": "d1",
      "selector": ".items-center",
      "operation": "wrap_with",
      "html": "<section class=\"iwa-dynamic-panel iwa-dynamic-panel--accent\" data-seed=\"{{seed}}\" data-path=\"/\">\n  <header>\n    <h2>Variant {{seed}} preview</h2>\n    <p class=\"iwa-dynamic-panel__subtitle\">Stress test block for <code>/</code></p>\n  </header>\n  <article class=\"iwa-dynamic-panel__body\">\n    <p>Seed {{seed}} injects synthetic content to expose brittle selectors and assertions.</p>\n    <ul class=\"iwa-dynamic-panel__list\">\n      <li data-role=\"summary\">DOM target: <strong>/</strong></li>\n      <li data-role=\"selector\">Selector impact: <code>#06</code></li>\n      <li data-role=\"note\">Always ensure your automation tolerates this block.</li>\n    </ul>\n  </article>\n  <footer>\n    <button class=\"iwa-dynamic-panel__cta\">Acknowledge variant {{seed}}</button>\n  </footer>\n</section>",
      "attribute": null,
      "value": null,
      "text": null,
      "new_name": null,
      "url_pattern": "/",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "home-d1-6-insert-after",
      "phase": "d1",
      "selector": ".items-center",
      "operation": "insert_after",
      "html": "<aside class='iwa-palette-banner' data-seed='{{seed}}'>Seed {{seed}} activated for <code>/</code></aside>",
      "attribute": null,
      "value": null,
      "text": null,
      "new_name": null,
      "url_pattern": "/",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "home-d1-6-replace",
      "phase": "d1",
      "selector": ".items-center",
      "operation": "replace_inner_html",
      "html": "<section class=\"iwa-dynamic-panel iwa-dynamic-panel--accent\" data-seed=\"{{seed}}\" data-path=\"/\">\n  <header>\n    <h2>Variant {{seed}} preview</h2>\n    <p class=\"iwa-dynamic-panel__subtitle\">Stress test block for <code>/</code></p>\n  </header>\n  <article class=\"iwa-dynamic-panel__body\">\n    <p>Seed {{seed}} injects synthetic content to expose brittle selectors and assertions.</p>\n    <ul class=\"iwa-dynamic-panel__list\">\n      <li data-role=\"summary\">DOM target: <strong>/</strong></li>\n      <li data-role=\"selector\">Selector impact: <code>#06</code></li>\n      <li data-role=\"note\">Always ensure your automation tolerates this block.</li>\n    </ul>\n  </article>\n  <footer>\n    <button class=\"iwa-dynamic-panel__cta\">Acknowledge variant {{seed}}</button>\n  </footer>\n</section>",
      "attribute": null,
      "value": null,
      "text": null,
      "new_name": null,
      "url_pattern": "/",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "home-d1-7-wrap",
      "phase": "d1",
      "selector": ".font-semibold",
      "operation": "wrap_with",
      "html": "<section class=\"iwa-dynamic-panel iwa-dynamic-panel--muted\" data-seed=\"{{seed}}\" data-path=\"/\">\n  <header>\n    <h2>Variant {{seed}} preview</h2>\n    <p class=\"iwa-dynamic-panel__subtitle\">Stress test block for <code>/</code></p>\n  </header>\n  <article class=\"iwa-dynamic-panel__body\">\n    <p>Seed {{seed}} injects synthetic content to expose brittle selectors and assertions.</p>\n    <ul class=\"iwa-dynamic-panel__list\">\n      <li data-role=\"summary\">DOM target: <strong>/</strong></li>\n      <li data-role=\"selector\">Selector impact: <code>#07</code></li>\n      <li data-role=\"note\">Always ensure your automation tolerates this block.</li>\n    </ul>\n  </article>\n  <footer>\n    <button class=\"iwa-dynamic-panel__cta\">Acknowledge variant {{seed}}</button>\n  </footer>\n</section>",
      "attribute": null,
      "value": null,
      "text": null,
      "new_name": null,
      "url_pattern": "/",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "home-d1-7-insert-after",
      "phase": "d1",
      "selector": ".font-semibold",
      "operation": "insert_after",
      "html": "<aside class='iwa-palette-banner' data-seed='{{seed}}'>Seed {{seed}} activated for <code>/</code></aside>",
      "attribute": null,
      "value": null,
      "text": null,
      "new_name": null,
      "url_pattern": "/",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "home-d1-7-replace",
      "phase": "d1",
      "selector": ".font-semibold",
      "operation": "replace_inner_html",
      "html": "<section class=\"iwa-dynamic-panel iwa-dynamic-panel--muted\" data-seed=\"{{seed}}\" data-path=\"/\">\n  <header>\n    <h2>Variant {{seed}} preview</h2>\n    <p class=\"iwa-dynamic-panel__subtitle\">Stress test block for <code>/</code></p>\n  </header>\n  <article class=\"iwa-dynamic-panel__body\">\n    <p>Seed {{seed}} injects synthetic content to expose brittle selectors and assertions.</p>\n    <ul class=\"iwa-dynamic-panel__list\">\n      <li data-role=\"summary\">DOM target: <strong>/</strong></li>\n      <li data-role=\"selector\">Selector impact: <code>#07</code></li>\n      <li data-role=\"note\">Always ensure your automation tolerates this block.</li>\n    </ul>\n  </article>\n  <footer>\n    <button class=\"iwa-dynamic-panel__cta\">Acknowledge variant {{seed}}</button>\n  </footer>\n</section>",
      "attribute": null,
      "value": null,
      "text": null,
      "new_name": null,
      "url_pattern": "/",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "home-d1-8-wrap",
      "phase": "d1",
      "selector": ".text-[#253037]",
      "operation": "wrap_with",
      "html": "<section class=\"iwa-dynamic-panel iwa-dynamic-panel--primary\" data-seed=\"{{seed}}\" data-path=\"/\">\n  <header>\n    <h2>Variant {{seed}} preview</h2>\n    <p class=\"iwa-dynamic-panel__subtitle\">Stress test block for <code>/</code></p>\n  </header>\n  <article class=\"iwa-dynamic-panel__body\">\n    <p>Seed {{seed}} injects synthetic content to expose brittle selectors and assertions.</p>\n    <ul class=\"iwa-dynamic-panel__list\">\n      <li data-role=\"summary\">DOM target: <strong>/</strong></li>\n      <li data-role=\"selector\">Selector impact: <code>#08</code></li>\n      <li data-role=\"note\">Always ensure your automation tolerates this block.</li>\n    </ul>\n  </article>\n  <footer>\n    <button class=\"iwa-dynamic-panel__cta\">Acknowledge variant {{seed}}</button>\n  </footer>\n</section>",
      "attribute": null,
      "value": null,
      "text": null,
      "new_name": null,
      "url_pattern": "/",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "home-d1-8-insert-after",
      "phase": "d1",
      "selector": ".text-[#253037]",
      "operation": "insert_after",
      "html": "<aside class='iwa-palette-banner' data-seed='{{seed}}'>Seed {{seed}} activated for <code>/</code></aside>",
      "attribute": null,
      "value": null,
      "text": null,
      "new_name": null,
      "url_pattern": "/",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "home-d1-8-replace",
      "phase": "d1",
      "selector": ".text-[#253037]",
      "operation": "replace_inner_html",
      "html": "<section class=\"iwa-dynamic-panel iwa-dynamic-panel--primary\" data-seed=\"{{seed}}\" data-path=\"/\">\n  <header>\n    <h2>Variant {{seed}} preview</h2>\n    <p class=\"iwa-dynamic-panel__subtitle\">Stress test block for <code>/</code></p>\n  </header>\n  <article class=\"iwa-dynamic-panel__body\">\n    <p>Seed {{seed}} injects synthetic content to expose brittle selectors and assertions.</p>\n    <ul class=\"iwa-dynamic-panel__list\">\n      <li data-role=\"summary\">DOM target: <strong>/</strong></li>\n      <li data-role=\"selector\">Selector impact: <code>#08</code></li>\n      <li data-role=\"note\">Always ensure your automation tolerates this block.</li>\n    </ul>\n  </article>\n  <footer>\n    <button class=\"iwa-dynamic-panel__cta\">Acknowledge variant {{seed}}</button>\n  </footer>\n</section>",
      "attribute": null,
      "value": null,
      "text": null,
      "new_name": null,
      "url_pattern": "/",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "home-d1-9-wrap",
      "phase": "d1",
      "selector": ".border",
      "operation": "wrap_with",
      "html": "<section class=\"iwa-dynamic-panel iwa-dynamic-panel--secondary\" data-seed=\"{{seed}}\" data-path=\"/\">\n  <header>\n    <h2>Variant {{seed}} preview</h2>\n    <p class=\"iwa-dynamic-panel__subtitle\">Stress test block for <code>/</code></p>\n  </header>\n  <article class=\"iwa-dynamic-panel__body\">\n    <p>Seed {{seed}} injects synthetic content to expose brittle selectors and assertions.</p>\n    <ul class=\"iwa-dynamic-panel__list\">\n      <li data-role=\"summary\">DOM target: <strong>/</strong></li>\n      <li data-role=\"selector\">Selector impact: <code>#09</code></li>\n      <li data-role=\"note\">Always ensure your automation tolerates this block.</li>\n    </ul>\n  </article>\n  <footer>\n    <button class=\"iwa-dynamic-panel__cta\">Acknowledge variant {{seed}}</button>\n  </footer>\n</section>",
      "attribute": null,
      "value": null,
      "text": null,
      "new_name": null,
      "url_pattern": "/",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "home-d1-9-insert-after",
      "phase": "d1",
      "selector": ".border",
      "operation": "insert_after",
      "html": "<aside class='iwa-palette-banner' data-seed='{{seed}}'>Seed {{seed}} activated for <code>/</code></aside>",
      "attribute": null,
      "value": null,
      "text": null,
      "new_name": null,
      "url_pattern": "/",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "home-d1-9-replace",
      "phase": "d1",
      "selector": ".border",
      "operation": "replace_inner_html",
      "html": "<section class=\"iwa-dynamic-panel iwa-dynamic-panel--secondary\" data-seed=\"{{seed}}\" data-path=\"/\">\n  <header>\n    <h2>Variant {{seed}} preview</h2>\n    <p class=\"iwa-dynamic-panel__subtitle\">Stress test block for <code>/</code></p>\n  </header>\n  <article class=\"iwa-dynamic-panel__body\">\n    <p>Seed {{seed}} injects synthetic content to expose brittle selectors and assertions.</p>\n    <ul class=\"iwa-dynamic-panel__list\">\n      <li data-role=\"summary\">DOM target: <strong>/</strong></li>\n      <li data-role=\"selector\">Selector impact: <code>#09</code></li>\n      <li data-role=\"note\">Always ensure your automation tolerates this block.</li>\n    </ul>\n  </article>\n  <footer>\n    <button class=\"iwa-dynamic-panel__cta\">Acknowledge variant {{seed}}</button>\n  </footer>\n</section>",
      "attribute": null,
      "value": null,
      "text": null,
      "new_name": null,
      "url_pattern": "/",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "home-d1-10-wrap",
      "phase": "d1",
      "selector": ".shadow",
      "operation": "wrap_with",
      "html": "<section class=\"iwa-dynamic-panel iwa-dynamic-panel--accent\" data-seed=\"{{seed}}\" data-path=\"/\">\n  <header>\n    <h2>Variant {{seed}} preview</h2>\n    <p class=\"iwa-dynamic-panel__subtitle\">Stress test block for <code>/</code></p>\n  </header>\n  <article class=\"iwa-dynamic-panel__body\">\n    <p>Seed {{seed}} injects synthetic content to expose brittle selectors and assertions.</p>\n    <ul class=\"iwa-dynamic-panel__list\">\n      <li data-role=\"summary\">DOM target: <strong>/</strong></li>\n      <li data-role=\"selector\">Selector impact: <code>#10</code></li>\n      <li data-role=\"note\">Always ensure your automation tolerates this block.</li>\n    </ul>\n  </article>\n  <footer>\n    <button class=\"iwa-dynamic-panel__cta\">Acknowledge variant {{seed}}</button>\n  </footer>\n</section>",
      "attribute": null,
      "value": null,
      "text": null,
      "new_name": null,
      "url_pattern": "/",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "home-d1-10-insert-after",
      "phase": "d1",
      "selector": ".shadow",
      "operation": "insert_after",
      "html": "<aside class='iwa-palette-banner' data-seed='{{seed}}'>Seed {{seed}} activated for <code>/</code></aside>",
      "attribute": null,
      "value": null,
      "text": null,
      "new_name": null,
      "url_pattern": "/",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "home-d1-10-replace",
      "phase": "d1",
      "selector": ".shadow",
      "operation": "replace_inner_html",
      "html": "<section class=\"iwa-dynamic-panel iwa-dynamic-panel--accent\" data-seed=\"{{seed}}\" data-path=\"/\">\n  <header>\n    <h2>Variant {{seed}} preview</h2>\n    <p class=\"iwa-dynamic-panel__subtitle\">Stress test block for <code>/</code></p>\n  </header>\n  <article class=\"iwa-dynamic-panel__body\">\n    <p>Seed {{seed}} injects synthetic content to expose brittle selectors and assertions.</p>\n    <ul class=\"iwa-dynamic-panel__list\">\n      <li data-role=\"summary\">DOM target: <strong>/</strong></li>\n      <li data-role=\"selector\">Selector impact: <code>#10</code></li>\n      <li data-role=\"note\">Always ensure your automation tolerates this block.</li>\n    </ul>\n  </article>\n  <footer>\n    <button class=\"iwa-dynamic-panel__cta\">Acknowledge variant {{seed}}</button>\n  </footer>\n</section>",
      "attribute": null,
      "value": null,
      "text": null,
      "new_name": null,
      "url_pattern": "/",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "home-d1-11-wrap",
      "phase": "d1",
      "selector": ".text-xs",
      "operation": "wrap_with",
      "html": "<section class=\"iwa-dynamic-panel iwa-dynamic-panel--muted\" data-seed=\"{{seed}}\" data-path=\"/\">\n  <header>\n    <h2>Variant {{seed}} preview</h2>\n    <p class=\"iwa-dynamic-panel__subtitle\">Stress test block for <code>/</code></p>\n  </header>\n  <article class=\"iwa-dynamic-panel__body\">\n    <p>Seed {{seed}} injects synthetic content to expose brittle selectors and assertions.</p>\n    <ul class=\"iwa-dynamic-panel__list\">\n      <li data-role=\"summary\">DOM target: <strong>/</strong></li>\n      <li data-role=\"selector\">Selector impact: <code>#11</code></li>\n      <li data-role=\"note\">Always ensure your automation tolerates this block.</li>\n    </ul>\n  </article>\n  <footer>\n    <button class=\"iwa-dynamic-panel__cta\">Acknowledge variant {{seed}}</button>\n  </footer>\n</section>",
      "attribute": null,
      "value": null,
      "text": null,
      "new_name": null,
      "url_pattern": "/",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "home-d1-11-insert-after",
      "phase": "d1",
      "selector": ".text-xs",
      "operation": "insert_after",
      "html": "<aside class='iwa-palette-banner' data-seed='{{seed}}'>Seed {{seed}} activated for <code>/</code></aside>",
      "attribute": null,
      "value": null,
      "text": null,
      "new_name": null,
      "url_pattern": "/",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "home-d1-11-replace",
      "phase": "d1",
      "selector": ".text-xs",
      "operation": "replace_inner_html",
      "html": "<section class=\"iwa-dynamic-panel iwa-dynamic-panel--muted\" data-seed=\"{{seed}}\" data-path=\"/\">\n  <header>\n    <h2>Variant {{seed}} preview</h2>\n    <p class=\"iwa-dynamic-panel__subtitle\">Stress test block for <code>/</code></p>\n  </header>\n  <article class=\"iwa-dynamic-panel__body\">\n    <p>Seed {{seed}} injects synthetic content to expose brittle selectors and assertions.</p>\n    <ul class=\"iwa-dynamic-panel__list\">\n      <li data-role=\"summary\">DOM target: <strong>/</strong></li>\n      <li data-role=\"selector\">Selector impact: <code>#11</code></li>\n      <li data-role=\"note\">Always ensure your automation tolerates this block.</li>\n    </ul>\n  </article>\n  <footer>\n    <button class=\"iwa-dynamic-panel__cta\">Acknowledge variant {{seed}}</button>\n  </footer>\n</section>",
      "attribute": null,
      "value": null,
      "text": null,
      "new_name": null,
      "url_pattern": "/",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "home-d1-12-wrap",
      "phase": "d1",
      "selector": ".gap-2",
      "operation": "wrap_with",
      "html": "<section class=\"iwa-dynamic-panel iwa-dynamic-panel--primary\" data-seed=\"{{seed}}\" data-path=\"/\">\n  <header>\n    <h2>Variant {{seed}} preview</h2>\n    <p class=\"iwa-dynamic-panel__subtitle\">Stress test block for <code>/</code></p>\n  </header>\n  <article class=\"iwa-dynamic-panel__body\">\n    <p>Seed {{seed}} injects synthetic content to expose brittle selectors and assertions.</p>\n    <ul class=\"iwa-dynamic-panel__list\">\n      <li data-role=\"summary\">DOM target: <strong>/</strong></li>\n      <li data-role=\"selector\">Selector impact: <code>#12</code></li>\n      <li data-role=\"note\">Always ensure your automation tolerates this block.</li>\n    </ul>\n  </article>\n  <footer>\n    <button class=\"iwa-dynamic-panel__cta\">Acknowledge variant {{seed}}</button>\n  </footer>\n</section>",
      "attribute": null,
      "value": null,
      "text": null,
      "new_name": null,
      "url_pattern": "/",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "home-d1-12-insert-after",
      "phase": "d1",
      "selector": ".gap-2",
      "operation": "insert_after",
      "html": "<aside class='iwa-palette-banner' data-seed='{{seed}}'>Seed {{seed}} activated for <code>/</code></aside>",
      "attribute": null,
      "value": null,
      "text": null,
      "new_name": null,
      "url_pattern": "/",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "home-d1-12-replace",
      "phase": "d1",
      "selector": ".gap-2",
      "operation": "replace_inner_html",
      "html": "<section class=\"iwa-dynamic-panel iwa-dynamic-panel--primary\" data-seed=\"{{seed}}\" data-path=\"/\">\n  <header>\n    <h2>Variant {{seed}} preview</h2>\n    <p class=\"iwa-dynamic-panel__subtitle\">Stress test block for <code>/</code></p>\n  </header>\n  <article class=\"iwa-dynamic-panel__body\">\n    <p>Seed {{seed}} injects synthetic content to expose brittle selectors and assertions.</p>\n    <ul class=\"iwa-dynamic-panel__list\">\n      <li data-role=\"summary\">DOM target: <strong>/</strong></li>\n      <li data-role=\"selector\">Selector impact: <code>#12</code></li>\n      <li data-role=\"note\">Always ensure your automation tolerates this block.</li>\n    </ul>\n  </article>\n  <footer>\n    <button class=\"iwa-dynamic-panel__cta\">Acknowledge variant {{seed}}</button>\n  </footer>\n</section>",
      "attribute": null,
      "value": null,
      "text": null,
      "new_name": null,
      "url_pattern": "/",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "home-d1-13-wrap",
      "phase": "d1",
      "selector": "button",
      "operation": "wrap_with",
      "html": "<section class=\"iwa-dynamic-panel iwa-dynamic-panel--secondary\" data-seed=\"{{seed}}\" data-path=\"/\">\n  <header>\n    <h2>Variant {{seed}} preview</h2>\n    <p class=\"iwa-dynamic-panel__subtitle\">Stress test block for <code>/</code></p>\n  </header>\n  <article class=\"iwa-dynamic-panel__body\">\n    <p>Seed {{seed}} injects synthetic content to expose brittle selectors and assertions.</p>\n    <ul class=\"iwa-dynamic-panel__list\">\n      <li data-role=\"summary\">DOM target: <strong>/</strong></li>\n      <li data-role=\"selector\">Selector impact: <code>#13</code></li>\n      <li data-role=\"note\">Always ensure your automation tolerates this block.</li>\n    </ul>\n  </article>\n  <footer>\n    <button class=\"iwa-dynamic-panel__cta\">Acknowledge variant {{seed}}</button>\n  </footer>\n</section>",
      "attribute": null,
      "value": null,
      "text": null,
      "new_name": null,
      "url_pattern": "/",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "home-d1-13-insert-after",
      "phase": "d1",
      "selector": "button",
      "operation": "insert_after",
      "html": "<aside class='iwa-palette-banner' data-seed='{{seed}}'>Seed {{seed}} activated for <code>/</code></aside>",
      "attribute": null,
      "value": null,
      "text": null,
      "new_name": null,
      "url_pattern": "/",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "home-d1-13-replace",
      "phase": "d1",
      "selector": "button",
      "operation": "replace_inner_html",
      "html": "<section class=\"iwa-dynamic-panel iwa-dynamic-panel--secondary\" data-seed=\"{{seed}}\" data-path=\"/\">\n  <header>\n    <h2>Variant {{seed}} preview</h2>\n    <p class=\"iwa-dynamic-panel__subtitle\">Stress test block for <code>/</code></p>\n  </header>\n  <article class=\"iwa-dynamic-panel__body\">\n    <p>Seed {{seed}} injects synthetic content to expose brittle selectors and assertions.</p>\n    <ul class=\"iwa-dynamic-panel__list\">\n      <li data-role=\"summary\">DOM target: <strong>/</strong></li>\n      <li data-role=\"selector\">Selector impact: <code>#13</code></li>\n      <li data-role=\"note\">Always ensure your automation tolerates this block.</li>\n    </ul>\n  </article>\n  <footer>\n    <button class=\"iwa-dynamic-panel__cta\">Acknowledge variant {{seed}}</button>\n  </footer>\n</section>",
      "attribute": null,
      "value": null,
      "text": null,
      "new_name": null,
      "url_pattern": "/",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "home-d3-0-data",
      "phase": "d3",
      "selector": "header",
      "operation": "set_attribute",
      "html": null,
      "attribute": "data-iwa-variant",
      "value": "/-variant-{{seed}}",
      "text": null,
      "new_name": null,
      "url_pattern": "/",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "home-d3-0-class",
      "phase": "d3",
      "selector": "header",
      "operation": "append_class",
      "html": null,
      "attribute": null,
      "value": "iwa-variant-{{seed}}",
      "text": null,
      "new_name": null,
      "url_pattern": "/",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "home-d3-0-text",
      "phase": "d3",
      "selector": "header",
      "operation": "replace_text",
      "html": null,
      "attribute": null,
      "value": null,
      "text": "Dynamic copy for / – seed {{seed}}",
      "new_name": null,
      "url_pattern": "/",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "home-d3-1-data",
      "phase": "d3",
      "selector": "nav",
      "operation": "set_attribute",
      "html": null,
      "attribute": "data-iwa-variant",
      "value": "/-variant-{{seed}}",
      "text": null,
      "new_name": null,
      "url_pattern": "/",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "home-d3-1-class",
      "phase": "d3",
      "selector": "nav",
      "operation": "append_class",
      "html": null,
      "attribute": null,
      "value": "iwa-variant-{{seed}}",
      "text": null,
      "new_name": null,
      "url_pattern": "/",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "home-d3-1-text",
      "phase": "d3",
      "selector": "nav",
      "operation": "replace_text",
      "html": null,
      "attribute": null,
      "value": null,
      "text": "Dynamic copy for / – seed {{seed}}",
      "new_name": null,
      "url_pattern": "/",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "home-d3-2-data",
      "phase": "d3",
      "selector": "main",
      "operation": "set_attribute",
      "html": null,
      "attribute": "data-iwa-variant",
      "value": "/-variant-{{seed}}",
      "text": null,
      "new_name": null,
      "url_pattern": "/",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "home-d3-2-class",
      "phase": "d3",
      "selector": "main",
      "operation": "append_class",
      "html": null,
      "attribute": null,
      "value": "iwa-variant-{{seed}}",
      "text": null,
      "new_name": null,
      "url_pattern": "/",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "home-d3-2-text",
      "phase": "d3",
      "selector": "main",
      "operation": "replace_text",
      "html": null,
      "attribute": null,
      "value": null,
      "text": "Dynamic copy for / – seed {{seed}}",
      "new_name": null,
      "url_pattern": "/",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "home-d3-3-data",
      "phase": "d3",
      "selector": "section",
      "operation": "set_attribute",
      "html": null,
      "attribute": "data-iwa-variant",
      "value": "/-variant-{{seed}}",
      "text": null,
      "new_name": null,
      "url_pattern": "/",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "home-d3-3-class",
      "phase": "d3",
      "selector": "section",
      "operation": "append_class",
      "html": null,
      "attribute": null,
      "value": "iwa-variant-{{seed}}",
      "text": null,
      "new_name": null,
      "url_pattern": "/",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "home-d3-3-text",
      "phase": "d3",
      "selector": "section",
      "operation": "replace_text",
      "html": null,
      "attribute": null,
      "value": null,
      "text": "Dynamic copy for / – seed {{seed}}",
      "new_name": null,
      "url_pattern": "/",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "home-d3-4-data",
      "phase": "d3",
      "selector": "aside",
      "operation": "set_attribute",
      "html": null,
      "attribute": "data-iwa-variant",
      "value": "/-variant-{{seed}}",
      "text": null,
      "new_name": null,
      "url_pattern": "/",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "home-d3-4-class",
      "phase": "d3",
      "selector": "aside",
      "operation": "append_class",
      "html": null,
      "attribute": null,
      "value": "iwa-variant-{{seed}}",
      "text": null,
      "new_name": null,
      "url_pattern": "/",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "home-d3-4-text",
      "phase": "d3",
      "selector": "aside",
      "operation": "replace_text",
      "html": null,
      "attribute": null,
      "value": null,
      "text": "Dynamic copy for / – seed {{seed}}",
      "new_name": null,
      "url_pattern": "/",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "home-d3-5-data",
      "phase": "d3",
      "selector": ".flex",
      "operation": "set_attribute",
      "html": null,
      "attribute": "data-iwa-variant",
      "value": "/-variant-{{seed}}",
      "text": null,
      "new_name": null,
      "url_pattern": "/",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "home-d3-5-class",
      "phase": "d3",
      "selector": ".flex",
      "operation": "append_class",
      "html": null,
      "attribute": null,
      "value": "iwa-variant-{{seed}}",
      "text": null,
      "new_name": null,
      "url_pattern": "/",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "home-d3-5-text",
      "phase": "d3",
      "selector": ".flex",
      "operation": "replace_text",
      "html": null,
      "attribute": null,
      "value": null,
      "text": "Dynamic copy for / – seed {{seed}}",
      "new_name": null,
      "url_pattern": "/",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "home-d3-6-data",
      "phase": "d3",
      "selector": ".items-center",
      "operation": "set_attribute",
      "html": null,
      "attribute": "data-iwa-variant",
      "value": "/-variant-{{seed}}",
      "text": null,
      "new_name": null,
      "url_pattern": "/",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "home-d3-6-class",
      "phase": "d3",
      "selector": ".items-center",
      "operation": "append_class",
      "html": null,
      "attribute": null,
      "value": "iwa-variant-{{seed}}",
      "text": null,
      "new_name": null,
      "url_pattern": "/",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "home-d3-6-text",
      "phase": "d3",
      "selector": ".items-center",
      "operation": "replace_text",
      "html": null,
      "attribute": null,
      "value": null,
      "text": "Dynamic copy for / – seed {{seed}}",
      "new_name": null,
      "url_pattern": "/",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "home-d3-7-data",
      "phase": "d3",
      "selector": ".font-semibold",
      "operation": "set_attribute",
      "html": null,
      "attribute": "data-iwa-variant",
      "value": "/-variant-{{seed}}",
      "text": null,
      "new_name": null,
      "url_pattern": "/",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "home-d3-7-class",
      "phase": "d3",
      "selector": ".font-semibold",
      "operation": "append_class",
      "html": null,
      "attribute": null,
      "value": "iwa-variant-{{seed}}",
      "text": null,
      "new_name": null,
      "url_pattern": "/",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "home-d3-7-text",
      "phase": "d3",
      "selector": ".font-semibold",
      "operation": "replace_text",
      "html": null,
      "attribute": null,
      "value": null,
      "text": "Dynamic copy for / – seed {{seed}}",
      "new_name": null,
      "url_pattern": "/",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "home-d3-8-data",
      "phase": "d3",
      "selector": ".text-[#253037]",
      "operation": "set_attribute",
      "html": null,
      "attribute": "data-iwa-variant",
      "value": "/-variant-{{seed}}",
      "text": null,
      "new_name": null,
      "url_pattern": "/",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "home-d3-8-class",
      "phase": "d3",
      "selector": ".text-[#253037]",
      "operation": "append_class",
      "html": null,
      "attribute": null,
      "value": "iwa-variant-{{seed}}",
      "text": null,
      "new_name": null,
      "url_pattern": "/",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "home-d3-8-text",
      "phase": "d3",
      "selector": ".text-[#253037]",
      "operation": "replace_text",
      "html": null,
      "attribute": null,
      "value": null,
      "text": "Dynamic copy for / – seed {{seed}}",
      "new_name": null,
      "url_pattern": "/",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "home-d3-9-data",
      "phase": "d3",
      "selector": ".border",
      "operation": "set_attribute",
      "html": null,
      "attribute": "data-iwa-variant",
      "value": "/-variant-{{seed}}",
      "text": null,
      "new_name": null,
      "url_pattern": "/",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "home-d3-9-class",
      "phase": "d3",
      "selector": ".border",
      "operation": "append_class",
      "html": null,
      "attribute": null,
      "value": "iwa-variant-{{seed}}",
      "text": null,
      "new_name": null,
      "url_pattern": "/",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "home-d3-9-text",
      "phase": "d3",
      "selector": ".border",
      "operation": "replace_text",
      "html": null,
      "attribute": null,
      "value": null,
      "text": "Dynamic copy for / – seed {{seed}}",
      "new_name": null,
      "url_pattern": "/",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "home-d3-10-data",
      "phase": "d3",
      "selector": ".shadow",
      "operation": "set_attribute",
      "html": null,
      "attribute": "data-iwa-variant",
      "value": "/-variant-{{seed}}",
      "text": null,
      "new_name": null,
      "url_pattern": "/",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "home-d3-10-class",
      "phase": "d3",
      "selector": ".shadow",
      "operation": "append_class",
      "html": null,
      "attribute": null,
      "value": "iwa-variant-{{seed}}",
      "text": null,
      "new_name": null,
      "url_pattern": "/",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "home-d3-10-text",
      "phase": "d3",
      "selector": ".shadow",
      "operation": "replace_text",
      "html": null,
      "attribute": null,
      "value": null,
      "text": "Dynamic copy for / – seed {{seed}}",
      "new_name": null,
      "url_pattern": "/",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "home-d3-11-data",
      "phase": "d3",
      "selector": ".text-xs",
      "operation": "set_attribute",
      "html": null,
      "attribute": "data-iwa-variant",
      "value": "/-variant-{{seed}}",
      "text": null,
      "new_name": null,
      "url_pattern": "/",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "home-d3-11-class",
      "phase": "d3",
      "selector": ".text-xs",
      "operation": "append_class",
      "html": null,
      "attribute": null,
      "value": "iwa-variant-{{seed}}",
      "text": null,
      "new_name": null,
      "url_pattern": "/",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "home-d3-11-text",
      "phase": "d3",
      "selector": ".text-xs",
      "operation": "replace_text",
      "html": null,
      "attribute": null,
      "value": null,
      "text": "Dynamic copy for / – seed {{seed}}",
      "new_name": null,
      "url_pattern": "/",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "home-d3-12-data",
      "phase": "d3",
      "selector": ".gap-2",
      "operation": "set_attribute",
      "html": null,
      "attribute": "data-iwa-variant",
      "value": "/-variant-{{seed}}",
      "text": null,
      "new_name": null,
      "url_pattern": "/",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "home-d3-12-class",
      "phase": "d3",
      "selector": ".gap-2",
      "operation": "append_class",
      "html": null,
      "attribute": null,
      "value": "iwa-variant-{{seed}}",
      "text": null,
      "new_name": null,
      "url_pattern": "/",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "home-d3-12-text",
      "phase": "d3",
      "selector": ".gap-2",
      "operation": "replace_text",
      "html": null,
      "attribute": null,
      "value": null,
      "text": "Dynamic copy for / – seed {{seed}}",
      "new_name": null,
      "url_pattern": "/",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "home-d3-13-data",
      "phase": "d3",
      "selector": "button",
      "operation": "set_attribute",
      "html": null,
      "attribute": "data-iwa-variant",
      "value": "/-variant-{{seed}}",
      "text": null,
      "new_name": null,
      "url_pattern": "/",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "home-d3-13-class",
      "phase": "d3",
      "selector": "button",
      "operation": "append_class",
      "html": null,
      "attribute": null,
      "value": "iwa-variant-{{seed}}",
      "text": null,
      "new_name": null,
      "url_pattern": "/",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "home-d3-13-text",
      "phase": "d3",
      "selector": "button",
      "operation": "replace_text",
      "html": null,
      "attribute": null,
      "value": null,
      "text": "Dynamic copy for / – seed {{seed}}",
      "new_name": null,
      "url_pattern": "/",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "home-d4-0",
      "phase": "d4",
      "selector": "body",
      "operation": "overlay",
      "html": "<div class='iwa-overlay iwa-overlay--banner' style='position:fixed;top:0;left:0;right:0;background:rgba(15,23,42,0.9);color:#fff;padding:18px;z-index:2147483647;font-family:sans-serif;'><div style='display:flex;flex-direction:column;gap:12px;align-items:flex-start;'><strong>Autoppia dynamic challenge</strong><span>Please confirm you accept the latest terms to continue browsing.</span><button data-iwa-dismiss style='padding:8px 16px;border:none;border-radius:8px;background:#2563eb;color:#fff;'>Continue</button></div></div>",
      "attribute": null,
      "value": null,
      "text": null,
      "new_name": null,
      "url_pattern": "/",
      "weight": 1.0,
      "overlay_type": "banner",
      "blocking": false,
      "dismiss_selector": "[data-iwa-dismiss]",
      "trigger_after": 2
    },
    {
      "id": "home-d4-2",
      "phase": "d4",
      "selector": "body",
      "operation": "overlay",
      "html": "<div class='iwa-overlay iwa-overlay--cookie' style='position:fixed;center:0;left:0;right:0;background:rgba(15,23,42,0.9);color:#fff;padding:18px;z-index:2147483647;font-family:sans-serif;'><div style='display:flex;flex-direction:column;gap:12px;align-items:flex-start;'><strong>Autoppia dynamic challenge</strong><span>Please confirm you accept the latest terms to continue browsing.</span><button data-iwa-dismiss style='padding:8px 16px;border:none;border-radius:8px;background:#2563eb;color:#fff;'>Continue</button></div></div>",
      "attribute": null,
      "value": null,
      "text": null,
      "new_name": null,
      "url_pattern": "/",
      "weight": 1.0,
      "overlay_type": "cookie",
      "blocking": true,
      "dismiss_selector": "[data-iwa-dismiss]",
      "trigger_after": 4
    },
    {
      "id": "home-d4-4",
      "phase": "d4",
      "selector": "body",
      "operation": "overlay",
      "html": "<div class='iwa-overlay iwa-overlay--modal' style='position:fixed;bottom:0;left:0;right:0;background:rgba(15,23,42,0.9);color:#fff;padding:18px;z-index:2147483647;font-family:sans-serif;'><div style='display:flex;flex-direction:column;gap:12px;align-items:flex-start;'><strong>Autoppia dynamic challenge</strong><span>Please confirm you accept the latest terms to continue browsing.</span><button data-iwa-dismiss style='padding:8px 16px;border:none;border-radius:8px;background:#2563eb;color:#fff;'>Continue</button></div></div>",
      "attribute": null,
      "value": null,
      "text": null,
      "new_name": null,
      "url_pattern": "/",
      "weight": 1.0,
      "overlay_type": "modal",
      "blocking": true,
      "dismiss_selector": "[data-iwa-dismiss]",
      "trigger_after": 3
    },
    {
      "id": "expert_alexa_r-d1-0-wrap",
      "phase": "d1",
      "selector": "header",
      "operation": "wrap_with",
      "html": "<section class=\"iwa-dynamic-panel iwa-dynamic-panel--primary\" data-seed=\"{{seed}}\" data-path=\"/expert/alexa-r\">\n  <header>\n    <h2>Variant {{seed}} preview</h2>\n    <p class=\"iwa-dynamic-panel__subtitle\">Stress test block for <code>/expert/alexa-r</code></p>\n  </header>\n  <article class=\"iwa-dynamic-panel__body\">\n    <p>Seed {{seed}} injects synthetic content to expose brittle selectors and assertions.</p>\n    <ul class=\"iwa-dynamic-panel__list\">\n      <li data-role=\"summary\">DOM target: <strong>/expert/alexa-r</strong></li>\n      <li data-role=\"selector\">Selector impact: <code>#00</code></li>\n      <li data-role=\"note\">Always ensure your automation tolerates this block.</li>\n    </ul>\n  </article>\n  <footer>\n    <button class=\"iwa-dynamic-panel__cta\">Acknowledge variant {{seed}}</button>\n  </footer>\n</section>",
      "attribute": null,
      "value": null,
      "text": null,
      "new_name": null,
      "url_pattern": "/expert/alexa-r",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "expert_alexa_r-d1-0-insert-after",
      "phase": "d1",
      "selector": "header",
      "operation": "insert_after",
      "html": "<aside class='iwa-palette-banner' data-seed='{{seed}}'>Seed {{seed}} activated for <code>/expert/alexa-r</code></aside>",
      "attribute": null,
      "value": null,
      "text": null,
      "new_name": null,
      "url_pattern": "/expert/alexa-r",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "expert_alexa_r-d1-0-replace",
      "phase": "d1",
      "selector": "header",
      "operation": "replace_inner_html",
      "html": "<section class=\"iwa-dynamic-panel iwa-dynamic-panel--primary\" data-seed=\"{{seed}}\" data-path=\"/expert/alexa-r\">\n  <header>\n    <h2>Variant {{seed}} preview</h2>\n    <p class=\"iwa-dynamic-panel__subtitle\">Stress test block for <code>/expert/alexa-r</code></p>\n  </header>\n  <article class=\"iwa-dynamic-panel__body\">\n    <p>Seed {{seed}} injects synthetic content to expose brittle selectors and assertions.</p>\n    <ul class=\"iwa-dynamic-panel__list\">\n      <li data-role=\"summary\">DOM target: <strong>/expert/alexa-r</strong></li>\n      <li data-role=\"selector\">Selector impact: <code>#00</code></li>\n      <li data-role=\"note\">Always ensure your automation tolerates this block.</li>\n    </ul>\n  </article>\n  <footer>\n    <button class=\"iwa-dynamic-panel__cta\">Acknowledge variant {{seed}}</button>\n  </footer>\n</section>",
      "attribute": null,
      "value": null,
      "text": null,
      "new_name": null,
      "url_pattern": "/expert/alexa-r",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "expert_alexa_r-d1-1-wrap",
      "phase": "d1",
      "selector": "nav",
      "operation": "wrap_with",
      "html": "<section class=\"iwa-dynamic-panel iwa-dynamic-panel--secondary\" data-seed=\"{{seed}}\" data-path=\"/expert/alexa-r\">\n  <header>\n    <h2>Variant {{seed}} preview</h2>\n    <p class=\"iwa-dynamic-panel__subtitle\">Stress test block for <code>/expert/alexa-r</code></p>\n  </header>\n  <article class=\"iwa-dynamic-panel__body\">\n    <p>Seed {{seed}} injects synthetic content to expose brittle selectors and assertions.</p>\n    <ul class=\"iwa-dynamic-panel__list\">\n      <li data-role=\"summary\">DOM target: <strong>/expert/alexa-r</strong></li>\n      <li data-role=\"selector\">Selector impact: <code>#01</code></li>\n      <li data-role=\"note\">Always ensure your automation tolerates this block.</li>\n    </ul>\n  </article>\n  <footer>\n    <button class=\"iwa-dynamic-panel__cta\">Acknowledge variant {{seed}}</button>\n  </footer>\n</section>",
      "attribute": null,
      "value": null,
      "text": null,
      "new_name": null,
      "url_pattern": "/expert/alexa-r",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "expert_alexa_r-d1-1-insert-after",
      "phase": "d1",
      "selector": "nav",
      "operation": "insert_after",
      "html": "<aside class='iwa-palette-banner' data-seed='{{seed}}'>Seed {{seed}} activated for <code>/expert/alexa-r</code></aside>",
      "attribute": null,
      "value": null,
      "text": null,
      "new_name": null,
      "url_pattern": "/expert/alexa-r",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "expert_alexa_r-d1-1-replace",
      "phase": "d1",
      "selector": "nav",
      "operation": "replace_inner_html",
      "html": "<section class=\"iwa-dynamic-panel iwa-dynamic-panel--secondary\" data-seed=\"{{seed}}\" data-path=\"/expert/alexa-r\">\n  <header>\n    <h2>Variant {{seed}} preview</h2>\n    <p class=\"iwa-dynamic-panel__subtitle\">Stress test block for <code>/expert/alexa-r</code></p>\n  </header>\n  <article class=\"iwa-dynamic-panel__body\">\n    <p>Seed {{seed}} injects synthetic content to expose brittle selectors and assertions.</p>\n    <ul class=\"iwa-dynamic-panel__list\">\n      <li data-role=\"summary\">DOM target: <strong>/expert/alexa-r</strong></li>\n      <li data-role=\"selector\">Selector impact: <code>#01</code></li>\n      <li data-role=\"note\">Always ensure your automation tolerates this block.</li>\n    </ul>\n  </article>\n  <footer>\n    <button class=\"iwa-dynamic-panel__cta\">Acknowledge variant {{seed}}</button>\n  </footer>\n</section>",
      "attribute": null,
      "value": null,
      "text": null,
      "new_name": null,
      "url_pattern": "/expert/alexa-r",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "expert_alexa_r-d1-2-wrap",
      "phase": "d1",
      "selector": "main",
      "operation": "wrap_with",
      "html": "<section class=\"iwa-dynamic-panel iwa-dynamic-panel--accent\" data-seed=\"{{seed}}\" data-path=\"/expert/alexa-r\">\n  <header>\n    <h2>Variant {{seed}} preview</h2>\n    <p class=\"iwa-dynamic-panel__subtitle\">Stress test block for <code>/expert/alexa-r</code></p>\n  </header>\n  <article class=\"iwa-dynamic-panel__body\">\n    <p>Seed {{seed}} injects synthetic content to expose brittle selectors and assertions.</p>\n    <ul class=\"iwa-dynamic-panel__list\">\n      <li data-role=\"summary\">DOM target: <strong>/expert/alexa-r</strong></li>\n      <li data-role=\"selector\">Selector impact: <code>#02</code></li>\n      <li data-role=\"note\">Always ensure your automation tolerates this block.</li>\n    </ul>\n  </article>\n  <footer>\n    <button class=\"iwa-dynamic-panel__cta\">Acknowledge variant {{seed}}</button>\n  </footer>\n</section>",
      "attribute": null,
      "value": null,
      "text": null,
      "new_name": null,
      "url_pattern": "/expert/alexa-r",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "expert_alexa_r-d1-2-insert-after",
      "phase": "d1",
      "selector": "main",
      "operation": "insert_after",
      "html": "<aside class='iwa-palette-banner' data-seed='{{seed}}'>Seed {{seed}} activated for <code>/expert/alexa-r</code></aside>",
      "attribute": null,
      "value": null,
      "text": null,
      "new_name": null,
      "url_pattern": "/expert/alexa-r",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "expert_alexa_r-d1-2-replace",
      "phase": "d1",
      "selector": "main",
      "operation": "replace_inner_html",
      "html": "<section class=\"iwa-dynamic-panel iwa-dynamic-panel--accent\" data-seed=\"{{seed}}\" data-path=\"/expert/alexa-r\">\n  <header>\n    <h2>Variant {{seed}} preview</h2>\n    <p class=\"iwa-dynamic-panel__subtitle\">Stress test block for <code>/expert/alexa-r</code></p>\n  </header>\n  <article class=\"iwa-dynamic-panel__body\">\n    <p>Seed {{seed}} injects synthetic content to expose brittle selectors and assertions.</p>\n    <ul class=\"iwa-dynamic-panel__list\">\n      <li data-role=\"summary\">DOM target: <strong>/expert/alexa-r</strong></li>\n      <li data-role=\"selector\">Selector impact: <code>#02</code></li>\n      <li data-role=\"note\">Always ensure your automation tolerates this block.</li>\n    </ul>\n  </article>\n  <footer>\n    <button class=\"iwa-dynamic-panel__cta\">Acknowledge variant {{seed}}</button>\n  </footer>\n</section>",
      "attribute": null,
      "value": null,
      "text": null,
      "new_name": null,
      "url_pattern": "/expert/alexa-r",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "expert_alexa_r-d1-3-wrap",
      "phase": "d1",
      "selector": "aside",
      "operation": "wrap_with",
      "html": "<section class=\"iwa-dynamic-panel iwa-dynamic-panel--muted\" data-seed=\"{{seed}}\" data-path=\"/expert/alexa-r\">\n  <header>\n    <h2>Variant {{seed}} preview</h2>\n    <p class=\"iwa-dynamic-panel__subtitle\">Stress test block for <code>/expert/alexa-r</code></p>\n  </header>\n  <article class=\"iwa-dynamic-panel__body\">\n    <p>Seed {{seed}} injects synthetic content to expose brittle selectors and assertions.</p>\n    <ul class=\"iwa-dynamic-panel__list\">\n      <li data-role=\"summary\">DOM target: <strong>/expert/alexa-r</strong></li>\n      <li data-role=\"selector\">Selector impact: <code>#03</code></li>\n      <li data-role=\"note\">Always ensure your automation tolerates this block.</li>\n    </ul>\n  </article>\n  <footer>\n    <button class=\"iwa-dynamic-panel__cta\">Acknowledge variant {{seed}}</button>\n  </footer>\n</section>",
      "attribute": null,
      "value": null,
      "text": null,
      "new_name": null,
      "url_pattern": "/expert/alexa-r",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "expert_alexa_r-d1-3-insert-after",
      "phase": "d1",
      "selector": "aside",
      "operation": "insert_after",
      "html": "<aside class='iwa-palette-banner' data-seed='{{seed}}'>Seed {{seed}} activated for <code>/expert/alexa-r</code></aside>",
      "attribute": null,
      "value": null,
      "text": null,
      "new_name": null,
      "url_pattern": "/expert/alexa-r",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "expert_alexa_r-d1-3-replace",
      "phase": "d1",
      "selector": "aside",
      "operation": "replace_inner_html",
      "html": "<section class=\"iwa-dynamic-panel iwa-dynamic-panel--muted\" data-seed=\"{{seed}}\" data-path=\"/expert/alexa-r\">\n  <header>\n    <h2>Variant {{seed}} preview</h2>\n    <p class=\"iwa-dynamic-panel__subtitle\">Stress test block for <code>/expert/alexa-r</code></p>\n  </header>\n  <article class=\"iwa-dynamic-panel__body\">\n    <p>Seed {{seed}} injects synthetic content to expose brittle selectors and assertions.</p>\n    <ul class=\"iwa-dynamic-panel__list\">\n      <li data-role=\"summary\">DOM target: <strong>/expert/alexa-r</strong></li>\n      <li data-role=\"selector\">Selector impact: <code>#03</code></li>\n      <li data-role=\"note\">Always ensure your automation tolerates this block.</li>\n    </ul>\n  </article>\n  <footer>\n    <button class=\"iwa-dynamic-panel__cta\">Acknowledge variant {{seed}}</button>\n  </footer>\n</section>",
      "attribute": null,
      "value": null,
      "text": null,
      "new_name": null,
      "url_pattern": "/expert/alexa-r",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "expert_alexa_r-d1-4-wrap",
      "phase": "d1",
      "selector": ".flex",
      "operation": "wrap_with",
      "html": "<section class=\"iwa-dynamic-panel iwa-dynamic-panel--primary\" data-seed=\"{{seed}}\" data-path=\"/expert/alexa-r\">\n  <header>\n    <h2>Variant {{seed}} preview</h2>\n    <p class=\"iwa-dynamic-panel__subtitle\">Stress test block for <code>/expert/alexa-r</code></p>\n  </header>\n  <article class=\"iwa-dynamic-panel__body\">\n    <p>Seed {{seed}} injects synthetic content to expose brittle selectors and assertions.</p>\n    <ul class=\"iwa-dynamic-panel__list\">\n      <li data-role=\"summary\">DOM target: <strong>/expert/alexa-r</strong></li>\n      <li data-role=\"selector\">Selector impact: <code>#04</code></li>\n      <li data-role=\"note\">Always ensure your automation tolerates this block.</li>\n    </ul>\n  </article>\n  <footer>\n    <button class=\"iwa-dynamic-panel__cta\">Acknowledge variant {{seed}}</button>\n  </footer>\n</section>",
      "attribute": null,
      "value": null,
      "text": null,
      "new_name": null,
      "url_pattern": "/expert/alexa-r",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "expert_alexa_r-d1-4-insert-after",
      "phase": "d1",
      "selector": ".flex",
      "operation": "insert_after",
      "html": "<aside class='iwa-palette-banner' data-seed='{{seed}}'>Seed {{seed}} activated for <code>/expert/alexa-r</code></aside>",
      "attribute": null,
      "value": null,
      "text": null,
      "new_name": null,
      "url_pattern": "/expert/alexa-r",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "expert_alexa_r-d1-4-replace",
      "phase": "d1",
      "selector": ".flex",
      "operation": "replace_inner_html",
      "html": "<section class=\"iwa-dynamic-panel iwa-dynamic-panel--primary\" data-seed=\"{{seed}}\" data-path=\"/expert/alexa-r\">\n  <header>\n    <h2>Variant {{seed}} preview</h2>\n    <p class=\"iwa-dynamic-panel__subtitle\">Stress test block for <code>/expert/alexa-r</code></p>\n  </header>\n  <article class=\"iwa-dynamic-panel__body\">\n    <p>Seed {{seed}} injects synthetic content to expose brittle selectors and assertions.</p>\n    <ul class=\"iwa-dynamic-panel__list\">\n      <li data-role=\"summary\">DOM target: <strong>/expert/alexa-r</strong></li>\n      <li data-role=\"selector\">Selector impact: <code>#04</code></li>\n      <li data-role=\"note\">Always ensure your automation tolerates this block.</li>\n    </ul>\n  </article>\n  <footer>\n    <button class=\"iwa-dynamic-panel__cta\">Acknowledge variant {{seed}}</button>\n  </footer>\n</section>",
      "attribute": null,
      "value": null,
      "text": null,
      "new_name": null,
      "url_pattern": "/expert/alexa-r",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "expert_alexa_r-d1-5-wrap",
      "phase": "d1",
      "selector": ".items-center",
      "operation": "wrap_with",
      "html": "<section class=\"iwa-dynamic-panel iwa-dynamic-panel--secondary\" data-seed=\"{{seed}}\" data-path=\"/expert/alexa-r\">\n  <header>\n    <h2>Variant {{seed}} preview</h2>\n    <p class=\"iwa-dynamic-panel__subtitle\">Stress test block for <code>/expert/alexa-r</code></p>\n  </header>\n  <article class=\"iwa-dynamic-panel__body\">\n    <p>Seed {{seed}} injects synthetic content to expose brittle selectors and assertions.</p>\n    <ul class=\"iwa-dynamic-panel__list\">\n      <li data-role=\"summary\">DOM target: <strong>/expert/alexa-r</strong></li>\n      <li data-role=\"selector\">Selector impact: <code>#05</code></li>\n      <li data-role=\"note\">Always ensure your automation tolerates this block.</li>\n    </ul>\n  </article>\n  <footer>\n    <button class=\"iwa-dynamic-panel__cta\">Acknowledge variant {{seed}}</button>\n  </footer>\n</section>",
      "attribute": null,
      "value": null,
      "text": null,
      "new_name": null,
      "url_pattern": "/expert/alexa-r",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "expert_alexa_r-d1-5-insert-after",
      "phase": "d1",
      "selector": ".items-center",
      "operation": "insert_after",
      "html": "<aside class='iwa-palette-banner' data-seed='{{seed}}'>Seed {{seed}} activated for <code>/expert/alexa-r</code></aside>",
      "attribute": null,
      "value": null,
      "text": null,
      "new_name": null,
      "url_pattern": "/expert/alexa-r",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "expert_alexa_r-d1-5-replace",
      "phase": "d1",
      "selector": ".items-center",
      "operation": "replace_inner_html",
      "html": "<section class=\"iwa-dynamic-panel iwa-dynamic-panel--secondary\" data-seed=\"{{seed}}\" data-path=\"/expert/alexa-r\">\n  <header>\n    <h2>Variant {{seed}} preview</h2>\n    <p class=\"iwa-dynamic-panel__subtitle\">Stress test block for <code>/expert/alexa-r</code></p>\n  </header>\n  <article class=\"iwa-dynamic-panel__body\">\n    <p>Seed {{seed}} injects synthetic content to expose brittle selectors and assertions.</p>\n    <ul class=\"iwa-dynamic-panel__list\">\n      <li data-role=\"summary\">DOM target: <strong>/expert/alexa-r</strong></li>\n      <li data-role=\"selector\">Selector impact: <code>#05</code></li>\n      <li data-role=\"note\">Always ensure your automation tolerates this block.</li>\n    </ul>\n  </article>\n  <footer>\n    <button class=\"iwa-dynamic-panel__cta\">Acknowledge variant {{seed}}</button>\n  </footer>\n</section>",
      "attribute": null,
      "value": null,
      "text": null,
      "new_name": null,
      "url_pattern": "/expert/alexa-r",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "expert_alexa_r-d3-0-data",
      "phase": "d3",
      "selector": "header",
      "operation": "set_attribute",
      "html": null,
      "attribute": "data-iwa-variant",
      "value": "/expert/alexa-r-variant-{{seed}}",
      "text": null,
      "new_name": null,
      "url_pattern": "/expert/alexa-r",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "expert_alexa_r-d3-0-class",
      "phase": "d3",
      "selector": "header",
      "operation": "append_class",
      "html": null,
      "attribute": null,
      "value": "iwa-variant-{{seed}}",
      "text": null,
      "new_name": null,
      "url_pattern": "/expert/alexa-r",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "expert_alexa_r-d3-0-text",
      "phase": "d3",
      "selector": "header",
      "operation": "replace_text",
      "html": null,
      "attribute": null,
      "value": null,
      "text": "Dynamic copy for /expert/alexa-r – seed {{seed}}",
      "new_name": null,
      "url_pattern": "/expert/alexa-r",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "expert_alexa_r-d3-1-data",
      "phase": "d3",
      "selector": "nav",
      "operation": "set_attribute",
      "html": null,
      "attribute": "data-iwa-variant",
      "value": "/expert/alexa-r-variant-{{seed}}",
      "text": null,
      "new_name": null,
      "url_pattern": "/expert/alexa-r",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "expert_alexa_r-d3-1-class",
      "phase": "d3",
      "selector": "nav",
      "operation": "append_class",
      "html": null,
      "attribute": null,
      "value": "iwa-variant-{{seed}}",
      "text": null,
      "new_name": null,
      "url_pattern": "/expert/alexa-r",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "expert_alexa_r-d3-1-text",
      "phase": "d3",
      "selector": "nav",
      "operation": "replace_text",
      "html": null,
      "attribute": null,
      "value": null,
      "text": "Dynamic copy for /expert/alexa-r – seed {{seed}}",
      "new_name": null,
      "url_pattern": "/expert/alexa-r",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "expert_alexa_r-d3-2-data",
      "phase": "d3",
      "selector": "main",
      "operation": "set_attribute",
      "html": null,
      "attribute": "data-iwa-variant",
      "value": "/expert/alexa-r-variant-{{seed}}",
      "text": null,
      "new_name": null,
      "url_pattern": "/expert/alexa-r",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "expert_alexa_r-d3-2-class",
      "phase": "d3",
      "selector": "main",
      "operation": "append_class",
      "html": null,
      "attribute": null,
      "value": "iwa-variant-{{seed}}",
      "text": null,
      "new_name": null,
      "url_pattern": "/expert/alexa-r",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "expert_alexa_r-d3-2-text",
      "phase": "d3",
      "selector": "main",
      "operation": "replace_text",
      "html": null,
      "attribute": null,
      "value": null,
      "text": "Dynamic copy for /expert/alexa-r – seed {{seed}}",
      "new_name": null,
      "url_pattern": "/expert/alexa-r",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "expert_alexa_r-d3-3-data",
      "phase": "d3",
      "selector": "aside",
      "operation": "set_attribute",
      "html": null,
      "attribute": "data-iwa-variant",
      "value": "/expert/alexa-r-variant-{{seed}}",
      "text": null,
      "new_name": null,
      "url_pattern": "/expert/alexa-r",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "expert_alexa_r-d3-3-class",
      "phase": "d3",
      "selector": "aside",
      "operation": "append_class",
      "html": null,
      "attribute": null,
      "value": "iwa-variant-{{seed}}",
      "text": null,
      "new_name": null,
      "url_pattern": "/expert/alexa-r",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "expert_alexa_r-d3-3-text",
      "phase": "d3",
      "selector": "aside",
      "operation": "replace_text",
      "html": null,
      "attribute": null,
      "value": null,
      "text": "Dynamic copy for /expert/alexa-r – seed {{seed}}",
      "new_name": null,
      "url_pattern": "/expert/alexa-r",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "expert_alexa_r-d3-4-data",
      "phase": "d3",
      "selector": ".flex",
      "operation": "set_attribute",
      "html": null,
      "attribute": "data-iwa-variant",
      "value": "/expert/alexa-r-variant-{{seed}}",
      "text": null,
      "new_name": null,
      "url_pattern": "/expert/alexa-r",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "expert_alexa_r-d3-4-class",
      "phase": "d3",
      "selector": ".flex",
      "operation": "append_class",
      "html": null,
      "attribute": null,
      "value": "iwa-variant-{{seed}}",
      "text": null,
      "new_name": null,
      "url_pattern": "/expert/alexa-r",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "expert_alexa_r-d3-4-text",
      "phase": "d3",
      "selector": ".flex",
      "operation": "replace_text",
      "html": null,
      "attribute": null,
      "value": null,
      "text": "Dynamic copy for /expert/alexa-r – seed {{seed}}",
      "new_name": null,
      "url_pattern": "/expert/alexa-r",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "expert_alexa_r-d3-5-data",
      "phase": "d3",
      "selector": ".items-center",
      "operation": "set_attribute",
      "html": null,
      "attribute": "data-iwa-variant",
      "value": "/expert/alexa-r-variant-{{seed}}",
      "text": null,
      "new_name": null,
      "url_pattern": "/expert/alexa-r",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "expert_alexa_r-d3-5-class",
      "phase": "d3",
      "selector": ".items-center",
      "operation": "append_class",
      "html": null,
      "attribute": null,
      "value": "iwa-variant-{{seed}}",
      "text": null,
      "new_name": null,
      "url_pattern": "/expert/alexa-r",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "expert_alexa_r-d3-5-text",
      "phase": "d3",
      "selector": ".items-center",
      "operation": "replace_text",
      "html": null,
      "attribute": null,
      "value": null,
      "text": "Dynamic copy for /expert/alexa-r – seed {{seed}}",
      "new_name": null,
      "url_pattern": "/expert/alexa-r",
      "weight": 1.0,
      "overlay_type": null,
      "blocking": false,
      "dismiss_selector": null,
      "trigger_after": null
    },
    {
      "id": "expert_alexa_r-d4-3",
      "phase": "d4",
      "selector": "body",
      "operation": "overlay",
      "html": "<div class='iwa-overlay iwa-overlay--banner' style='position:fixed;top:0;left:0;right:0;background:rgba(15,23,42,0.9);color:#fff;padding:18px;z-index:2147483647;font-family:sans-serif;'><div style='display:flex;flex-direction:column;gap:12px;align-items:flex-start;'><strong>Autoppia dynamic challenge</strong><span>Please confirm you accept the latest terms to continue browsing.</span><button data-iwa-dismiss style='padding:8px 16px;border:none;border-radius:8px;background:#2563eb;color:#fff;'>Continue</button></div></div>",
      "attribute": null,
      "value": null,
      "text": null,
      "new_name": null,
      "url_pattern": "/expert/alexa-r",
      "weight": 1.0,
      "overlay_type": "banner",
      "blocking": false,
      "dismiss_selector": "[data-iwa-dismiss]",
      "trigger_after": 2
    },
    {
      "id": "expert_alexa_r-d4-5",
      "phase": "d4",
      "selector": "body",
      "operation": "overlay",
      "html": "<div class='iwa-overlay iwa-overlay--cookie' style='position:fixed;center:0;left:0;right:0;background:rgba(15,23,42,0.9);color:#fff;padding:18px;z-index:2147483647;font-family:sans-serif;'><div style='display:flex;flex-direction:column;gap:12px;align-items:flex-start;'><strong>Autoppia dynamic challenge</strong><span>Please confirm you accept the latest terms to continue browsing.</span><button data-iwa-dismiss style='padding:8px 16px;border:none;border-radius:8px;background:#2563eb;color:#fff;'>Continue</button></div></div>",
      "attribute": null,
      "value": null,
      "text": null,
      "new_name": null,
      "url_pattern": "/expert/alexa-r",
      "weight": 1.0,
      "overlay_type": "cookie",
      "blocking": true,
      "dismiss_selector": "[data-iwa-dismiss]",
      "trigger_after": 4
    },
    {
      "id": "expert_alexa_r-d4-7",
      "phase": "d4",
      "selector": "body",
      "operation": "overlay",
      "html": "<div class='iwa-overlay iwa-overlay--modal' style='position:fixed;bottom:0;left:0;right:0;background:rgba(15,23,42,0.9);color:#fff;padding:18px;z-index:2147483647;font-family:sans-serif;'><div style='display:flex;flex-direction:column;gap:12px;align-items:flex-start;'><strong>Autoppia dynamic challenge</strong><span>Please confirm you accept the latest terms to continue browsing.</span><button data-iwa-dismiss style='padding:8px 16px;border:none;border-radius:8px;background:#2563eb;color:#fff;'>Continue</button></div></div>",
      "attribute": null,
      "value": null,
      "text": null,
      "new_name": null,
      "url_pattern": "/expert/alexa-r",
      "weight": 1.0,
      "overlay_type": "modal",
      "blocking": true,
      "dismiss_selector": "[data-iwa-dismiss]",
      "trigger_after": 3
    }
  ]
}
""")

palette = MutationPalette.model_validate(PALETTE_DATA)
