from datetime import datetime

from ...projects.operators import (
    CONTAINS,
    EQUALS,
    GREATER_EQUAL,
    GREATER_THAN,
    LESS_EQUAL,
    LESS_THAN,
    NOT_CONTAINS,
    NOT_EQUALS,
)

TASKS_DATA = [
    {
        "name": "Buy groceries",
        "description": "Milk, Bread, Eggs, and Cheese",
        "date": datetime(2025, 8, 15),
        "priority": 1,
        "priority_label": "High",
        "action": "add",
        "source": "main_view",
        "is_editing": False,
        "was_previously_selected": False,
    },
    {
        "name": "Finish project report",
        "description": "Complete the Q3 financial analysis section.",
        "date": datetime(2025, 8, 20),
        "priority": 2,
        "priority_label": "Medium",
        "action": "update",
        "source": "task_modal",
        "is_editing": True,
        "was_previously_selected": True,
    },
    {
        "name": "Call the doctor",
        "description": "Schedule annual check-up.",
        "date": datetime(2025, 9, 1),
        "priority": 3,
        "priority_label": "Low",
        "action": "add",
        "source": "quick_add",
        "is_editing": False,
        "was_previously_selected": False,
    },
    {
        "name": "Plan team meeting",
        "description": "Agenda: review sprint goals and assign tasks.",
        "date": None,
        "priority": 4,
        "priority_label": "None",
        "action": "add",
        "source": "main_view",
        "is_editing": False,
        "was_previously_selected": False,
    },
    {
        "name": "Prepare Q4 presentation",
        "description": "Include sales data and projections.",
        "date": datetime(2025, 10, 28),
        "priority": 1,
        "priority_label": "High",
        "action": "add",
        "source": "main_view",
        "is_editing": False,
        "was_previously_selected": False,
    },
    {
        "name": "Submit expense report",
        "description": "For the business trip to New York.",
        "date": datetime(2025, 9, 5),
        "priority": 2,
        "priority_label": "Medium",
        "action": "update",
        "source": "task_modal",
        "is_editing": True,
        "was_previously_selected": True,
    },
    {
        "name": "Follow up with ClientX",
        "description": "Regarding the contract renewal.",
        "date": datetime(2025, 8, 22),
        "priority": 1,
        "priority_label": "High",
        "action": "add",
        "source": "quick_add",
        "is_editing": False,
        "was_previously_selected": False,
    },
    {
        "name": "Update project timeline",
        "description": "Reflect the new feature release date.",
        "date": None,
        "priority": 2,
        "priority_label": "Medium",
        "action": "update",
        "source": "main_view",
        "is_editing": True,
        "was_previously_selected": False,
    },
    {
        "name": "Organize team offsite",
        "description": "Book venue and plan activities.",
        "date": datetime(2025, 11, 15),
        "priority": 3,
        "priority_label": "Low",
        "action": "add",
        "source": "task_modal",
        "is_editing": False,
        "was_previously_selected": True,
    },
    {
        "name": "Book flights to Denver",
        "description": "For the conference in October.",
        "date": datetime(2025, 9, 10),
        "priority": 1,
        "priority_label": "High",
        "action": "add",
        "source": "quick_add",
        "is_editing": False,
        "was_previously_selected": False,
    },
    {
        "name": "Renew driver's license",
        "description": "Appointment at the DMV on Tuesday.",
        "date": datetime(2026, 1, 20),
        "priority": 2,
        "priority_label": "Medium",
        "action": "add",
        "source": "main_view",
        "is_editing": False,
        "was_previously_selected": False,
    },
    {
        "name": "Clean the garage",
        "description": "Sort out old boxes and tools.",
        "date": datetime(2025, 9, 13),
        "priority": 4,
        "priority_label": "None",
        "action": "add",
        "source": "main_view",
        "is_editing": False,
        "was_previously_selected": False,
    },
    {
        "name": "Water the plants",
        "description": "Especially the new ones on the balcony.",
        "date": None,
        "priority": 3,
        "priority_label": "Low",
        "action": "add",
        "source": "quick_add",
        "is_editing": False,
        "was_previously_selected": False,
    },
    {
        "name": "Call mom",
        "description": "Wish her a happy birthday.",
        "date": datetime(2025, 10, 5),
        "priority": 1,
        "priority_label": "High",
        "action": "add",
        "source": "main_view",
        "is_editing": False,
        "was_previously_selected": False,
    },
    {
        "name": "Go for a 5k run",
        "description": "Morning run in the park.",
        "date": datetime(2025, 8, 18),
        "priority": 3,
        "priority_label": "Low",
        "action": "add",
        "source": "quick_add",
        "is_editing": False,
        "was_previously_selected": False,
    },
    {
        "name": "Schedule dentist appointment",
        "description": "For a routine check-up and cleaning.",
        "date": datetime(2025, 9, 25),
        "priority": 2,
        "priority_label": "Medium",
        "action": "add",
        "source": "task_modal",
        "is_editing": False,
        "was_previously_selected": True,
    },
    {
        "name": "Meal prep for the week",
        "description": "Chicken, rice, and vegetables.",
        "date": datetime(2025, 8, 24),
        "priority": 2,
        "priority_label": "Medium",
        "action": "add",
        "source": "main_view",
        "is_editing": False,
        "was_previously_selected": False,
    },
    {
        "name": "Yoga session",
        "description": "Evening relaxation yoga.",
        "date": None,
        "priority": 4,
        "priority_label": "None",
        "action": "add",
        "source": "quick_add",
        "is_editing": False,
        "was_previously_selected": False,
    },
    {
        "name": "Pay credit card bill",
        "description": "Due on the 25th.",
        "date": datetime(2025, 8, 25),
        "priority": 1,
        "priority_label": "High",
        "action": "update",
        "source": "task_modal",
        "is_editing": True,
        "was_previously_selected": True,
    },
    {
        "name": "Review monthly budget",
        "description": "Check spending in all categories.",
        "date": datetime(2025, 8, 31),
        "priority": 2,
        "priority_label": "Medium",
        "action": "add",
        "source": "main_view",
        "is_editing": False,
        "was_previously_selected": False,
    },
    {
        "name": "File taxes",
        "description": "Deadline is approaching.",
        "date": datetime(2026, 4, 10),
        "priority": 1,
        "priority_label": "High",
        "action": "add",
        "source": "main_view",
        "is_editing": False,
        "was_previously_selected": False,
    },
    {
        "name": "Research investment options",
        "description": "Look into index funds and ETFs.",
        "date": None,
        "priority": 3,
        "priority_label": "Low",
        "action": "add",
        "source": "quick_add",
        "is_editing": False,
        "was_previously_selected": False,
    },
    {
        "name": "Read 'Atomic Habits'",
        "description": "One chapter every day.",
        "date": None,
        "priority": 4,
        "priority_label": "None",
        "action": "add",
        "source": "main_view",
        "is_editing": False,
        "was_previously_selected": False,
    },
    {
        "name": "Complete Python course module 5",
        "description": "Focus on object-oriented programming.",
        "date": datetime(2025, 9, 12),
        "priority": 2,
        "priority_label": "Medium",
        "action": "update",
        "source": "task_modal",
        "is_editing": True,
        "was_previously_selected": True,
    },
    {
        "name": "Practice Spanish on Duolingo",
        "description": "15 minutes daily.",
        "date": None,
        "priority": 3,
        "priority_label": "Low",
        "action": "add",
        "source": "quick_add",
        "is_editing": False,
        "was_previously_selected": False,
    },
    {
        "name": "Fix leaky faucet",
        "description": "In the kitchen sink.",
        "date": datetime(2025, 8, 19),
        "priority": 1,
        "priority_label": "High",
        "action": "add",
        "source": "main_view",
        "is_editing": False,
        "was_previously_selected": False,
    },
    {
        "name": "Mow the lawn",
        "description": "Before the weekend.",
        "date": datetime(2025, 8, 23),
        "priority": 3,
        "priority_label": "Low",
        "action": "add",
        "source": "main_view",
        "is_editing": False,
        "was_previously_selected": False,
    },
    {
        "name": "Organize the pantry",
        "description": "Check for expired items.",
        "date": None,
        "priority": 4,
        "priority_label": "None",
        "action": "add",
        "source": "quick_add",
        "is_editing": False,
        "was_previously_selected": False,
    },
    {
        "name": "Change air filters",
        "description": "For the HVAC system.",
        "date": datetime(2025, 10, 1),
        "priority": 2,
        "priority_label": "Medium",
        "action": "add",
        "source": "task_modal",
        "is_editing": False,
        "was_previously_selected": True,
    },
    {
        "name": "Buy new light bulbs",
        "description": "For the living room lamp.",
        "date": None,
        "priority": 3,
        "priority_label": "Low",
        "action": "add",
        "source": "main_view",
        "is_editing": False,
        "was_previously_selected": False,
    },
    {
        "name": "Draft blog post",
        "description": "Topic: '10 Tips for Productivity'.",
        "date": datetime(2025, 9, 8),
        "priority": 2,
        "priority_label": "Medium",
        "action": "update",
        "source": "task_modal",
        "is_editing": True,
        "was_previously_selected": True,
    },
    {
        "name": "Brainstorm new project ideas",
        "description": "Mind map session.",
        "date": None,
        "priority": 3,
        "priority_label": "Low",
        "action": "add",
        "source": "quick_add",
        "is_editing": False,
        "was_previously_selected": False,
    },
    {
        "name": "Review pull request #123",
        "description": "Check for code quality and logic.",
        "date": datetime(2025, 8, 16),
        "priority": 1,
        "priority_label": "High",
        "action": "add",
        "source": "main_view",
        "is_editing": False,
        "was_previously_selected": False,
    },
    {
        "name": "Set up new development environment",
        "description": "Install Docker and VS Code extensions.",
        "date": None,
        "priority": 2,
        "priority_label": "Medium",
        "action": "add",
        "source": "task_modal",
        "is_editing": False,
        "was_previously_selected": True,
    },
    {
        "name": "Learn a new song on guitar",
        "description": "Start with 'Wonderwall'.",
        "date": None,
        "priority": 4,
        "priority_label": "None",
        "action": "add",
        "source": "main_view",
        "is_editing": False,
        "was_previously_selected": False,
    },
    {
        "name": "Plan weekend trip",
        "description": "Look for cabins in the mountains.",
        "date": datetime(2025, 9, 20),
        "priority": 2,
        "priority_label": "Medium",
        "action": "add",
        "source": "quick_add",
        "is_editing": False,
        "was_previously_selected": False,
    },
    {
        "name": "Do laundry",
        "description": "Separate whites and colors.",
        "date": datetime(2025, 8, 17),
        "priority": 3,
        "priority_label": "Low",
        "action": "add",
        "source": "main_view",
        "is_editing": False,
        "was_previously_selected": False,
    },
    {
        "name": "Pay rent",
        "description": "Due on the 1st of the month.",
        "date": datetime(2025, 9, 1),
        "priority": 1,
        "priority_label": "High",
        "action": "add",
        "source": "task_modal",
        "is_editing": False,
        "was_previously_selected": True,
    },
    {
        "name": "Create a new workout plan",
        "description": "Focus on strength training.",
        "date": None,
        "priority": 2,
        "priority_label": "Medium",
        "action": "add",
        "source": "quick_add",
        "is_editing": False,
        "was_previously_selected": False,
    },
    {
        "name": "Meditate for 10 minutes",
        "description": "Use the Calm app.",
        "date": None,
        "priority": 3,
        "priority_label": "Low",
        "action": "add",
        "source": "main_view",
        "is_editing": False,
        "was_previously_selected": False,
    },
    {
        "name": "Update resume",
        "description": "Add recent work experience.",
        "date": datetime(2025, 9, 30),
        "priority": 2,
        "priority_label": "Medium",
        "action": "update",
        "source": "task_modal",
        "is_editing": True,
        "was_previously_selected": True,
    },
    {
        "name": "Network on LinkedIn",
        "description": "Connect with 5 new people in the industry.",
        "date": None,
        "priority": 3,
        "priority_label": "Low",
        "action": "add",
        "source": "quick_add",
        "is_editing": False,
        "was_previously_selected": False,
    },
    {
        "name": "Cancel unused subscriptions",
        "description": "Review bank statements for recurring charges.",
        "date": datetime(2025, 8, 28),
        "priority": 2,
        "priority_label": "Medium",
        "action": "add",
        "source": "main_view",
        "is_editing": False,
        "was_previously_selected": False,
    },
    {
        "name": "Bake a cake",
        "description": "For the office party.",
        "date": datetime(2025, 9, 19),
        "priority": 3,
        "priority_label": "Low",
        "action": "add",
        "source": "main_view",
        "is_editing": False,
        "was_previously_selected": False,
    },
    {
        "name": "Take the car for an oil change",
        "description": "Service is overdue.",
        "date": datetime(2025, 9, 15),
        "priority": 2,
        "priority_label": "Medium",
        "action": "add",
        "source": "task_modal",
        "is_editing": False,
        "was_previously_selected": True,
    },
    {
        "name": "Organize digital files",
        "description": "Clean up the desktop and downloads folder.",
        "date": None,
        "priority": 4,
        "priority_label": "None",
        "action": "add",
        "source": "quick_add",
        "is_editing": False,
        "was_previously_selected": False,
    },
    {
        "name": "Write a thank-you note",
        "description": "To the person who helped with the project.",
        "date": datetime(2025, 8, 21),
        "priority": 3,
        "priority_label": "Low",
        "action": "add",
        "source": "main_view",
        "is_editing": False,
        "was_previously_selected": False,
    },
    {
        "name": "Volunteer at the local shelter",
        "description": "Saturday morning shift.",
        "date": datetime(2025, 9, 6),
        "priority": 3,
        "priority_label": "Low",
        "action": "add",
        "source": "main_view",
        "is_editing": False,
        "was_previously_selected": False,
    },
    {
        "name": "Watch a classic movie",
        "description": "From the AFI Top 100 list.",
        "date": None,
        "priority": 4,
        "priority_label": "None",
        "action": "add",
        "source": "quick_add",
        "is_editing": False,
        "was_previously_selected": False,
    },
    {
        "name": "Listen to a new podcast episode",
        "description": "Tech-related podcast.",
        "date": None,
        "priority": 4,
        "priority_label": "None",
        "action": "add",
        "source": "main_view",
        "is_editing": False,
        "was_previously_selected": False,
    },
    {
        "name": "Fix bug #456 in the main branch",
        "description": "Critical issue reported by a user.",
        "date": datetime(2025, 8, 16),
        "priority": 1,
        "priority_label": "High",
        "action": "update",
        "source": "task_modal",
        "is_editing": True,
        "was_previously_selected": True,
    },
    {
        "name": "Deploy staging server updates",
        "description": "Coordinate with the DevOps team.",
        "date": datetime(2025, 8, 29),
        "priority": 1,
        "priority_label": "High",
        "action": "add",
        "source": "main_view",
        "is_editing": False,
        "was_previously_selected": False,
    },
    {
        "name": "Create user documentation",
        "description": "For the new API endpoint.",
        "date": datetime(2025, 9, 18),
        "priority": 2,
        "priority_label": "Medium",
        "action": "add",
        "source": "task_modal",
        "is_editing": False,
        "was_previously_selected": True,
    },
    {
        "name": "Attend the weekly sync meeting",
        "description": "Be prepared to give an update.",
        "date": datetime(2025, 8, 19),
        "priority": 2,
        "priority_label": "Medium",
        "action": "add",
        "source": "main_view",
        "is_editing": False,
        "was_previously_selected": False,
    },
]
LOGICAL_OPERATORS = [EQUALS, NOT_EQUALS, GREATER_EQUAL, GREATER_THAN, LESS_EQUAL, LESS_THAN]
STRING_OPERATORS = [EQUALS, NOT_EQUALS, CONTAINS, NOT_CONTAINS]
EQUALITY_OPERATORS = [EQUALS, NOT_EQUALS]


# --- Field Operator Mappings ---
FIELD_OPERATORS_SELECT_DATE_MAP = {
    "selected_date": LOGICAL_OPERATORS,
    # "wasPreviouslySelected": EQUALITY_OPERATORS,
}
FIELD_OPERATORS_SELECT_PRIORITY_MAP = {
    "priority": LOGICAL_OPERATORS,
    "label": STRING_OPERATORS,
}
FIELD_OPERATORS_TASK_ADDED_MAP = {
    # "action": EQUALITY_OPERATORS,
    "name": STRING_OPERATORS,
    "description": STRING_OPERATORS,
    "priority": EQUALITY_OPERATORS,
}
FIELD_OPERATORS_CANCEL_TASK_MAP = {
    "current_name": STRING_OPERATORS,
    "priority": EQUALITY_OPERATORS,
    # "is_editing": EQUALITY_OPERATORS,
}
FIELD_OPERATORS_EDIT_MODAL_MAP = {
    "name": STRING_OPERATORS,
    "description": STRING_OPERATORS,
    "priority": STRING_OPERATORS,
}
